begin;
create table if not exists public.country_user_preferences (
 user_id uuid primary key references auth.users(id) on delete cascade,
 main_country_id uuid null references public.countries(id) on delete set null,
 active_country_id uuid null references public.countries(id) on delete set null,
 updated_at timestamptz not null default now()
);
alter table public.country_user_preferences enable row level security;
drop policy if exists "country prefs own" on public.country_user_preferences;
create policy "country prefs own" on public.country_user_preferences for all to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
grant select,insert,update,delete on public.country_user_preferences to authenticated;

-- Preference values must point to countries the user can manage.
drop policy if exists "country prefs own" on public.country_user_preferences;
create policy "country prefs own" on public.country_user_preferences for all to authenticated
using (user_id=auth.uid())
with check (
 user_id=auth.uid()
 and (main_country_id is null or exists(select 1 from public.countries c where c.id=main_country_id and (c.owner_id=auth.uid() or exists(select 1 from public.country_members m where m.country_id=c.id and m.user_id=auth.uid() and m.role in ('owner','admin','editor')))))
 and (active_country_id is null or exists(select 1 from public.countries c where c.id=active_country_id and (c.owner_id=auth.uid() or exists(select 1 from public.country_members m where m.country_id=c.id and m.user_id=auth.uid() and m.role in ('owner','admin','editor')))))
);

create or replace function public.mfdco_public_country_market_priorities()
returns table(country_id uuid,is_main boolean,is_active boolean)
language sql stable security definer set search_path=public
as $$
 select c.id,(p.main_country_id=c.id),(p.active_country_id=c.id)
 from public.countries c
 left join public.country_user_preferences p on p.user_id=c.owner_id
 where c.is_public=true and c.archived_at is null;
$$;
revoke all on function public.mfdco_public_country_market_priorities() from public;
grant execute on function public.mfdco_public_country_market_priorities() to anon,authenticated;


create table if not exists public.country_market_history (
 id bigint generated by default as identity primary key,
 country_id uuid not null references public.countries(id) on delete cascade,
 captured_hour timestamptz not null,
 market_date date not null,
 market_month text not null,
 market_hour text not null,
 change_pct numeric(9,4) not null default 0,
 fx_value numeric null,
 stock_value numeric null,
 world_average_pct numeric(9,4) null,
 themes jsonb not null default '{}'::jsonb,
 recorded_by uuid null references auth.users(id) on delete set null,
 created_at timestamptz not null default now(),
 unique(country_id,captured_hour)
);
create index if not exists country_market_history_country_time_idx on public.country_market_history(country_id,captured_hour desc);
alter table public.country_market_history enable row level security;
drop policy if exists "public market history read" on public.country_market_history;
create policy "public market history read" on public.country_market_history for select to anon,authenticated using (exists(select 1 from public.countries c where c.id=country_id and c.is_public=true and c.archived_at is null));
drop policy if exists "auth market history write" on public.country_market_history;
create policy "auth market history write" on public.country_market_history for insert to authenticated with check (recorded_by=auth.uid());
drop policy if exists "auth market history update" on public.country_market_history;
create policy "auth market history update" on public.country_market_history for update to authenticated using (recorded_by=auth.uid()) with check (recorded_by=auth.uid());
grant select on public.country_market_history to anon,authenticated;
grant insert,update on public.country_market_history to authenticated;
commit;
