-- =========================================================
-- MFDCO Country Operations v17.2 incremental
-- Requires the v15/v17.1 database baseline.
-- - Organization founders may leave; empty organizations auto-delete.
-- - Founder control transfers to the oldest remaining active member.
-- - Logged-in clients can safely backfill deterministic market history.
-- =========================================================
begin;

-- v15の初期案では country_market_history.country_id が uuid になっていましたが、
-- countries.id は text です。既存環境と新規環境の両方を text に統一します。
create table if not exists public.country_market_history (
 id bigint generated by default as identity primary key,
 country_id text not null references public.countries(id) on delete cascade,
 captured_hour timestamptz not null,
 market_date date not null,
 market_month text not null,
 market_hour text not null,
 change_pct numeric(9,4) not null default 0,
 fx_value numeric null,
 stock_value numeric null,
 world_average_pct numeric(9,4) null,
 themes jsonb not null default '{}'::jsonb,
 recorded_by uuid null references auth.users(id) on delete set null,
 created_at timestamptz not null default now(),
 unique(country_id,captured_hour)
);

alter table public.country_market_history
  drop constraint if exists country_market_history_country_id_fkey;
alter table public.country_market_history
  alter column country_id type text using country_id::text;
alter table public.country_market_history
  add constraint country_market_history_country_id_fkey
  foreign key(country_id) references public.countries(id) on delete cascade;

create index if not exists country_market_history_country_time_idx
  on public.country_market_history(country_id,captured_hour desc);

alter table public.country_market_history enable row level security;
drop policy if exists "public market history read" on public.country_market_history;
create policy "public market history read" on public.country_market_history
  for select to anon,authenticated
  using (exists(select 1 from public.countries c where c.id=country_id and c.is_public=true and c.archived_at is null));
drop policy if exists "auth market history write" on public.country_market_history;
create policy "auth market history write" on public.country_market_history
  for insert to authenticated with check(recorded_by=auth.uid());
drop policy if exists "auth market history update" on public.country_market_history;
create policy "auth market history update" on public.country_market_history
  for update to authenticated using(recorded_by=auth.uid()) with check(recorded_by=auth.uid());
grant select on public.country_market_history to anon,authenticated;
grant insert,update on public.country_market_history to authenticated;

create or replace function public.mfdco_leave_international_organization(
  p_organization_id uuid,
  p_country_id text
)
returns text
language plpgsql
security definer
set search_path=public
as $$
declare
  v_role text;
  v_remaining integer:=0;
  v_successor_country text;
  v_successor_owner uuid;
begin
  if auth.uid() is null or not public.mfdco_country_can_manage(p_country_id) then
    raise exception 'not allowed';
  end if;

  update public.international_organization_members
  set status='left'
  where organization_id=p_organization_id
    and country_id=p_country_id
    and status='active'
  returning role into v_role;

  if v_role is null then
    raise exception 'active organization membership not found';
  end if;

  select count(*) into v_remaining
  from public.international_organization_members
  where organization_id=p_organization_id
    and status='active';

  if v_remaining=0 then
    delete from public.international_organizations
    where id=p_organization_id;
    return 'deleted';
  end if;

  if v_role='founder' then
    select m.country_id,c.owner_id
    into v_successor_country,v_successor_owner
    from public.international_organization_members m
    join public.countries c on c.id=m.country_id
    where m.organization_id=p_organization_id
      and m.status='active'
    order by m.joined_at asc,m.country_id asc
    limit 1;

    if v_successor_country is not null and v_successor_owner is not null then
      update public.international_organization_members
      set role='founder'
      where organization_id=p_organization_id
        and country_id=v_successor_country;

      update public.international_organizations
      set founder_country_id=v_successor_country,
          created_by=v_successor_owner,
          updated_at=now()
      where id=p_organization_id;
    end if;
  end if;

  return 'left';
end
$$;

revoke all on function public.mfdco_leave_international_organization(uuid,text) from public;
grant execute on function public.mfdco_leave_international_organization(uuid,text) to authenticated;

create or replace function public.mfdco_backfill_market_history(p_rows jsonb)
returns integer
language plpgsql
security definer
set search_path=public
as $$
declare
  r jsonb;
  v_inserted integer:=0;
  v_rowcount integer:=0;
  v_country_id public.countries.id%type;
begin
  if auth.uid() is null then
    raise exception 'authentication required';
  end if;

  if jsonb_typeof(coalesce(p_rows,'[]'::jsonb))<>'array' then
    raise exception 'rows must be an array';
  end if;

  if jsonb_array_length(coalesce(p_rows,'[]'::jsonb))>500 then
    raise exception 'too many rows; maximum is 500 per call';
  end if;

  for r in select value from jsonb_array_elements(coalesce(p_rows,'[]'::jsonb))
  loop
    begin
      v_country_id:=r->>'country_id';

      if not exists(
        select 1 from public.countries c
        where c.id=v_country_id
          and c.is_public=true
          and c.archived_at is null
      ) then
        continue;
      end if;

      insert into public.country_market_history(
        country_id,captured_hour,market_date,market_month,market_hour,
        change_pct,fx_value,stock_value,world_average_pct,themes,recorded_by
      ) values(
        v_country_id,
        (r->>'captured_hour')::timestamptz,
        (r->>'market_date')::date,
        coalesce(r->>'market_month',''),
        coalesce(r->>'market_hour',''),
        coalesce((r->>'change_pct')::numeric,0),
        nullif(r->>'fx_value','')::numeric,
        nullif(r->>'stock_value','')::numeric,
        nullif(r->>'world_average_pct','')::numeric,
        coalesce(r->'themes','{}'::jsonb),
        auth.uid()
      )
      on conflict(country_id,captured_hour) do nothing;

      get diagnostics v_rowcount = row_count;
      v_inserted:=v_inserted+v_rowcount;
    exception when others then
      raise exception 'invalid market history row: %', sqlerrm;
    end;
  end loop;

  return v_inserted;
end
$$;

revoke all on function public.mfdco_backfill_market_history(jsonb) from public;
grant execute on function public.mfdco_backfill_market_history(jsonb) to authenticated;

commit;

-- Quick verification
select proname
from pg_proc
where proname in (
  'mfdco_leave_international_organization',
  'mfdco_backfill_market_history'
)
order by proname;
