"use strict";
document.addEventListener("DOMContentLoaded",async()=>{
 const C=MFDCOCountry,V=MFDCOCountryV6,Cloud=MFDCOCountryCloud,c=await V.load(),root=document.getElementById('arsenal-app'),role=await Cloud.role(c.id);let rows=C.arr(c.officialEquipment);const can=['owner','admin','editor'].includes(role)||!Cloud.ready();
 if(Cloud.ready()){const r=await window.supabaseClient.from('country_work_adoptions').select('*,works(id,title,image_url,status)').eq('country_id',c.id).order('created_at',{ascending:false});if(!r.error)rows=(r.data||[]).map(x=>({...x,workTitle:x.works?.title||x.work_id}))}
 const cat=x=>x.category||'未分類';
 function table(list){return `<div class="table-wrap"><table><thead><tr><th>作品 / 装備</th><th>制式名称</th><th>軍種</th><th>部隊</th><th>状態</th><th>採用日</th><th></th></tr></thead><tbody>${list.map(r=>{const i=rows.indexOf(r);return `<tr><td>${r.work_id?`<a href="work.html?id=${r.work_id}">${C.esc(r.workTitle||r.work_id)}</a>`:C.esc(r.workTitle||r.name||'')}</td><td>${C.esc(r.designation||'')}</td><td>${C.esc(r.branch_name||r.branchName||'')}</td><td>${C.esc(r.unit_name||r.unitName||'')}</td><td>${C.esc(r.status||'active')}</td><td>${C.esc(r.adopted_at||r.adoptedAt||'')}</td><td>${can?`<button class="btn danger small del-adoption" data-i="${i}" data-id="${r.id||''}">削除</button>`:''}</td></tr>`}).join('')}</tbody></table></div>`}
 function render(){const groups=Object.entries(rows.reduce((a,r)=>{(a[cat(r)]??=[]).push(r);return a},{})).sort((a,b)=>a[0].localeCompare(b[0],'ja'));root.innerHTML=`<div class="toolbar">${can?'<button id="add-adoption" class="btn">＋Work作品を正式採用</button>':''}<a class="btn ghost" href="country.html?id=${c.id}">国家資料へ</a></div>${groups.length?groups.map(([k,v])=>`<section class="card section-card arsenal-group"><div class="section-head"><div><div class="eyebrow">EQUIPMENT CATEGORY</div><h2>${C.esc(k)}</h2></div><span class="badge">${v.length} 件</span></div>${table(v)}</section>`).join(''):'<div class="empty">正式採用装備はありません。</div>'}<div id="adopt-form"></div>`;document.getElementById('add-adoption')?.addEventListener('click',showForm);document.querySelectorAll('.del-adoption').forEach(b=>b.onclick=async()=>{if(Cloud.ready()&&b.dataset.id){const x=await window.supabaseClient.from('country_work_adoptions').delete().eq('id',b.dataset.id);if(x.error)return V.toast(x.error.message,'danger');location.reload()}else{c.officialEquipment.splice(+b.dataset.i,1);await V.save(c);rows=c.officialEquipment;render()}})}
 async function showForm(){const box=document.getElementById('adopt-form');box.innerHTML=`<section class="card section-card"><h2>正式採用を追加</h2><div class="form-grid"><div class="field full"><label>MFDCO Work</label><input id="work-search" class="input" placeholder="作品名を検索"><div id="work-results"></div></div><div class="field"><label>制式名称</label><input id="designation" class="input"></div><div class="field"><label>兵器分類</label><select id="category" class="select"><option value="">未分類</option>${V.option(V.EQUIPMENT_TYPES)}</select></div><div class="field"><label>軍種</label><select id="branch" class="select"><option value="">未指定</option>${C.arr(c.military.branches).map(b=>`<option>${C.esc(b.name)}</option>`).join('')}</select></div><div class="field"><label>配備部隊</label><select id="unit" class="select"><option value="">未指定</option>${C.arr(c.military.units).map(u=>`<option>${C.esc(u.name)}</option>`).join('')}</select></div><div class="field"><label>状態</label><select id="status" class="select"><option value="active">現役</option><option value="experimental">試験採用</option><option value="reserve">予備</option><option value="retired">退役</option></select></div><div class="field"><label>採用日</label><input id="adopted" class="input" type="date"></div></div><input type="hidden" id="selected-work"><button id="save-adoption" class="btn">追加</button></section>`;let selectedTitle='';document.getElementById('work-search').oninput=async e=>{const q=e.target.value.trim();if(q.length<2||!Cloud.ready())return;const r=await window.supabaseClient.from('works').select('id,title,status').eq('status','approved').ilike('title',`%${q}%`).limit(12);document.getElementById('work-results').innerHTML=(r.data||[]).map(w=>`<button class="btn ghost small pick-work" data-id="${w.id}" data-title="${C.esc(w.title)}">${C.esc(w.title)}</button>`).join('');document.querySelectorAll('.pick-work').forEach(b=>b.onclick=()=>{document.getElementById('selected-work').value=b.dataset.id;selectedTitle=b.dataset.title;document.getElementById('work-search').value=b.dataset.title})};document.getElementById('save-adoption').onclick=async()=>{const work=document.getElementById('selected-work').value;if(!work)return V.toast('作品を選択してください','warn');const item={country_id:c.id,work_id:work,designation:document.getElementById('designation').value,category:document.getElementById('category').value,branch_name:document.getElementById('branch').value,unit_name:document.getElementById('unit').value,status:document.getElementById('status').value,adopted_at:document.getElementById('adopted').value||null,notes:''};if(Cloud.ready()){const u=await Cloud.user();item.created_by=u.id;const x=await window.supabaseClient.from('country_work_adoptions').insert(item);if(x.error)return V.toast(x.error.message,'danger');location.reload()}else{c.officialEquipment.push({...item,id:C.uid(),workTitle:selectedTitle});await V.save(c);rows=c.officialEquipment;render()}}}
 render();
});
