"use strict";
(function(){
const C=window.MFDCOCountry;
const MAP={timeline:"timeline",posts:"post",wikiPages:"wiki",statistics:"statistic",mapPoints:"map_point",systems:"system",organizations:"organization",officialEquipment:"official_equipment",cities:"city",companies:"company",territories:"territory",disputes:"dispute",borders:"border",overseasBases:"overseas_base",universities:"university",researchInstitutions:"research_institution",welfarePrograms:"welfare_program",policies:"policy",opinionPolls:"opinion_poll",protests:"protest",trustMetrics:"trust_metric",equalityMetrics:"equality_metric",policeOrganizations:"police_org",criminalOrganizations:"criminal_org",ideologies:"ideology",securityPrograms:"security_program",banks:"bank",conglomerates:"conglomerate",resourceReserves:"resource_reserve",environmentalIssues:"environment_issue",sdgGoals:"sdg_goal",ports:"port",airports:"airport",heritageSites:"heritage",socialPlatforms:"social_platform",marketDependencies:"market_dependency"};
const reverse=Object.fromEntries(Object.entries(MAP).map(([k,v])=>[v,k]));
function ready(){return !!window.supabaseClient}
async function user(){if(!ready())return null;try{return (await window.supabaseClient.auth.getUser()).data?.user||null}catch{return null}}
function coreFromCountry(c){const core=C.clone(c);for(const k of Object.keys(MAP))delete core[k];core.public=!!c.isPublic;core.schemaVersion=11;core.basic={capital:c.capital?.name||"",government:c.government?.system||""};core._index=core._index||{};const st=C.calculateStrength(c);core._index.strength=st.total;core._index.completeness=C.calculateCompleteness(c);return core}
function recordsFromCountry(c){const out=[];for(const [key,type] of Object.entries(MAP)){C.arr(c[key]).forEach((item,i)=>out.push({id:item.id||C.uid(),record_type:type,title:item.title||item.name||item.label||`${type} ${i+1}`,sort_order:i,payload:{...item,id:item.id||undefined}}))}return out}
function merge(core,records){const c=C.clone(core||{});c.isPublic=!!(core?.isPublic??core?.public);for(const k of Object.keys(MAP))c[k]=[];for(const r of records||[]){const key=reverse[r.record_type];if(key)c[key].push({...r.payload,id:r.id,title:r.payload?.title||r.title})}return C.migrate(c)}
async function saveCountry(c){if(!ready())return C.save(c);const u=await user();if(!u)throw new Error("クラウド保存にはログインが必要です。ローカル保存のみ行いました。");const core=coreFromCountry(c),records=recordsFromCountry(c),snapshot=C.clone(c);const {data,error}=await window.supabaseClient.rpc("mfdco_save_country",{p_core:core,p_records:records,p_snapshot:snapshot});if(error)throw error;c.id=data||c.id;C.save(c);return c}
async function loadCountry(id){if(!ready())return C.get(id);try{const {data,error}=await window.supabaseClient.from("countries").select("id,core_data,is_public").eq("id",id).maybeSingle();if(error)throw error;if(!data)return C.get(id);const rr=await window.supabaseClient.from("country_records").select("id,record_type,title,sort_order,payload").eq("country_id",id).order("record_type").order("sort_order");if(rr.error)throw rr.error;const c=merge({...data.core_data,id:data.id,isPublic:data.is_public},rr.data||[]);C.save(c);return c}catch(e){console.warn("CLOUD LOAD fallback",e);return C.get(id)}}
async function listCountries({mine=false,publicOnly=false}={}){if(!ready())return C.load();let q=window.supabaseClient.from("countries").select("id,name,short_name,english_name,code,summary,is_public,tags,updated_at,population,area_km2,capital,government,strength_score,completeness_score,flag_key,cover_key,owner_id").is("archived_at",null);const u=await user();if(mine&&u)q=q.eq("owner_id",u.id);if(publicOnly)q=q.eq("is_public",true);const {data,error}=await q.order("updated_at",{ascending:false});if(error){console.warn(error);return C.load()}return (data||[]).map(x=>({id:x.id,name:x.name,shortName:x.short_name,englishName:x.english_name,code:x.code,summary:x.summary,isPublic:x.is_public,tags:x.tags||[],updatedAt:x.updated_at,population:x.population,territory:{area:x.area_km2},capital:{name:x.capital},government:{system:x.government},media:{flagKey:x.flag_key,coverKey:x.cover_key},_index:{strength:x.strength_score,completeness:x.completeness_score},ownerId:x.owner_id}))}
async function role(id){if(!ready())return "owner";const {data,error}=await window.supabaseClient.rpc("mfdco_country_role",{p_country_id:id});if(error)return null;return data}
async function uploadMedia(country,file,slot="file"){if(!ready())return C.storeMedia(file,slot);const u=await user();if(!u)throw new Error("アップロードにはログインが必要です");if(file.size>25*1024*1024)throw new Error("1ファイル25MiBまでです");const ext=(file.name.split(".").pop()||"bin").replace(/[^a-z0-9]/gi,"");const path=`${country.id}/${u.id}/${Date.now()}_${C.uid()}.${ext}`;const up=await window.supabaseClient.storage.from("country-media").upload(path,file,{contentType:file.type,upsert:false});if(up.error)throw up.error;const ins=await window.supabaseClient.from("country_media").insert({country_id:country.id,uploader_id:u.id,storage_path:path,slot,kind:file.type.startsWith("audio/")?"audio":file.type.startsWith("image/")?"image":"file",mime_type:file.type,original_name:file.name,size_bytes:file.size}).select("id").single();if(ins.error){await window.supabaseClient.storage.from("country-media").remove([path]);throw ins.error}return `storage:${path}`}
async function resolveMedia(key,expires=3600){if(!key)return "";if(!key.startsWith("storage:"))return C.mediaUrl(key);if(!ready())return "";const path=key.slice(8);const {data,error}=await window.supabaseClient.storage.from("country-media").createSignedUrl(path,expires);return error?"":data?.signedUrl||""}
async function notifications(){if(!ready())return [];const {data,error}=await window.supabaseClient.from("country_notifications").select("*").order("created_at",{ascending:false}).limit(100);return error?[]:data||[]}
async function markNotification(id){if(!ready())return;await window.supabaseClient.from("country_notifications").update({read_at:new Date().toISOString()}).eq("id",id)}
async function relations(countryId){if(!ready())return C.get(countryId).relations||[];const {data,error}=await window.supabaseClient.from("country_relations").select("*").or(`country_a_id.eq.${countryId},country_b_id.eq.${countryId}`).order("started_at",{ascending:false});return error?[]:data||[]}
async function proposals(countryId){if(!ready())return [];const {data,error}=await window.supabaseClient.from("country_proposals").select("*").or(`source_country_id.eq.${countryId},target_country_id.eq.${countryId}`).order("created_at",{ascending:false});return error?[]:data||[]}
async function createProposal(obj){if(!ready())throw new Error("外交提案の本番処理にはSupabase接続が必要です");const u=await user();if(!u)throw new Error("ログインが必要です");const {data,error}=await window.supabaseClient.from("country_proposals").insert({...obj,proposed_by:u.id}).select().single();if(error)throw error;return data}
async function respondProposal(id,status){const {data,error}=await window.supabaseClient.rpc("mfdco_respond_country_proposal",{p_proposal_id:id,p_status:status});if(error)throw error;return data}


async function editableCountryChoices(){if(!ready())return C.load().map(x=>({id:x.id,name:x.name}));const u=await user();if(!u)return [];const owned=await window.supabaseClient.from("countries").select("id,name").eq("owner_id",u.id).is("archived_at",null);const mem=await window.supabaseClient.from("country_members").select("country_id,role").eq("user_id",u.id).in("role",["owner","admin","editor"]);const ids=[...(owned.data||[]).map(x=>x.id),...(mem.data||[]).map(x=>x.country_id)];if(!ids.length)return [];const q=await window.supabaseClient.from("countries").select("id,name").in("id",[...new Set(ids)]).is("archived_at",null).order("name");return q.error?(owned.data||[]):q.data||[]}
async function usageRequests(countryId){if(!ready())return [];const {data,error}=await window.supabaseClient.from("country_usage_requests").select("*").eq("country_id",countryId).order("created_at",{ascending:false});return error?[]:data||[]}
async function createUsageRequest(obj){if(!ready())throw new Error("利用申請にはSupabase接続が必要です");const u=await user();if(!u)throw new Error("ログインが必要です");const {data,error}=await window.supabaseClient.from("country_usage_requests").insert({...obj,requester_id:u.id}).select().single();if(error)throw error;return data}
async function respondUsageRequest(id,status){if(!ready())throw new Error("Supabase接続が必要です");const {data,error}=await window.supabaseClient.rpc("mfdco_respond_country_usage_request",{p_request_id:id,p_status:status});if(error)throw error;return data}
async function versions(countryId){if(!ready())return [];const {data,error}=await window.supabaseClient.from("country_versions").select("id,created_at,created_by").eq("country_id",countryId).order("created_at",{ascending:false}).limit(30);return error?[]:data||[]}
async function marketSnapshots(){
 if(!ready())return C.load().filter(x=>x.isPublic);
 try{
  const rpc=await window.supabaseClient.rpc("mfdco_public_market_snapshots");
  if(!rpc.error&&Array.isArray(rpc.data))return rpc.data.map(x=>C.migrate(x.payload||{id:x.id,name:x.name,isPublic:true}));
 }catch(e){console.warn("MARKET RPC fallback",e)}
 try{
  const {data,error}=await window.supabaseClient.from("countries").select("id,name,short_name,is_public,core_data").eq("is_public",true).is("archived_at",null).limit(250);if(error)throw error;
  const rows=(data||[]).map(x=>C.migrate({...x.core_data,id:x.id,name:x.name,shortName:x.short_name,isPublic:x.is_public})),ids=rows.map(x=>x.id);
  if(ids.length){const rr=await window.supabaseClient.from("country_records").select("country_id,record_type,payload,id").in("country_id",ids).in("record_type",["company","market_dependency","port","resource_reserve"]);if(!rr.error){const by=new Map(rows.map(x=>[x.id,x]));for(const r of rr.data||[]){const c=by.get(r.country_id);if(!c)continue;const item={...r.payload,id:r.id};if(r.record_type==="company")c.companies.push(item);if(r.record_type==="market_dependency")c.marketDependencies.push(item);if(r.record_type==="port")c.ports.push(item);if(r.record_type==="resource_reserve")c.resourceReserves.push(item)}}}
  return rows
 }catch(e){console.warn("MARKET SNAPSHOTS fallback",e);return C.load().filter(x=>x.isPublic)}
}
window.MFDCOCountryCloud={ready,user,coreFromCountry,recordsFromCountry,merge,saveCountry,loadCountry,listCountries,role,uploadMedia,resolveMedia,notifications,markNotification,relations,proposals,createProposal,respondProposal,versions,marketSnapshots,editableCountryChoices,usageRequests,createUsageRequest,respondUsageRequest};
})();
