export function validateAviation(p){
 p.hangars??=[];if(!Array.isArray(p.hangars)||p.hangars.length>80)throw new Error('航空在庫は80拠点までです。');const hosts=new Set(),flights=new Set();
 for(const h of p.hangars){const host=p.units.find(u=>u.id===h.hostId);if(!host||p.defaults.find(t=>t.id===host.type)?.domain==='air'||hosts.has(h.hostId)||!Array.isArray(h.stock)||h.stock.length>60||!Array.isArray(h.sorties)||h.sorties.length>200)throw new Error('航空拠点・搭載予約が不正です。');hosts.add(h.hostId);const types=new Set(),reused=new Set();
  for(const item of h.stock){if(types.has(item.type)||item.type==='missile'||p.defaults.find(t=>t.id===item.type)?.domain!=='air'||!Number.isInteger(item.count)||item.count<0||item.count>1000)throw new Error('搭載機は兵科ごと0〜1000機です。');types.add(item.type);}
  for(const r of h.sorties){r.reuseFrom??='';const u=p.units.find(u=>u.id===r.unitId);if(!u||flights.has(r.unitId)||u.id===host.id||u.launchFrom!==h.hostId||u.type!==r.type||u.personnel!==r.count||u.start!==r.at||u.team!==host.team||!types.has(r.type)||!Number.isInteger(r.at)||r.at<host.start||r.at>10000||!Number.isInteger(r.count)||r.count<1||r.count>100||typeof r.reuseFrom!=='string')throw new Error('発艦予約の部隊・機数・時刻を確認してください。');
   u.returnAt??=null;if(u.returnAt!==null&&(!Number.isInteger(u.returnAt)||u.returnAt<=u.start||u.returnAt>10000))throw new Error('帰投開始frameは発艦より後にしてください。');
   if(r.reuseFrom){const prior=h.sorties.find(v=>v.unitId===r.reuseFrom),parent=p.units.find(v=>v.id===r.reuseFrom);if(!prior||!parent||prior.type!==r.type||prior.at>=r.at||r.count>prior.count||parent.returnAt==null||parent.returnAt>=r.at||reused.has(r.reuseFrom))throw new Error('再出撃は帰投する同兵科の隊から1回だけ予約できます。');reused.add(r.reuseFrom);}flights.add(r.unitId);
  }
  for(const item of h.stock)if(h.sorties.filter(r=>r.type===item.type&&!r.reuseFrom).reduce((n,r)=>n+r.count,0)>item.count)throw new Error('発艦予約が保有機数を超えています。');
 }
 for(const u of p.units){u.launchFrom??='';u.returnAt??=null;if(typeof u.launchFrom!=='string'||u.launchFrom&&!flights.has(u.id)||!u.launchFrom&&u.returnAt!==null)throw new Error('発艦元・帰投設定が不正です。');}return p;
}
export function hangarCounts(h,type,frame,states=[]){const rs=h.sorties.filter(r=>r.type===type),total=h.stock.find(s=>s.type===type)?.count||0,reserved=rs.filter(r=>!r.reuseFrom).reduce((n,r)=>n+r.count,0),departed=rs.filter(r=>r.at<frame).reduce((n,r)=>n+r.count,0),recovered=rs.filter(r=>!rs.some(v=>v.reuseFrom===r.unitId)).reduce((n,r)=>{const s=states.find(s=>s.id===r.unitId);return n+(s?.recovered?s.recoveredCount||0:0);},0);return{total,reserved,available:total-reserved,departed,pending:rs.filter(r=>r.at>=frame).reduce((n,r)=>n+r.count,0),recovered};}
export function cancelSortie(p,hostId,unitId){const h=p.hangars.find(h=>h.hostId===hostId);if(!h?.sorties.some(r=>r.unitId===unitId))throw new Error('予約がありません。');if(h.sorties.some(r=>r.reuseFrom===unitId))throw new Error('先に、この隊からの再出撃予約を取り消してください。');if(p.units.some(u=>u.id!==unitId&&(u.target===unitId||u.hq===unitId||u.orders.some(o=>o.target===unitId)))||p.radars.some(r=>r.unitId===unitId)||p.groups.some(g=>g.members.includes(unitId))||p.vls.some(r=>r.unitId===unitId||r.cells.some(c=>c.missileId===unitId)))throw new Error('この航空部隊を参照する命令・レーダー・グループがあります。先に解除してください。');h.sorties=h.sorties.filter(r=>r.unitId!==unitId);p.units=p.units.filter(u=>u.id!==unitId);p.communications.forEach(m=>{if(m.unitId===unitId)m.unitId='';});}
