import {ADDED_FACILITIES} from './catalog-additions.mjs';
import {powerFactor} from './logistics.mjs';
import {facilityState,validateFacilityState} from './facility-state.mjs';
export const FACILITY_LINE_TYPES=['road','railway','trench','road_bridge','rail_bridge','pier','waterway','seaplane_ramp','runway_strip'];
export const FACILITY_TYPES={...ADDED_FACILITIES,runway_strip:'滑走路（線）',road_bridge:'道路橋（線）',rail_bridge:'鉄道橋（線）',pier:'桟橋・岸壁（線）',waterway:'河川・運河（線）',seaplane_ramp:'水上機斜路（線）',mooring:'係留杭',cable_station:'海底電信局',mess_hall:'食堂・炊事施設',supply_depot:'総合補給所',fuel_depot:'燃料集積所',food_depot:'食料集積所',distribution_center:'物資配給所',generator:'発電機施設',field_kitchen_site:'野外炊事場',refugee_camp:'難民キャンプ',evacuation_center:'避難所',water_point:'給水所',civil_hospital:'総合病院',clinic:'診療所',firebreak:'防火空地',embassy:'大使館',radio_station:'放送局',telephone_exchange:'電話交換局',data_center:'情報処理施設',border_post:'国境検問所',observation_post:'監視哨',searchlight_site:'探照灯施設',hardened_shelter:'掩体壕',tank_obstacle:'対戦車障害物',military_police:'憲兵詰所',bakery:'製パン所',cold_store:'冷蔵倉庫',ammunition_depot:'弾薬庫',command_post:'指揮所',radar_station:'レーダーサイト',aa_emplacement:'対空陣地',coastal_battery:'沿岸砲台',drydock:'乾ドック',shipyard:'造船所',helipad:'ヘリポート',customs:'税関',grain_store:'穀物倉庫',market:'市場',hotel:'宿泊施設',university:'大学',library:'図書館',stadium:'競技場',prison:'収容施設',post_office:'郵便局',bus_terminal:'バスターミナル',sewage:'下水処理場',greenhouse:'温室',house:'住宅',apartment:'集合住宅',shop:'商店',school:'学校',fire_station:'消防署',police:'警察署',government:'役所',barracks:'兵舎',hangar:'格納庫',runway:'滑走路',fuel_tank:'燃料タンク',church:'教会',workshop:'整備工場',water_tower:'給水塔',reservoir:'貯水池',waterworks:'浄水場',substation:'変電所',solar:'太陽光発電',windfarm:'風力発電',refinery:'製油所',silo:'穀物サイロ',quarry:'採石場',observatory:'観測所',shelter:'避難施設',depot:'車両基地',container_terminal:'コンテナ埠頭',trench:'塹壕',minefield:'地雷原',bunker:'陣地',hospital:'野戦病院',airfield:'飛行場',road:'道路',railway:'鉄道',fort:'要塞',city:'都市',army_base:'陸軍基地',naval_base:'海軍基地',objective:'重要目標',warehouse:'倉庫',factory:'工場',power:'発電所',tower:'通信施設',checkpoint:'検問所',port:'港湾',station:'鉄道駅',bridge:'橋梁',dam:'ダム'};
export function kmPoint(p,v){return{x:v.x*p.widthKm/1000,y:v.y*p.heightKm/1000};}
export function segmentDistance(a,b,c){const dx=b.x-a.x,dy=b.y-a.y,t=dx*dx+dy*dy?Math.max(0,Math.min(1,((c.x-a.x)*dx+(c.y-a.y)*dy)/(dx*dx+dy*dy))):0;return Math.hypot(c.x-a.x-dx*t,c.y-a.y-dy*t);}
export function withinFacility(p,f,s){const v=kmPoint(p,s),pts=f.points.map(v=>kmPoint(p,v)),r=f.radiusKm*(p.facilityScale??1);if((f.type==='city'||f.footprint==='rectangle')&&f.points.length===2)return s.x>=Math.min(f.points[0].x,f.points[1].x)&&s.x<=Math.max(f.points[0].x,f.points[1].x)&&s.y>=Math.min(f.points[0].y,f.points[1].y)&&s.y<=Math.max(f.points[0].y,f.points[1].y);if(!FACILITY_LINE_TYPES.includes(f.type))return Math.hypot(v.x-pts[0].x,v.y-pts[0].y)<=r;return pts.slice(1).some((b,i)=>segmentDistance(pts[i],b,v)<=r);}
export function coverBonus(p,u,s){if(p.facilityEffects===false||p.defaults.find(t=>t.id===u.type)?.domain!=='land')return 0;return Math.max(0,...(p.facilities||[]).filter(f=>f.type!=='minefield'&&facilityState(p,f,p.simSeconds??0).operational&&(f.team==='neutral'||f.team===u.team)&&withinFacility(p,f,s)).map(f=>f.defense));}
export function mineHits(p,u,from,to,previous=[]){if(p.facilityEffects===false||p.defaults.find(t=>t.id===u.type)?.domain!=='land')return[];return(p.facilities||[]).filter(f=>f.type==='minefield'&&facilityState(p,f,p.simSeconds??0).operational&&!previous.includes(f.id)&&(f.team==='neutral'||f.team!==u.team)&&segmentDistance(kmPoint(p,from),kmPoint(p,to),kmPoint(p,f.points[0]))<=f.radiusKm*(p.facilityScale??1));}
export function validateFacilities(p){p.facilities??=[];p.facilityScale??=1;p.facilityEffects??=true;if(!Array.isArray(p.facilities)||p.facilities.length>1000||!Number.isFinite(p.facilityScale)||p.facilityScale<.1||p.facilityScale>10||typeof p.facilityEffects!=='boolean')throw new Error('設備設定が不正です。');const ids=new Set(),num=(v,a,b)=>typeof v==='number'&&Number.isFinite(v)&&v>=a&&v<=b;for(const f of p.facilities){if(!f||typeof f.id!=='string'||!f.id||f.id.length>40||ids.has(f.id)||!Object.hasOwn(FACILITY_TYPES,f.type)||!['blue','red','neutral'].includes(f.team)||!num(f.radiusKm,.01,20)||!num(f.defense,0,10000)||!num(f.damage,0,100000)||!Array.isArray(f.points)||f.points.length<(FACILITY_LINE_TYPES.includes(f.type)?2:1)||f.points.length>100||f.points.some(v=>!v||!num(v.x,0,1000)||!num(v.y,0,1000)))throw new Error('設備の種類・座標・数値が不正です。');f.footprint??='point';f.buildingHeight??=6;if(!['point','rectangle'].includes(f.footprint)||f.footprint==='rectangle'&&(f.points.length!==2||FACILITY_LINE_TYPES.includes(f.type))||!num(f.buildingHeight,0,1000))throw Error('建物の形状・高さが不正です。');f.blockKm??=.2;if(!num(f.blockKm,.01,5))throw new Error('都市の区画間隔は0.01〜5kmです。');validateFacilityState(f);ids.add(f.id);}return p;}

export function facilitySupportRate(p,u,s){if(p.facilityEffects===false||u.type==='missile')return 0;const domain=p.defaults.find(t=>t.id===u.type)?.domain;return Math.max(0,...p.facilities.filter(f=>({field_surgery:'land',hospital:'land',civil_hospital:'land',clinic:'land',army_base:'land',naval_base:'sea',airfield:'air'})[f.type]===domain&&f.team===u.team&&f.supportRate>0&&facilityState(p,f,p.simSeconds??0).operational&&withinFacility(p,f,s)).map(f=>f.supportRate*powerFactor(p,f,p.simSeconds??0)));}

// Preserve shape and events; reject the entire translation if any vertex leaves the map.
export function translateFacility(p,id,eastKm,southKm,copyId=''){
 const f=p.facilities.find(f=>f.id===id);if(!f)throw new Error('設備が見つかりません。');
 if(!Number.isFinite(eastKm)||!Number.isFinite(southKm))throw new Error('移動距離を数値で指定してください。');
 if(copyId&&(p.facilities.length>=1000||p.facilities.some(f=>f.id===copyId)))throw new Error('設備の上限またはIDを確認してください。');
 const points=f.points.map(v=>({x:v.x+eastKm/p.widthKm*1000,y:v.y+southKm/p.heightKm*1000}));
 if(points.some(v=>v.x<0||v.x>1000||v.y<0||v.y>1000))throw new Error('移動先が地図の範囲外です。距離を小さくしてください。');
 if(copyId){const next={...JSON.parse(JSON.stringify(f)),id:copyId,name:((f.name||FACILITY_TYPES[f.type])+' 複製').slice(0,60),points};p.facilities.push(next);return next.id;}
 f.points=points;return id;
}
