export function transformFacilities(p,ids,{east=0,south=0,rotate=0,copy=false,team=null,remove=false}={}){const selected=p.facilities.filter(f=>ids.includes(f.id));if(!selected.length)throw Error('設備を選択してください。');if(![east,south].every(Number.isFinite)||![0,90,180,270].includes(rotate))throw Error('移動距離または回転角が不正です。');if(team!==null&&!['blue','red','neutral'].includes(team))throw Error('陣営が不正です。');if(remove){p.facilities=p.facilities.filter(f=>!ids.includes(f.id));return [];}
 if(copy&&p.facilities.length+selected.length>1000)throw Error('設備は1000件までです。');const all=selected.flatMap(f=>f.points),cx=(Math.min(...all.map(v=>v.x))+Math.max(...all.map(v=>v.x)))/2*p.widthKm/1000,cy=(Math.min(...all.map(v=>v.y))+Math.max(...all.map(v=>v.y)))/2*p.heightKm/1000,angle=rotate*Math.PI/180;let seq=1;const used=new Set(p.facilities.map(f=>f.id));const changed=selected.map(f=>{const n=JSON.parse(JSON.stringify(f));n.points=f.points.map(v=>{const x=v.x*p.widthKm/1000-cx,y=v.y*p.heightKm/1000-cy;return{x:(cx+x*Math.cos(angle)-y*Math.sin(angle)+east)/p.widthKm*1000,y:(cy+x*Math.sin(angle)+y*Math.cos(angle)+south)/p.heightKm*1000};});if(n.points.some(v=>v.x<-.000001||v.x>1000.000001||v.y<-.000001||v.y>1000.000001))throw Error('移動・回転後に地図の外へ出ます。');n.points.forEach(v=>{v.x=Math.max(0,Math.min(1000,v.x));v.y=Math.max(0,Math.min(1000,v.y));});if(team!==null)n.team=team;if(copy){while(used.has('batch-'+seq))seq++;n.id='batch-'+seq++;used.add(n.id);n.name=(n.name+' 複製').slice(0,60);}return n;});if(copy)p.facilities.push(...changed);else for(const n of changed)p.facilities[p.facilities.findIndex(f=>f.id===n.id)]=n;return changed.map(f=>f.id);}

const center=f=>({x:f.points.reduce((s,v)=>s+v.x,0)/f.points.length,y:f.points.reduce((s,v)=>s+v.y,0)/f.points.length});
export function alignFacilities(p,ids,mode){const selected=p.facilities.filter(f=>ids.includes(f.id));if(selected.length<2)throw Error('設備を2件以上選択してください。');if(!['x','y','space-x','space-y'].includes(mode))throw Error('整列方法が不正です。');const axis=mode.endsWith('x')?'x':'y',sorted=[...selected].sort((a,b)=>center(a)[axis]-center(b)[axis]||a.id.localeCompare(b.id)),lo=center(sorted[0])[axis],hi=center(sorted.at(-1))[axis],updates=sorted.map((f,i)=>{const delta=(mode.startsWith('space')?lo+(hi-lo)*i/(sorted.length-1):(lo+hi)/2)-center(f)[axis];const points=f.points.map(v=>({...v,[axis]:v[axis]+delta}));if(points.some(v=>v.x<0||v.y<0||v.x>1000||v.y>1000))throw Error('整列後に地図の外へ出ます。');return{f,points};});for(const {f,points} of updates)f.points=points;}
export function repeatAlongLine(p,sourceId,lineId,spacingKm,offsetKm=0){
 const source=p.facilities.find(f=>f.id===sourceId),line=p.facilities.find(f=>f.id===lineId);if(!source||!line||source===line||line.points.length<2||!Number.isFinite(spacingKm)||spacingKm<.01||!Number.isFinite(offsetKm))throw Error('複製元・線・間隔を確認してください。');
 const pts=line.points.map(v=>({x:v.x*p.widthKm/1000,y:v.y*p.heightKm/1000})),segments=pts.slice(1).map((b,i)=>({a:pts[i],b,length:Math.hypot(b.x-pts[i].x,b.y-pts[i].y)})),total=segments.reduce((s,v)=>s+v.length,0),count=Math.floor(total/spacingKm)+1;if(count>200||p.facilities.length+count>1000)throw Error('一度の連続配置は200件、設備全体は1000件までです。間隔を広げてください。');
 const origin=center(source),used=new Set(p.facilities.map(f=>f.id)),added=[];let seq=1;
 for(let i=0;i<count;i++){let remaining=i*spacingKm,seg=segments.at(-1);for(const s of segments){seg=s;if(remaining<=s.length)break;remaining-=s.length;}if(!seg.length)continue;const t=remaining/seg.length,dx=seg.b.x-seg.a.x,dy=seg.b.y-seg.a.y,x=(seg.a.x+dx*t-dy/seg.length*offsetKm)/p.widthKm*1000,y=(seg.a.y+dy*t+dx/seg.length*offsetKm)/p.heightKm*1000;const f=structuredClone(source);f.points=f.points.map(v=>({x:v.x+x-origin.x,y:v.y+y-origin.y}));if(f.points.some(v=>v.x<0||v.x>1000||v.y<0||v.y>1000))throw Error('連続配置が地図の外へ出ます。線か横ずれを調整してください。');while(used.has('repeat-'+seq))seq++;f.id='repeat-'+seq++;used.add(f.id);f.name=((f.name||'設備')+' '+String(i+1).padStart(2,'0')).slice(0,60);delete f.history;added.push(f);}
 p.facilities.push(...added);return added.map(f=>f.id);
}
export function facilitiesInPolygon(p,polygon){if(polygon.length<3)return[];const inside=pt=>{let hit=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i],b=polygon[j];if((a.y>pt.y)!==(b.y>pt.y)&&pt.x<(b.x-a.x)*(pt.y-a.y)/(b.y-a.y)+a.x)hit=!hit;}return hit;};return p.facilities.filter(f=>inside(center(f))).map(f=>f.id);}
