import {unit,validate,TYPES} from './engine.mjs';
export const FORMATION_KEY='mfdco-formations-v1',FAVORITES_KEY='mfdco-unit-choices-v1';
export const FORMATION_FIELDS=['speed','hp','attack','range','defense','personnel','displayScale','detectionRange','retreatPercent','repairRate','personality','targetDomains'];
export function checkFormation(raw){
 if(raw?.format!=='mfdco-formation'||raw.version!==1||typeof raw.name!=='string'||!raw.name.trim()||raw.name.length>60||!Array.isArray(raw.members)||!raw.members.length||raw.members.length>80)throw Error('編成は名前60文字以内、1〜80部隊です。');
 const r={format:raw.format,version:1,name:raw.name,members:raw.members.map(m=>{if(!m||!TYPES.some(t=>t.id===m.type)||typeof m.name!=='string'||m.name.length>60||![m.dx,m.dy].every(v=>Number.isFinite(v)&&Math.abs(v)<=20000)||!m.settings||typeof m.settings!=='object'||Array.isArray(m.settings))throw Error('編成の兵科・名前・相対座標を確認してください。');return{type:m.type,name:m.name,dx:m.dx,dy:m.dy,settings:Object.fromEntries(FORMATION_FIELDS.filter(k=>Object.hasOwn(m.settings,k)).map(k=>[k,structuredClone(m.settings[k])]))};})};return r;
}
export function captureFormation(p,ids,name){const members=ids.map(id=>p.units.find(u=>u.id===id)).filter(Boolean);if(!members.length)throw Error('保存するグループを選択してください。');const x=members.reduce((s,u)=>s+u.x,0)/members.length,y=members.reduce((s,u)=>s+u.y,0)/members.length;return checkFormation({format:'mfdco-formation',version:1,name,members:members.map(u=>({type:u.type,name:u.name,dx:(u.x-x)*p.widthKm/1000,dy:(u.y-y)*p.heightKm/1000,settings:Object.fromEntries(FORMATION_FIELDS.filter(k=>u[k]!==undefined).map(k=>[k,structuredClone(u[k])]))}))});}
export function placeFormation(p,raw,{x=500,y=500,team='blue',scale=1,at=0}={}){
 const r=checkFormation(raw);if(!['blue','red','neutral'].includes(team)||!Number.isFinite(scale)||scale<.1||scale>10||![x,y].every(v=>Number.isFinite(v)&&v>=0&&v<=1000)||!Number.isInteger(at)||at<0||at>10000)throw Error('陣営・位置・間隔倍率を確認してください。');
 if(p.units.length+r.members.length>200||p.groups.length>=50)throw Error('部隊200件・グループ50件の上限を超えます。');
 const next=structuredClone(p),ids=[];for(const m of r.members){const px=x+m.dx*scale*1000/p.widthKm,py=y+m.dy*scale*1000/p.heightKm;if(px<0||px>1000||py<0||py>1000)throw Error('編成が地図外にはみ出します。間隔倍率を下げてください。');let id;do{id='u'+next.nextId++;}while(next.units.some(u=>u.id===id));const u=Object.assign(unit(id,m.type,px,py,team,next.defaults),m.settings,{name:m.name,start:at,hiddenUntilStart:at>0,action:'wait'});next.units.push(u);ids.push(id);}
 let n=1;while(next.groups.some(g=>g.id==='formation-'+n))n++;const group={id:'formation-'+n,name:r.name,members:ids};next.groups.push(group);next.duration=Math.max(next.duration,at);return {project:validate(next),groupId:group.id};
}
const preset=(name,types,spacing)=>checkFormation({format:'mfdco-formation',version:1,name,members:types.map((type,i)=>({type,name:({destroyer:'DD',frigate:'FF',cargo_ship:'AK',supply_ship:'AO'})[type]?({destroyer:'DD',frigate:'FF',cargo_ship:'AK',supply_ship:'AO'})[type]+'-'+String(i+1).padStart(2,'0')+'['+TYPES.find(t=>t.id===type).name+']':TYPES.find(t=>t.id===type).name+' '+String(i+1).padStart(2,'0'),dx:(i%2-.5)*spacing,dy:(Math.floor(i/2)-(Math.ceil(types.length/2)-1)/2)*spacing,settings:{}}))});
export const BUILTIN_FORMATIONS=[preset('装甲小隊',['armor','armor','ifv','ifv'],.15),preset('補給縦隊',['armored_car','command_vehicle','supply_truck','fuel_truck','ammo_truck','mobile_workshop'],.12),preset('護衛艦隊',['destroyer','destroyer','frigate','frigate','cargo_ship','supply_ship'],2),preset('輸送航空隊',['fighter','fighter','transport_aircraft','transport_aircraft'],1)];
export function readFormationList(storage){const raw=JSON.parse(storage.getItem(FORMATION_KEY)||'[]');if(!Array.isArray(raw)||raw.length>20)throw Error('保存編成の一覧が不正です。');return raw.map(checkFormation);}
export function saveFormationList(storage,list){if(list.length>20)throw Error('保存編成は20件までです。');storage.setItem(FORMATION_KEY,JSON.stringify(list.map(checkFormation)));}
export function readChoices(storage){try{const r=JSON.parse(storage.getItem(FAVORITES_KEY)||'{}'),known=a=>Array.isArray(a)?[...new Set(a.filter(id=>TYPES.some(t=>t.id===id)))]:[];return{favorites:known(r.favorites),recent:known(r.recent).slice(0,16)};}catch{return{favorites:[],recent:[]};}}
