import {fresh,unit,validate} from './engine.mjs';
import {loadBattlefield} from './map-catalog.mjs';
import {loadHistoricPack,applyHistoricPack} from './historic-layouts.mjs';
// Reference chronology and illustrative tracks are intentionally separate.
export const MIDWAY_CHRONOLOGY={id:'midway-morning-1942',version:1,date:'1942-06-04',timezone:'Midway Zone +12 / 西経日付（出典表記）',source:'https://www.ibiblio.org/hyperwar/USMC/I/USMC-I-V-4.html',sourceTitle:'USMC公式戦史 Vol.I Part V Chapter 4',events:[{at:0,text:'05:55頃 レーダーが接近する航空機群を捉える',channel:'alert'},{at:21,text:'06:16頃 島外で迎撃機と接近部隊が接触',channel:'report'},{at:35,text:'06:30頃 島への空襲が始まる',channel:'alert'},{at:65,text:'07:00過ぎ 空襲終了（本シーンでは07:00を区切りとする）',channel:'report'}]};
export async function midwayMorningScene(){const p=fresh(true);Object.assign(p,await loadBattlefield('midway'));applyHistoricPack(p,await loadHistoricPack('midway1942'));p.title='ミッドウェー朝・史実時刻参考 / 概略演出';p.calendar='西暦';p.date=MIDWAY_CHRONOLOGY.date;p.time='05:55';p.secondsPerFrame=60;p.duration=70;p.combatEnabled=false;p.units=[];p.radars=[];p.historyScene={...MIDWAY_CHRONOLOGY,tracks:'illustrative',note:'時刻の節目は戦史参考。経路・速度・機数・部隊配置・損害は史実の再現ではない。画面内の1駒は演出用の象徴。'};
const eastern=p.labels.find(l=>l.id.endsWith('-eastern'))||{x:700,y:600};
const aircraft=unit('hist-air','bomber',120,100,'red');Object.assign(aircraft,{name:'AIR-01[空襲の概略演出]',start:34,hiddenUntilStart:true,personnel:1,hp:100,attack:0,speed:240,displayScale:.5,points:[{x:eastern.x,y:eastern.y,wait:0},{x:950,y:100,wait:0}]});
const defender=unit('hist-base','hq',eastern.x,eastern.y,'blue');Object.assign(defender,{name:'BASE-01[基地・演出用]',personnel:1,attack:0,displayScale:.5,points:[]});p.units=[aircraft,defender];p.nextId=3;p.communications=MIDWAY_CHRONOLOGY.events.map((e,i)=>({...e,id:'hist-log-'+i,unitId:'',text:e.text+'（戦史参考）'}));p.briefing={title:'ミッドウェー・朝の時刻参考',organization:'歴史参考テンプレート',objective:'探知から空襲終了までの節目を、地図・通信・作戦概要で確認する。',situation:'1942年6月4日 05:55〜07:05。史料の時刻表記を使用。',notes:'経路・速度・機数・損害は概略演出。史実の航跡ではありません。出典：USMC公式戦史 Vol.I Part V Ch.4（HyperWar転記）。'};p.cuts=[{name:'探知',from:0,to:20,screen:'cic',mode:'radar',unitId:defender.id},{name:'空襲の概略演出',from:34,to:40,screen:'tactical',mode:'map',unitId:aircraft.id},{name:'通信経過',from:0,to:70,screen:'comms',mode:'map',unitId:''}];return validate(p);}
