// Named districts from the cited historical reference; centers are approximate modern map anchors.
export const HISTORIC_LAYOUTS={midway1942:'ミッドウェー1942・飛行場と基地',pearl1941:'真珠湾1941・基地と係留施設',normandy1944:'ノルマンディー1944・橋頭堡と集落',berlin1945:'ベルリン1945・地区名配置参考'};
export function applyHistoricLayout(p,id){if(id!=='berlin1945'||p.mapSource?.id!=='berlin')throw Error('先に地域参考図「ベルリン」を読み込んでください。');const names=[['ミッテ',13.405,52.52],['ヴェディング',13.36,52.55],['ティーアガルテン',13.35,52.515],['シャルロッテンブルク',13.30,52.515],['ヴィルマースドルフ',13.30,52.48],['シュパンダウ',13.20,52.535],['ライニッケンドルフ',13.33,52.59],['パンコウ',13.41,52.58],['ヴァイセンゼー',13.465,52.56],['プレンツラウアー・ベルク',13.425,52.535],['フリードリヒスハイン',13.46,52.515],['リヒテンベルク',13.515,52.52],['クロイツベルク',13.405,52.495],['シェーネベルク',13.35,52.485],['シュテーグリッツ',13.32,52.455],['ツェーレンドルフ',13.245,52.445],['テンペルホーフ',13.405,52.46],['ノイケルン',13.445,52.465],['トレプトウ',13.50,52.465],['ケーペニック',13.60,52.445]];const b=p.mapSource.bounds,next=names.map(([name,lon,lat],i)=>({id:'historic-berlin-'+i,name,x:(lon-b.west)/(b.east-b.west)*1000,y:(b.north-lat)/(b.north-b.south)*1000}));const keep=p.labels.filter(l=>!l.id.startsWith('historic-berlin-'));if(keep.length+next.length>200)throw Error('地名の上限200件を超えます。');p.labels=[...keep,...next];p.mapSource.historicLayout={id,date:'1945-09-01',title:HISTORIC_LAYOUTS[id],source:'https://germanhistorydocs.org/en/occupation-and-the-emergence-of-two-states-1945-1961/berlin-september-1-1945',scope:'地区名の存在と相対配置の参考。座標は概略の現代位置。地区境界・街路・建物・当時の市街地面積は復元していない。'};return p;}

export const HISTORIC_REGIONS={midway1942:'midway',pearl1941:'pearl_harbor',normandy1944:'normandy',berlin1945:'berlin'};
export async function loadHistoricPack(id){if(!Object.hasOwn(HISTORIC_REGIONS,id)||id==='berlin1945')throw Error('配置データがありません。');const r=await fetch('./data/historic/'+id+'.json');if(!r.ok)throw Error('歴史配置を読み込めませんでした。');const data=await r.json();if(data.id!==id||data.region!==HISTORIC_REGIONS[id]||!Array.isArray(data.labels)||!Array.isArray(data.facilities))throw Error('歴史配置の形式が不正です。');return data;}
export function applyHistoricPack(p,data,{update=false,includeLabels=true,includeFacilities=true}={}){
 if(!data||p.mapSource?.id!==data.region)throw Error('先に対応する地域参考図を読み込んでください。');
 const b=p.mapSource.bounds;if(!b||![b.east,b.west,b.north,b.south].every(Number.isFinite)||b.east<=b.west||b.north<=b.south)throw Error('地図の緯度経度範囲が不正です。');
 const pos=([lon,lat])=>{const q={x:(lon-b.west)/(b.east-b.west)*1000,y:(b.north-lat)/(b.north-b.south)*1000};if(!Number.isFinite(q.x)||!Number.isFinite(q.y)||q.x<0||q.x>1000||q.y<0||q.y>1000)throw Error('配置が地図範囲外です。');return q;};
 const prefix='hist-'+data.id+'-',history=item=>({layout:data.id,date:data.date,version:data.version,source:data.sources[item.source??0]?.url||'',sourceTitle:data.sources[item.source??0]?.title||'',accuracy:'approximate',note:item.note||'史実地名の概略中心位置。'});
 const newLabels=data.labels.map(l=>({id:prefix+l.key,name:l.name,...pos([l.lon,l.lat]),history:history(l)}));
 const newFacilities=data.facilities.map(f=>({id:prefix+f.key,name:f.name,type:f.type,team:'neutral',points:f.coordinates.map(pos),radiusKm:Math.max(.01,f.width??.02),footprint:f.geometry==='rectangle'?'rectangle':'point',blockKm:.08,buildingHeight:6,defense:0,damage:0,repairRate:0,supportRate:0,history:history(f)}));
 const merge=(current,entries)=>{const by=new Map(entries.map(e=>[e.id,e]));return [...current.map(e=>update&&by.has(e.id)?by.get(e.id):e),...entries.filter(e=>!current.some(v=>v.id===e.id))];};
 const labels=includeLabels?merge(p.labels,newLabels):p.labels,facilities=includeFacilities?merge(p.facilities,newFacilities):p.facilities;if(labels.length>200||facilities.length>1000)throw Error('地名200件・設備1000件の上限を超えます。');
 p.labels=labels;p.facilities=facilities;p.mapSource.historicLayout={id:data.id,date:data.date,title:data.title,version:data.version,sources:data.sources,scope:data.scope};return p;
}
