import {ADDED_TYPE_BY_ID} from './catalog-additions.mjs';
// Abstract production units for fictional animation, not physical supply forecasting.
export const CIVILIAN_TYPES=['refugees','evacuees','civilians','aid_workers','civilian_bus','relief_truck'];
export const isCivilian=u=>CIVILIAN_TYPES.includes(u.type);
export const LOGISTIC_FIELDS={initialFuel:'初期燃料 %',initialAmmo:'初期弾薬 %',initialFood:'初期食料 %',fuelPerKm:'燃料消費 % / km',ammoPerMinute:'射撃時の弾薬消費 % / 分',foodPerMinute:'食料消費 % / 分'};
export function validateLogistics(p){p.logisticsEnabled??=false;p.powerEnabled??=false;if(typeof p.logisticsEnabled!=='boolean'||typeof p.powerEnabled!=='boolean')throw Error('兵站・電力の有効設定が不正です。');const num=(v,a,b)=>typeof v==='number'&&Number.isFinite(v)&&v>=a&&v<=b;for(const u of p.units){const type=p.defaults.find(t=>t.id===u.type),foot=ADDED_TYPE_BY_ID[u.type]?.quantity==='名'||type?.domain==='land'&&['infantry','fire'].includes(type.category)||['infantry','marines','engineer','refugees','evacuees','civilians','aid_workers'].includes(u.type);for(const [k,v] of Object.entries({initialFuel:100,initialAmmo:100,initialFood:100,fuelPerKm:foot?0:.5,ammoPerMinute:isCivilian(u)?0:2,foodPerMinute:.05})){u[k]??=v;if(!num(u[k],0,100))throw Error('兵站の数値は0〜100です。');}}return p;}
export function validateInfrastructure(f){const supply=['supply_depot','distribution_center','food_depot','fuel_depot'].includes(f.type);const defaults={powerGrid:'main',powerOutput:['power','generator'].includes(f.type)?100:0,powerDemand:0,stockFuel:supply?500:0,stockAmmo:supply?500:0,stockFood:supply?500:0,supplyRate:supply?10:0};for(const [k,v] of Object.entries(defaults))f[k]??=v;if(typeof f.powerGrid!=='string'||f.powerGrid.length>60)throw Error('電力系統名は60文字以内です。');for(const k of ['powerOutput','powerDemand','stockFuel','stockAmmo','stockFood','supplyRate'])if(typeof f[k]!=='number'||!Number.isFinite(f[k])||f[k]<0||f[k]>1000000)throw Error('電力・在庫の数値は0〜1000000です。');}
function rawOperational(p,f,sec){let hp=f.hp??1000,clock=0;for(const e of [...(f.events||[])].sort((a,b)=>a.at-b.at)){const at=e.at*p.secondsPerFrame;if(at>sec)break;if(hp>0)hp=Math.min(f.maxHp??1000,hp+(at-clock)*(f.repairRate??0));hp=Math.max(0,Math.min(f.maxHp??1000,hp+e.delta));clock=at;}return hp>0;}
export function powerBalance(p,sec=0){const groups=new Map();for(const f of [...(p.facilities||[])].sort((a,b)=>a.id<b.id?-1:a.id>b.id?1:0)){const key=f.team+' / '+(f.powerGrid||'main');if(!groups.has(key))groups.set(key,{key,output:0,demand:0});if(!rawOperational(p,f,sec))continue;const g=groups.get(key);g.output+=f.powerOutput||0;g.demand+=f.powerDemand||0;}return [...groups.values()].map(g=>({...g,ratio:g.demand?Math.min(1,g.output/g.demand):1}));}
export function powerFactor(p,f,seconds=0){if(!p.powerEnabled||!f.powerDemand)return 1;const balance=(p._powerSeconds===seconds?p._powerBalance:null)??powerBalance(p,seconds);return balance.find(g=>g.key===f.team+' / '+(f.powerGrid||'main'))?.ratio??0;}
export function supplySpeed(p,u,s){if(!p.logisticsEnabled||u.type==='missile')return 1;return ((u.fuelPerKm??0)>0&&(s.fuel??u.initialFuel??100)<=0?0:1)*((s.food??u.initialFood??100)<=0?.5:1);}
export function supplyFire(p,u,s){return p.logisticsEnabled&&u.type!=='missile'&&(u.ammoPerMinute??0)>0&&(s.ammo??u.initialAmmo??100)<=0?0:1;}
const round=x=>Math.round(x*1e6)/1e6;
export function logisticsStep(p,units,old,next,stocks,seconds){if(!p.logisticsEnabled)return;for(let i=0;i<units.length;i++){const u=units[i],s=old[i],n=next[i];if(n.hp<=0||n.spent||n.recovered||n.mergedInto||u.type==='missile'||seconds<u.start*p.secondsPerFrame)continue;const km=Math.hypot((n.x-s.x)*p.widthKm/1000,(n.y-s.y)*p.heightKm/1000);n.fuel=Math.max(0,(s.fuel??u.initialFuel)-km*u.fuelPerKm);n.ammo=Math.max(0,(s.ammo??u.initialAmmo)-(n.fired?u.ammoPerMinute/60:0));n.food=Math.max(0,(s.food??u.initialFood)-u.foodPerMinute/60);delete n.fired;}
 for(const f of [...(p.facilities||[])].sort((a,b)=>a.id<b.id?-1:a.id>b.id?1:0)){if(!f.supplyRate||!rawOperational(p,f,seconds))continue;const rate=f.supplyRate/60*powerFactor(p,f,seconds);if(rate<=0)continue;const stock=stocks[f.id]??=Object.fromEntries(['Fuel','Ammo','Food'].map(k=>[k.toLowerCase(),f['stock'+k]||0]));const receivers=next.map((s,i)=>({s,u:units[i]})).filter(({s,u})=>s.hp>0&&!s.spent&&!s.recovered&&!s.mergedInto&&u.type!=='missile'&&seconds>=u.start*p.secondsPerFrame&&(u.team===f.team||f.team==='neutral'&&isCivilian(u))&&Math.hypot((s.x-f.points[0].x)*p.widthKm/1000,(s.y-f.points[0].y)*p.heightKm/1000)<=f.radiusKm);
 for(const key of ['fuel','ammo','food']){const requests=receivers.map(({s})=>({s,need:Math.min(rate,100-(s[key]??100))})),total=requests.reduce((a,v)=>a+v.need,0),factor=total?Math.min(1,stock[key]/total):0;let used=0;for(const {s,need} of requests){const amount=need*factor;s[key]=(s[key]??100)+amount;used+=amount;}stock[key]=Math.max(0,stock[key]-used);}}
 for(const n of next)for(const k of ['fuel','ammo','food'])if(n[k]!=null)n[k]=round(n[k]);}
// Explicit finite facility ammunition for scheduled mounts. Units are abstract counts.
export function consumeWeaponSupply(p,stocks,id,u,s,requested,seconds){const f=p.facilities.find(f=>f.id===id);if(!p.logisticsEnabled||!f||f.team!==u.team||!rawOperational(p,f,seconds)||powerFactor(p,f,seconds)<=0||Math.hypot((s.x-f.points[0].x)*p.widthKm/1000,(s.y-f.points[0].y)*p.heightKm/1000)>f.radiusKm)return 0;const stock=stocks[id]??=Object.fromEntries(['Fuel','Ammo','Food'].map(k=>[k.toLowerCase(),f['stock'+k]||0]));const amount=Math.min(requested,Math.floor(stock.ammo));stock.ammo-=amount;return amount;}
