import {validateMapSharing} from './map-sharing.mjs';
import {validateTerrainLayers,resetTerrainLayers,remapTerrainLayers,setTerrainCell} from './map-layers.mjs';
import {validateFacilities,FACILITY_LINE_TYPES} from './facilities.mjs';
// MAP-22: deterministic map assets, independent of the battle clock.
export const ENV_DEFAULTS={latitude:35,longitude:135,weather:'clear',climate:'temperate',temperature:20,windSpeed:0,windDirection:0,visibility:20,precipitation:0,humidity:50,soilMoisture:30,snowDepth:0,seaLevel:0,waterTemperature:15,pressure:1013};
export const WEATHER={clear:'晴れ',cloudy:'曇り',rain:'雨',snow:'雪',fog:'霧',storm:'嵐'};
export const CLIMATES={polar:'寒帯',cold:'亜寒帯',temperate:'温帯',dry:'乾燥帯',tropical:'熱帯'};
import {SYMBOL_NAMES} from './cartography-icons.mjs';
export const MAP_SYMBOLS=SYMBOL_NAMES;
export const LINE_TYPES=FACILITY_LINE_TYPES;
const clone=v=>JSON.parse(JSON.stringify(v)),num=(v,a,b)=>Number.isFinite(v)&&v>=a&&v<=b;
export function validateMap(p,terrainTypes){validateMapSharing(p);validateTerrainLayers(p,terrainTypes);p.facilityIconScale??=1;p.mapSymbolScale??=1;p.mapViewLayers??={terrain:true,elevation:true,facilities:true,symbols:true,images:true,labels:true,background:true};for(const k of ['facilityIconScale','mapSymbolScale'])if(!num(p[k],.05,4))throw Error('アイコン倍率は0.05〜4です。');if(!p.mapViewLayers||typeof p.mapViewLayers!=='object'||Array.isArray(p.mapViewLayers))throw Error('表示レイヤーが不正です。');for(const k of ['terrain','elevation','facilities','symbols','images','labels','background']){p.mapViewLayers[k]??=true;if(typeof p.mapViewLayers[k]!=='boolean')throw Error('表示レイヤーが不正です。');}p.contourInterval??=100;p.showBathymetry??=false;if(!num(p.contourInterval,10,5000)||typeof p.showBathymetry!=='boolean')throw Error('等高線の設定が不正です。');p.mapSource??=null;if(p.mapSource!==null&&(typeof p.mapSource!=='object'||typeof p.mapSource.name!=='string'||p.mapSource.name.length>120||typeof p.mapSource.version!=='string'||p.mapSource.version.length>30||JSON.stringify(p.mapSource).length>100000))throw Error('地図の出典情報が不正です。');p.elevation??=Array(p.terrain.length).fill(0);p.mapSeed??='MFDCO';p.environment??={...ENV_DEFAULTS};p.mapSymbols??=[];p.mapAtlas??=[];p.mapImages??=[];validateMapImages(p.mapImages);p.backgroundBounds??=null;if(p.backgroundBounds){const b=p.backgroundBounds;if(!num(b.x,0,1000)||!num(b.y,0,1000)||!num(b.width,.001,1000)||!num(b.height,.001,1000)||b.x+b.width>1000.000001||b.y+b.height>1000.000001)throw Error('背景画像の配置範囲が不正です。');}
 if(!Array.isArray(p.elevation)||p.elevation.length!==p.terrain.length||p.elevation.some(v=>!num(v,-11000,9000)))throw Error('標高は-11000〜9000mで指定してください。');
 if(typeof p.mapSeed!=='string'||p.mapSeed.length>80)throw Error('シードは80文字以内です。');const e=p.environment;for(const [k,v] of Object.entries(ENV_DEFAULTS))e[k]??=v;for(const [k,a,b] of [['humidity',0,100],['soilMoisture',0,100],['snowDepth',0,100],['seaLevel',-500,500],['waterTemperature',-5,50],['pressure',800,1100]])if(!num(e[k],a,b))throw Error('地理条件の数値が不正です。');
 if(!e||!num(e.latitude,-90,90)||!num(e.longitude,-180,180)||!Object.hasOwn(WEATHER,e.weather)||!Object.hasOwn(CLIMATES,e.climate)||!num(e.temperature,-100,70)||!num(e.windSpeed,0,150)||!num(e.windDirection,0,360)||!num(e.visibility,0,1000)||!num(e.precipitation,0,1000))throw Error('戦場環境の数値を確認してください。');
 if(!Array.isArray(p.mapSymbols)||p.mapSymbols.length>500||p.mapSymbols.some(s=>!s||!Object.hasOwn(MAP_SYMBOLS,s.type)||!num(s.x,0,1000)||!num(s.y,0,1000)||typeof s.name!=='string'||s.name.length>60))throw Error('地図記号が不正です。');
 if(!Array.isArray(p.mapAtlas)||p.mapAtlas.length>24)throw Error('接続マップは24枚までです。');const cells=new Set(['0,0']);let total=0,imageBytes=p.mapImages.reduce((n,i)=>n+i.data.length,0);
 for(const t of p.mapAtlas){const key=t.gx+','+t.gy;if(!Number.isInteger(t.gx)||!Number.isInteger(t.gy)||Math.abs(t.gx)>24||Math.abs(t.gy)>24||cells.has(key)||typeof t.title!=='string'||t.title.length>120||!Number.isInteger(t.cols)||!Number.isInteger(t.rows)||!num(t.cols,1,2048)||!num(t.rows,1,2048)||!num(t.widthKm,1,20000)||!num(t.heightKm,1,20000)||!Array.isArray(t.terrain)||t.terrain.length!==t.cols*t.rows||t.terrain.some(k=>!Object.hasOwn(terrainTypes,k))||!Array.isArray(t.elevation)||t.elevation.length!==t.terrain.length||t.elevation.some(v=>!num(v,-11000,9000)))throw Error('接続マップのデータが不正です。');t.mapSymbols??=[];if(!Array.isArray(t.mapSymbols)||t.mapSymbols.length>500||t.mapSymbols.some(s=>!s||!Object.hasOwn(MAP_SYMBOLS,s.type)||!num(s.x,0,1000)||!num(s.y,0,1000)||typeof s.name!=='string'||s.name.length>60))throw Error('接続地図の記号が不正です。');for(const k of ['facilityIconScale','mapSymbolScale']){t[k]??=1;if(!num(t[k],.05,4))throw Error('接続地図のアイコン倍率が不正です。');}if(t.mapSource&&(typeof t.mapSource!=='object'||typeof t.mapSource.name!=='string'||JSON.stringify(t.mapSource).length>100000))throw Error('接続地図の出典が不正です。');t.mapImages??=[];validateMapImages(t.mapImages);imageBytes+=t.mapImages.reduce((n,i)=>n+i.data.length,0);t.facilities??=[];validateFacilities({facilities:t.facilities});cells.add(key);total+=t.terrain.length;}
 if(imageBytes>8000000)throw Error('配置画像の合計は接続先を含め8MBまでです。');
 if(total>4194304)throw Error('接続マップの総セル数は4194304以内です。');return p;
}
export function mapSnapshot(p,gx=0,gy=0){return{gx,gy,title:p.title,widthKm:p.widthKm,heightKm:p.heightKm,cols:p.terrainCols,rows:p.terrainRows,terrain:[...p.terrain],elevation:[...p.elevation],facilities:clone(p.facilities),mapImages:clone(p.mapImages||[]),mapSymbols:clone(p.mapSymbols||[]),mapSource:clone(p.mapSource||null),facilityIconScale:p.facilityIconScale??1,mapSymbolScale:p.mapSymbolScale??1};}
export function seedRandom(seed){let a=2166136261;for(const c of String(seed))a=Math.imul(a^c.charCodeAt(0),16777619);return()=>{a+=0x6D2B79F5;let t=Math.imul(a^a>>>15,1|a);t^=t+Math.imul(t^t>>>7,61|t);return((t^t>>>14)>>>0)/4294967296;};}
export function generateMap(p,kind,seed){
 if(!Object.hasOwn(MAP_PRESETS,kind))throw Error('地形テンプレートが不正です。');
 resetTerrainLayers(p);p.mapSource=null;const random=seedRandom(seed),hills=Array.from({length:18},()=>({x:random(),y:random(),r:.08+random()*.24,h:random()})),isles=Array.from({length:32},()=>({x:.06+random()*.88,y:.06+random()*.88,r:.018+random()*.055,h:100+random()*600}));p.mapSeed=String(seed);
 for(let y=0;y<p.terrainRows;y++)for(let x=0;x<p.terrainCols;x++){
  const nx=(x+.5)/p.terrainCols,ny=(y+.5)/p.terrainRows,r=Math.hypot(nx-.5,ny-.5),n=hills.reduce((v,h)=>v+h.h*Math.exp(-((nx-h.x)**2+(ny-h.y)**2)/(h.r*h.r)),0);
  let height=kind==='ocean'?-200:kind==='islands'?(n-.85)*900:kind==='coast'?(nx-.45)*1700+n*250:n*500;
  if(kind==='archipelago')height=Math.max(...isles.map(h=>h.h*Math.exp(-((nx-h.x)**2+(ny-h.y)**2)/(h.r*h.r))))-90;
  if(kind==='atoll')height=150*Math.exp(-(((r-.27)/.038)**2))-35+n*2;
  if(kind==='volcanic')height=1800*Math.exp(-r*r/.038)-130-900*Math.exp(-r*r/.001);
  if(kind==='peninsula')height=(.17+.1*Math.sin(nx*7)-Math.abs(ny-.5))*2200+(1-nx)*120;
  if(kind==='strait')height=(Math.abs(nx-.5-.06*Math.sin(ny*8))-.16)*2200;
  if(['river','delta'].includes(kind)){const stream=Math.abs(nx-(.5+.12*Math.sin(ny*7)));height=stream<.022||(kind==='delta'&&ny>.55&&Math.abs(nx-(.5+(ny-.55)*.7))<.018)?-8:30+n*60;if(kind==='delta'&&ny>.86)height=-40;}
  if(kind==='lake')height=r<.23+n*.01?-60:80+n*250;
  if(kind==='snowfield')height=100+n*350;
  if(kind==='highlands')height=800+n*700;
  if(kind==='urban'||kind==='farmland')height=15+n*30;
  if(kind==='port_city')height=nx>.68+.035*Math.sin(ny*15)?-100:15+n*20;
  let t=height<0?'water':kind==='desert'?(n>1.4?'rock':'desert'):kind==='wetland'?(n<.6?'water':n<1.1?'swamp':'forest'):height>1000?'mountain':height>600?'hill':n>.9?'forest':'plain';
  if(height>=0){if(kind==='atoll')t='beach';if(kind==='snowfield')t='snow';if(kind==='farmland')t=Math.floor(nx*18)%6===0?'forest':'farmland';if(kind==='urban')t=r<.4?'urban':'farmland';if(kind==='port_city')t=nx>.22&&nx<.64&&ny>.15&&ny<.85?'urban':'plain';}
  const i=y*p.terrainCols+x;p.elevation[i]=Math.round(height)||0;p.terrain[i]=t;
 }
 if(['urban','port_city'].includes(kind)){const id='generated-city',city={id,type:'city',name:MAP_PRESETS[kind],team:'neutral',radiusKm:.1,defense:15,damage:0,blockKm:Math.max(.05,Math.min(5,p.widthKm/150)),points:[{x:200,y:200},{x:kind==='port_city'?620:800,y:800}]};const index=p.facilities.findIndex(f=>f.id===id);if(index>=0)p.facilities[index]=city;else{if(p.facilities.length>=1000)throw Error('都市生成には設備の空きが必要です。');p.facilities.push(city);}}
 return p;
}
export function paintMap(p,x,y,{tool='terrain',terrain='plain',radius=1,elevation=0,delta=25,shape='circle',soft=true,layerId='base'}={}){const cx=Math.max(0,Math.min(p.terrainCols-1,Math.floor(x/1000*p.terrainCols))),cy=Math.max(0,Math.min(p.terrainRows-1,Math.floor(y/1000*p.terrainRows))),source=tool==='smooth'?[...p.elevation]:null;for(let yy=Math.max(0,cy-radius);yy<=Math.min(p.terrainRows-1,cy+radius);yy++)for(let xx=Math.max(0,cx-radius);xx<=Math.min(p.terrainCols-1,cx+radius);xx++){const d=shape==='circle'?Math.hypot(xx-cx,yy-cy):Math.max(Math.abs(xx-cx),Math.abs(yy-cy));if(d>radius)continue;const i=yy*p.terrainCols+xx,t=radius?Math.min(1,d/radius):0,weight=soft?1-t*t*(3-2*t):1;if(tool==='terrain'||tool==='erase'){setTerrainCell(p,i,terrain,layerId,tool==='erase');continue;}let v=p.elevation[i];if(tool==='smooth'){let sum=0,n=0;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const sx=xx+dx,sy=yy+dy;if(sx>=0&&sx<p.terrainCols&&sy>=0&&sy<p.terrainRows){sum+=source[sy*p.terrainCols+sx];n++;}}v+=(sum/n-v)*weight;}else if(tool==='height')v+=(elevation-v)*weight;else v+=delta*weight;p.elevation[i]=Math.round(Math.max(-11000,Math.min(9000,v))*100)/100;}}
export function resampleMap(p,cols,rows){if(!Number.isInteger(cols)||!Number.isInteger(rows)||cols<1||rows<1||cols>2048||rows>2048||cols*rows>2097152)throw Error('地形は各辺2048・合計2097152セル以内です。');const old=p.terrain,heights=p.elevation,oc=p.terrainCols,or=p.terrainRows,idx=i=>Math.min(or-1,Math.floor(Math.floor(i/cols)*or/rows))*oc+Math.min(oc-1,Math.floor(i%cols*oc/cols));remapTerrainLayers(p,cols,rows,i=>idx(i));p.terrain=Array.from({length:cols*rows},(_,i)=>old[idx(i)]);p.elevation=Array.from({length:cols*rows},(_,i)=>heights?.[idx(i)]??0);p.terrainCols=cols;p.terrainRows=rows;}
// Import finite snapshots, never recursive project references. Edge strip uses destination cell spacing.
export function connectMap(p,other,side,extendLines=true){const dirs={north:[0,-1],south:[0,1],west:[-1,0],east:[1,0]},d=dirs[side];if(!d)throw Error('接続方向が不正です。');const tiles=[mapSnapshot(other),...other.mapAtlas].map(t=>({...clone(t),gx:t.gx+d[0],gy:t.gy+d[1]}));const occupied=new Set(['0,0',...p.mapAtlas.map(t=>t.gx+','+t.gy)]);for(const t of tiles){const key=t.gx+','+t.gy;if(occupied.has(key))throw Error('接続先が既存の地図と重なります。接続一覧から解除してください。');occupied.add(key);}if(p.mapAtlas.length+tiles.length>24)throw Error('接続マップは24枚までです。');
 const horizontal=!!d[0],oc=p.terrainCols,or=p.terrainRows,nc=oc+(horizontal?1:0),nr=or+(horizontal?0:1),cw=p.widthKm/oc,ch=p.heightKm/or,nw=p.widthKm+(horizontal?cw:0),nh=p.heightKm+(horizontal?0:ch);if(nc>2048||nr>2048||nc*nr>2097152||nw>20000||nh>20000)throw Error('接続後の地図サイズが上限を超えます。');
 const terrain=Array(nc*nr).fill('water'),height=Array(nc*nr).fill(0),ox=side==='west'?1:0,oy=side==='north'?1:0;
 for(let y=0;y<or;y++)for(let x=0;x<oc;x++){terrain[(y+oy)*nc+x+ox]=p.terrain[y*oc+x];height[(y+oy)*nc+x+ox]=p.elevation[y*oc+x];}
 for(let k=0;k<(horizontal?or:oc);k++){const along=(k+.5)*(horizontal?ch:cw),extent=horizontal?other.heightKm:other.widthKm;if(along>=extent)continue;const sx=horizontal?(side==='east'?0:other.terrainCols-1):Math.floor(along/other.widthKm*other.terrainCols),sy=horizontal?Math.floor(along/other.heightKm*other.terrainRows):(side==='south'?0:other.terrainRows-1),dst=horizontal?(k*nc+(side==='east'?nc-1:0)):((side==='south'?nr-1:0)*nc+k),src=sy*other.terrainCols+sx;terrain[dst]=other.terrain[src];height[dst]=other.elevation[src];}
 const shift=v=>{v.x=(v.x*p.widthKm/1000+ox*cw)/nw*1000;v.y=(v.y*p.heightKm/1000+oy*ch)/nh*1000;};
 for(const u of p.units){shift(u);u.points.forEach(shift);for(const o of u.orders||[]){if(Number.isFinite(o.x)&&Number.isFinite(o.y))shift(o);o.points?.forEach(shift);}}
 p.labels.forEach(shift);p.mapSymbols.forEach(shift);p.mapImages?.forEach(shift);p.radars.forEach(shift);
 for(const f of p.facilities){const endpoints=f.points.map(v=>({...v}));f.points.forEach(shift);if(extendLines&&LINE_TYPES.includes(f.type)){for(const i of [0,f.points.length-1]){const v=endpoints[i];if(horizontal?Math.abs(v.x-(side==='east'?1000:0))<=1000/oc:Math.abs(v.y-(side==='south'?1000:0))<=1000/or){const q={...endpoints[i]};shift(q);if(horizontal)q.x=side==='east'?1000:0;else q.y=side==='south'?1000:0;if(f.points.length>=100)throw Error('線の頂点は100点までです。');if(i===0)f.points.unshift(q);else f.points.push(q);}}}}
 if(extendLines){for(const f of other.facilities.filter(f=>LINE_TYPES.includes(f.type))){for(const endpoint of [f.points[0],f.points.at(-1)]){const edge=side==='east'?0:side==='west'?1000:side==='south'?0:1000,near=horizontal?Math.abs(endpoint.x-edge)<=1000/other.terrainCols:Math.abs(endpoint.y-edge)<=1000/other.terrainRows;if(!near)continue;const along=horizontal?endpoint.y*other.heightKm/1000:endpoint.x*other.widthKm/1000;if(along>(horizontal?p.heightKm:p.widthKm))continue;if(p.facilities.length>=1000)throw Error('設備は1000件までです。');let id='edge-'+p.facilities.length;while(p.facilities.some(f=>f.id===id))id+='x';const a=horizontal?{x:side==='east'?p.widthKm/nw*1000:cw/nw*1000,y:along/nh*1000}:{x:along/nw*1000,y:side==='south'?p.heightKm/nh*1000:ch/nh*1000},b={...a};if(horizontal)b.x=side==='east'?1000:0;else b.y=side==='south'?1000:0;p.facilities.push({...clone(f),id,points:[a,b]});}}}
 remapTerrainLayers(p,nc,nr,i=>{const x=i%nc-ox,y=Math.floor(i/nc)-oy;return x>=0&&x<oc&&y>=0&&y<or?y*oc+x:-1;},terrain);shiftBackground(p,shift,nw,nh);expandGeoBounds(p,nw,nh,ox*cw,oy*ch);p.widthKm=nw;p.heightKm=nh;p.manualHeight=true;p.mapAspect=nw/nh;p.terrainCols=nc;p.terrainRows=nr;p.terrain=terrain;p.elevation=height;p.mapAtlas.push(...tiles);return p;
}

export function fillTerrain(p,x,y,type){const cols=p.terrainCols,rows=p.terrainRows,cx=Math.max(0,Math.min(cols-1,Math.floor(x/1000*cols))),cy=Math.max(0,Math.min(rows-1,Math.floor(y/1000*rows))),start=cy*cols+cx,source=p.terrainBase||p.terrain,old=source[start];if(old===type)return;const queue=[start],seen=new Uint8Array(cols*rows);seen[start]=1;for(let n=0;n<queue.length;n++){const i=queue[n],xx=i%cols,yy=Math.floor(i/cols);setTerrainCell(p,i,type);for(const next of [xx>0?i-1:-1,xx+1<cols?i+1:-1,yy>0?i-cols:-1,yy+1<rows?i+cols:-1])if(next>=0&&!seen[next]&&source[next]===old){seen[next]=1;queue.push(next);}}}

export function validateMapImages(images){if(!Array.isArray(images)||images.length>100)throw Error('画像配置は100件までです。');const ids=new Set();for(const i of images){if(!i||typeof i.id!=='string'||!i.id||i.id.length>40||ids.has(i.id)||typeof i.name!=='string'||i.name.length>60||!num(i.x,0,1000)||!num(i.y,0,1000)||!num(i.widthKm,.01,1000)||!num(i.heightKm,.01,1000)||typeof i.data!=='string'||i.data.length>1100000||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(i.data))throw Error('配置画像の形式・大きさ・名前が不正です。');ids.add(i.id);}}
export function configureMapSize(p,cols,widthKm,heightKm){if(!Number.isInteger(cols)||!num(cols,1,2048)||!num(widthKm,1,20000)||!num(heightKm,1,20000))throw Error('横セル数と横・縦の距離を確認してください。');const rows=Math.max(1,Math.round(cols*heightKm/widthKm));resampleMap(p,cols,rows);p.widthKm=widthKm;p.heightKm=heightKm;p.manualHeight=true;p.mapAspect=widthKm/heightKm;return rows;}
// EXPAND-23: pad with water without resampling old cells, preserving all existing physical distances.
export function expandMap(p,side,count=1){if(!['north','south','east','west'].includes(side)||!Number.isInteger(count)||count<1||count>128)throw Error('拡張は1〜128セルで指定してください。');const horizontal=side==='east'||side==='west',oc=p.terrainCols,or=p.terrainRows,nc=oc+(horizontal?count:0),nr=or+(horizontal?0:count),cw=p.widthKm/oc,ch=p.heightKm/or,nw=p.widthKm+(horizontal?cw*count:0),nh=p.heightKm+(horizontal?0:ch*count),ox=side==='west'?count:0,oy=side==='north'?count:0;if(nc>2048||nr>2048||nc*nr>2097152||nw>20000||nh>20000)throw Error('拡張後のサイズが上限を超えます。');const terrain=Array(nc*nr).fill('water'),elevation=Array(nc*nr).fill(0);for(let y=0;y<or;y++)for(let x=0;x<oc;x++){terrain[(y+oy)*nc+x+ox]=p.terrain[y*oc+x];elevation[(y+oy)*nc+x+ox]=p.elevation[y*oc+x];}const shift=v=>{v.x=Math.max(0,Math.min(1000,(v.x*p.widthKm/1000+ox*cw)/nw*1000));v.y=Math.max(0,Math.min(1000,(v.y*p.heightKm/1000+oy*ch)/nh*1000));};for(const u of p.units){shift(u);u.points.forEach(shift);for(const o of u.orders||[]){if(Number.isFinite(o.x)&&Number.isFinite(o.y))shift(o);o.points?.forEach(shift);}}p.labels.forEach(shift);p.mapSymbols.forEach(shift);p.mapImages.forEach(shift);p.radars.forEach(shift);p.facilities.forEach(f=>f.points.forEach(shift));remapTerrainLayers(p,nc,nr,i=>{const x=i%nc-ox,y=Math.floor(i/nc)-oy;return x>=0&&x<oc&&y>=0&&y<or?y*oc+x:-1;},terrain);shiftBackground(p,shift,nw,nh);expandGeoBounds(p,nw,nh,ox*cw,oy*ch);Object.assign(p,{widthKm:nw,heightKm:nh,terrainCols:nc,terrainRows:nr,terrain,elevation,manualHeight:true,mapAspect:nw/nh});return p;}
export const MAP_PRESETS={islands:'島嶼',archipelago:'諸島',atoll:'環礁',volcanic:'火山島',coast:'沿岸',peninsula:'半島',strait:'海峡',continent:'山地・平原',river:'河川平野',delta:'三角州',lake:'湖水地方',desert:'砂漠',wetland:'湿地',snowfield:'雪原',highlands:'高原',urban:'都市圏',port_city:'港湾都市',farmland:'田園',ocean:'外洋'};

function shiftBackground(p,shift,nw,nh){if(!p.background)return;const b=p.backgroundBounds||{x:0,y:0,width:1000,height:1000},point={x:b.x,y:b.y};shift(point);p.backgroundBounds={...point,width:b.width*p.widthKm/nw,height:b.height*p.heightKm/nh};}

// Preserve geographic anchors when padding a georeferenced regional map.
function expandGeoBounds(p,nw,nh,westKm,northKm){const b=p.mapSource?.bounds;if(!b||![b.west,b.east,b.north,b.south].every(Number.isFinite)||b.east<=b.west||b.north<=b.south)return;const dx=(b.east-b.west)/p.widthKm,dy=(b.north-b.south)/p.heightKm,west=b.west-westKm*dx,north=b.north+northKm*dy;p.mapSource={...p.mapSource,bounds:{west,east:west+nw*dx,north,south:north-nh*dy}};}
