import {visibleLabels} from './map-edit-policy.mjs';
import {rasterMap} from './map-raster.mjs';
import {mapGlyph} from './cartography-icons.mjs';
import {TERRAIN} from './engine.mjs';
import {terrainRects,facilityMarkup} from './terrain-view.mjs';
import {mapSnapshot} from './map-model.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function mapSymbolsSVG(p){return(p.mapSymbols||[]).map(s=>`<g transform="translate(${s.x} ${s.y*.625}) scale(${p.mapSymbolScale??1})"><rect x="-14" y="-14" width="28" height="28" rx="2" fill="#142824" opacity=".9"/>${mapGlyph(s.type)}<text x="17" y="4" font-size="10" fill="#e3e7d8" stroke="#243830" stroke-width="2" paint-order="stroke">${esc(s.name)}</text></g>`).join('')+mapImagesSVG(p);}
export function mapImagesSVG(p){return(p.mapImages||[]).map(i=>{const raw=i.widthKm/p.widthKm*1000,scale=Math.max(1,16/raw),w=raw*scale,h=i.heightKm/p.heightKm*625*scale;return `<g data-map-image="${esc(i.id)}" transform="translate(${i.x} ${i.y*.625})"><image href="${esc(i.data)}" x="${-w/2}" y="${-h/2}" width="${w}" height="${h}" preserveAspectRatio="none"/><text y="${h/2+13}" text-anchor="middle" fill="#e3e7d8" font-size="11" stroke="#162820" stroke-width="2" paint-order="stroke">${esc(i.name)}</text></g>`;}).join('');}
export function elevationSVG(p,{shade=true,contours=true}={}){const raster=rasterMap(p,TERRAIN,{elevation:true,shade,contours});if(raster)return raster;const c=p.terrainCols,r=p.terrainRows,w=1000/c,h=625/r,out=[],path=[];for(let y=0;y<r;y++){if(shade){let x=0;while(x<c){const band=p.terrain[y*c+x]==='water'&&!p.showBathymetry?0:Math.floor((p.elevation[y*c+x]||0)/200);let end=x+1;while(end<c&&(p.terrain[y*c+end]==='water'&&!p.showBathymetry?0:Math.floor((p.elevation[y*c+end]||0)/200))===band)end++;if(band!==0)out.push(`<rect x="${x*w}" y="${y*h}" width="${(end-x)*w+.1}" height="${h+.1}" fill="${band>0?'#eee5c6':'#072330'}" opacity="${Math.min(.45,Math.abs(band)*.025)}"/>`);x=end;}}if(contours)for(let x=0;x<c;x++){if(p.terrain[y*c+x]==='water'&&!p.showBathymetry)continue;const a=Math.floor((p.elevation[y*c+x]||0)/(p.contourInterval??100));if(x+1<c&&a!==Math.floor(p.elevation[y*c+x+1]/(p.contourInterval??100)))path.push(`M${(x+1)*w} ${y*h}v${h}`);if(y+1<r&&a!==Math.floor(p.elevation[(y+1)*c+x]/(p.contourInterval??100)))path.push(`M${x*w} ${(y+1)*h}h${w}`);}}return out.join('')+(contours?`<path d="${path.join('')}" fill="none" stroke="#c6b78c" stroke-width=".6" opacity=".42"/>`:'');}
export function cartographySVG(p,{shade=true,contours=true,zoom=1}={}){const v=p.mapViewLayers||{};return (v.terrain===false?'':terrainRects(p,TERRAIN))+(p.background&&v.background!==false?`<image href="${esc(p.background)}" x="${p.backgroundBounds?.x||0}" y="${(p.backgroundBounds?.y||0)*.625}" width="${p.backgroundBounds?.width||1000}" height="${(p.backgroundBounds?.height||1000)*.625}" preserveAspectRatio="none"/>`:'')+(v.elevation===false?'':elevationSVG(p,{shade,contours}))+(v.facilities===false?'':facilityMarkup(p))+mapSymbolsSVG({...p,mapSymbols:v.symbols===false?[]:p.mapSymbols,mapImages:v.images===false?[]:p.mapImages})+visibleLabels(v.labels===false?[]:p.labels,p.mapLabelPolicy,zoom).map(l=>`<text x="${l.x}" y="${l.y*.625}" font-size="${p.mapLabelPolicy==='avoid'?12/Math.max(1,zoom):12}" fill="#e2e7d7" stroke="#263b33" stroke-width="2" paint-order="stroke">${esc(l.name)}</text>`).join('')+mapCreditSVG(p);}
export function atlasSVG(p){const tiles=[mapSnapshot(p),...p.mapAtlas],minX=Math.min(...tiles.map(t=>t.gx)),maxX=Math.max(...tiles.map(t=>t.gx)),minY=Math.min(...tiles.map(t=>t.gy)),maxY=Math.max(...tiles.map(t=>t.gy)),w=(maxX-minX+1)*300,h=(maxY-minY+1)*210;let out=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}"><rect width="100%" height="100%" fill="#172e38"/>`;for(const t of tiles){out+=`<svg x="${(t.gx-minX)*300}" y="${(t.gy-minY)*210}" width="300" height="188" viewBox="0 0 1000 625">${terrainRects({terrainCols:t.cols,terrainRows:t.rows,terrain:t.terrain},TERRAIN)}${facilityMarkup({facilities:t.facilities||[],widthKm:t.widthKm,heightKm:t.heightKm,secondsPerFrame:60,facilityIconScale:t.facilityIconScale??1})}${mapSymbolsSVG({mapImages:t.mapImages,mapSymbols:t.mapSymbols||[],mapSymbolScale:t.mapSymbolScale??1,widthKm:t.widthKm,heightKm:t.heightKm})}${mapCreditSVG(t)}</svg><text x="${(t.gx-minX)*300+6}" y="${(t.gy-minY)*210+203}" font-size="12" fill="#d9e7d8">${esc(t.title)} (${t.gx},${t.gy})</text>`;}return out+'</svg>';}

export function mapCreditSVG(p){return p.mapSource?`<text x="990" y="620" text-anchor="end" fill="#e3e7d8" stroke="#162820" stroke-width="2" paint-order="stroke" font-size="7">${esc(p.mapSource.attribution||p.mapSource.name)}</text>`:'';}
