import {validateEffects,effectMarkup} from './presentation-effects.mjs';
const clone=v=>JSON.parse(JSON.stringify(v));
const num=(v,a,b)=>typeof v==='number'&&Number.isFinite(v)&&v>=a&&v<=b;
export function validateProduction(p){validateEffects(p);p.presentation??={palette:'green',font:'sans',weaponLayout:'cards'};if(!['green','amber','cyan'].includes(p.presentation.palette)||!['sans','mono'].includes(p.presentation.font)||!['cards','ship','vls'].includes(p.presentation.weaponLayout))throw Error('表示プリセットが不正です。');p.briefing??={title:'作戦概要',organization:'MFDCO',objective:'',situation:'',notes:''};for(const [k,max] of Object.entries({title:80,organization:80,objective:1000,situation:1000,notes:1000}))if(typeof p.briefing[k]!=='string'||p.briefing[k].length>max)throw Error('作戦概要の文字数を確認してください。');p.camera??={enabled:false,keys:[]};if(typeof p.camera.enabled!=='boolean'||!Array.isArray(p.camera.keys)||p.camera.keys.length>200)throw Error('カメラ設定が不正です。');const times=new Set();for(const k of p.camera.keys){if(!Number.isInteger(k.at)||k.at<0||k.at>p.duration||times.has(k.at)||!num(k.zoom,1,4)||!num(k.x,0,1000)||!num(k.y,0,625)||typeof k.follow!=='string'||k.follow&&!p.units.some(u=>u.id===k.follow))throw Error('カメラのframe・倍率・追従部隊を確認してください。');times.add(k.at);}p.camera.keys.sort((a,b)=>a.at-b.at);p.cuts??=[];if(!Array.isArray(p.cuts)||p.cuts.length>50)throw Error('カットは50件までです。');for(const c of p.cuts)if(typeof c.name!=='string'||!c.name||c.name.length>80||!Number.isInteger(c.from)||!Number.isInteger(c.to)||c.from<0||c.to<c.from||c.to>p.duration||!['tactical','briefing','weapons','cic','waveform','comms','status','damage','aviation','facilities','logistics','support'].includes(c.screen)||typeof c.unitId!=='string'||c.unitId&&!p.units.some(u=>u.id===c.unitId)||!['map','radar'].includes(c.mode))throw Error('カットの名前・区間・リンク部隊を確認してください。');return p;}
export function cameraAt(p,frame,states=[],fallback={zoom:1,center:{x:500,y:312.5}}){if(!p.camera?.enabled||!p.camera.keys.length)return fallback;const ks=p.camera.keys,a=[...ks].reverse().find(k=>k.at<=frame)||ks[0],b=ks.find(k=>k.at>a.at)||a,t=Math.max(0,Math.min(1,(frame-a.at)/(b.at-a.at||1))),mix=k=>a[k]+(b[k]-a[k])*t,zoom=mix('zoom'),follow=states.find(s=>s.id===a.follow),x=follow?.x??mix('x'),y=follow?follow.y*.625:mix('y');return{zoom,center:{x:Math.max(500/zoom,Math.min(1000-500/zoom,x)),y:Math.max(312.5/zoom,Math.min(625-312.5/zoom,y))}};}
export function equipmentPreset(p,hostId,name){const mounts=p.mounts.filter(m=>m.hostId===hostId).map(m=>({...clone(m),events:[],hostId:'',supplyId:''}));if(!mounts.length)throw Error('保存する武装がありません。');return{format:'mfdco-equipment',version:1,name:String(name).slice(0,80),mounts};}
export function applyEquipment(p,hostId,record){if(record?.format!=='mfdco-equipment'||record.version!==1||!Array.isArray(record.mounts)||!record.mounts.length||record.mounts.length>128||!p.units.some(u=>u.id===hostId))throw Error('装備プリセットの形式を確認してください。');if(p.mounts.length+record.mounts.length>128)throw Error('武装の合計上限128基を超えます。');const ids=new Set(p.mounts.map(m=>m.id));let n=1;const next=record.mounts.map(m=>{while(ids.has('eq-'+n))n++;const id='eq-'+n++;ids.add(id);return{...clone(m),id,hostId,supplyId:'',events:[]};});p.mounts.push(...next);return next;}

// Removing a unit keeps production cuts usable without a broken reference.
export function detachProduction(p,ids){const gone=new Set(ids);for(const k of p.camera?.keys||[])if(gone.has(k.follow))k.follow='';for(const c of p.cuts||[])if(gone.has(c.unitId))c.unitId='';}

export function styleProduction(svg,p,frame=0,screen=''){const skin={...(p.presentation||{}),...(p.screenStyles?.[screen]||{})},colors=skin.palette==='amber'?{'#c4e6db':'#eedab3','#8fe0c1':'#ffcf73','#91dcc2':'#ffcf73','#071416':'#18130c','#102326':'#2a2114','#386359':'#78613a'}:skin.palette==='cyan'?{'#c4e6db':'#c7e5ef','#8fe0c1':'#89dcff','#91dcc2':'#89dcff','#071416':'#08131e','#102326':'#11273a','#386359':'#345e77'}:{};return svg.replace(/<\/svg>$/,effectMarkup(p,frame,screen)+'</svg>').replace(/#[0-9a-f]{6}/g,c=>colors[c]||c).replace('font-family="Segoe UI,Meiryo,sans-serif"',`font-family="${skin.font==='mono'?'monospace,Meiryo':'Segoe UI,Meiryo,sans-serif'}"`);}
