// SAVE-24: IndexedDB avoids the small localStorage quota for national maps.
let database;
function openDB(){if(typeof indexedDB==='undefined')return Promise.reject(Error('IndexedDB unavailable'));return database??=new Promise((resolve,reject)=>{const r=indexedDB.open('mfdco-projects',1);r.onupgradeneeded=()=>r.result.createObjectStore('drafts');r.onsuccess=()=>resolve(r.result);r.onerror=()=>{database=null;reject(r.error);};r.onblocked=()=>{database=null;reject(Error('保存先が使用中です。ほかのタブを閉じてください。'));};});}
export async function loadProjectDraft(){let local=null,stored=null;try{local=JSON.parse(localStorage.getItem('mfdco-sim-v03')||'null');}catch{}try{const db=await openDB();stored=await new Promise((resolve,reject)=>{const r=db.transaction('drafts').objectStore('drafts').get('current');r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error);});}catch{}const chosen=(local?.savedAt??0)>(stored?.savedAt??0)?local:stored||local;return chosen?.project||chosen;}
export async function saveProjectDraft(project){const record={savedAt:Date.now(),project};try{const db=await openDB();await new Promise((resolve,reject)=>{const t=db.transaction('drafts','readwrite');t.objectStore('drafts').put(record,'current');t.oncomplete=resolve;t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error);});return;}catch{localStorage.setItem('mfdco-sim-v03',JSON.stringify(record));}}
function localRestorePoints(){try{const list=JSON.parse(localStorage.getItem('mfdco-restore-points')||'[]');return Array.isArray(list)?list.slice(0,3):[];}catch{return[];}}
export async function listRestorePoints(){try{const db=await openDB();return await new Promise((resolve,reject)=>{const r=db.transaction('drafts').objectStore('drafts').get('restore-points');r.onsuccess=()=>resolve(r.result||localRestorePoints());r.onerror=()=>reject(r.error);});}catch{return localRestorePoints();}}
let restoreQueue=Promise.resolve();
export function saveRestorePoint(project){const record={at:Date.now(),title:project.title,project:JSON.parse(JSON.stringify(project))};const task=restoreQueue.catch(()=>{}).then(()=>writeRestorePoint(record));restoreQueue=task;return task;}
async function writeRestorePoint(record){const points=await listRestorePoints();points.unshift(record);points.splice(3);try{const db=await openDB();await new Promise((resolve,reject)=>{const t=db.transaction('drafts','readwrite');t.objectStore('drafts').put(points,'restore-points');t.oncomplete=resolve;t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error);});}catch{localStorage.setItem('mfdco-restore-points',JSON.stringify(points));}return points;}
