import {VERSION,validate,copy} from './engine.mjs';
const finite=(n,a,b)=>typeof n==='number'&&Number.isFinite(n)&&n>=a&&n<=b;
export function packReplay(project,snapshots,events,view={}){
 const strings=[],lookup=new Map(),intern=s=>{s=String(s??'');if(!lookup.has(s)){lookup.set(s,strings.length);strings.push(s);}return lookup.get(s);};
 const ids=project.units.map(u=>u.id).sort();
 const frames=snapshots.map(states=>{let by=new Map(states.map(s=>[s.id,s]));return ids.map(id=>{let s=by.get(id),u=project.units.find(u=>u.id===id);return[s.x,s.y,s.hp??u.hp,s.maxHp??u.hp,s.personnel??u.personnel,s.attack??u.attack,intern(s.status),intern(s.reason),intern(s.target),intern(s.mergedInto),(s.retreat?1:0)+(s.repair?2:0)+(s.spent?4:0)+(s.recovered?8:0),s.recoveredCount??0,s.recoveredAt??0,...(project.logisticsEnabled?[s.fuel??u.initialFuel,s.ammo??u.initialAmmo,s.food??u.initialFood]:[])];});});
 return{...(project.mounts?.length?{weaponFrames:snapshots.map(states=>ids.map(id=>copy(states.find(s=>s.id===id)?.weaponStates||{})))}:{}),format:'mfdco-replay',replayVersion:project.logisticsEnabled?3:2,engineVersion:VERSION,project:copy(project),view:copy(view),ids,strings,frames,events:copy(events)};
}
export function validateReplay(r){
 const fail=m=>{throw new Error(m);};if(!r||r.format!=='mfdco-replay'||![1,2,3].includes(r.replayVersion)||typeof r.engineVersion!=='string')fail('リプレイ形式が不正です。');r.project=validate(r.project);const p=r.project;
 if(p.units.length>80||p.duration>10000)fail('リプレイは80部隊・10000frameまで対応します。');
 if(!Array.isArray(r.ids)||r.ids.length!==p.units.length||new Set(r.ids).size!==r.ids.length||r.ids.some(id=>!p.units.some(u=>u.id===id)))fail('部隊一覧が不正です。');
 if(!Array.isArray(r.strings)||r.strings.length>50000||r.strings.some(s=>typeof s!=='string'||s.length>300))fail('状態データが不正です。');
 if(!Array.isArray(r.frames)||r.frames.length!==p.duration+1)fail('リプレイのフレーム数が不正です。');
 for(let f of r.frames){if(!Array.isArray(f)||f.length!==r.ids.length)fail('リプレイの部隊数が不正です。');for(let row of f){if(!Array.isArray(row)||row.length!==(r.replayVersion===1?11:r.replayVersion===2?13:16)||!finite(row[0],0,1000)||!finite(row[1],0,1000)||!finite(row[2],0,80000000)||!finite(row[3],0,80000000)||row[2]>row[3]||!finite(row[4],0,80000000)||!finite(row[5],0,8000000)||!Number.isInteger(row[10])||row[10]<0||row[10]>(r.replayVersion===1?7:15))fail('リプレイの状態値が不正です。');if(r.replayVersion>=2&&(!Number.isInteger(row[11])||!finite(row[11],0,1000)||!finite(row[12],0,p.duration*p.secondsPerFrame)))fail('回収状態が不正です。');if(r.replayVersion===3&&row.slice(13,16).some(v=>!finite(v,0,100)))fail('兵站状態が不正です。');for(let i=6;i<=9;i++)if(!Number.isInteger(row[i])||row[i]<0||row[i]>=r.strings.length)fail('状態文字列の参照が不正です。');for(let i of [8,9])if(r.strings[row[i]]&&!r.ids.includes(r.strings[row[i]]))fail('対象部隊の参照が不正です。');}}
 if(!Array.isArray(r.events)||r.events.length>20000||r.events.some(e=>!e||!finite(e.time,0,p.duration*(p.secondsPerFrame??60))||(e.recordedAt!==undefined&&!finite(e.recordedAt,e.time,p.duration*(p.secondsPerFrame??60)))||!r.ids.includes(e.unit)||typeof e.label!=='string'||e.label.length>300||typeof e.kind!=='string'||e.kind.length>20))fail('リプレイのイベントが不正です。');
 if(r.weaponFrames){if(!Array.isArray(r.weaponFrames)||r.weaponFrames.length!==r.frames.length)fail('武装記録のframe数が不正です。');for(const frame of r.weaponFrames){if(!Array.isArray(frame)||frame.length!==r.ids.length)fail('武装記録の部隊数が不正です。');frame.forEach((record,i)=>{if(!record||typeof record!=='object'||Array.isArray(record)||Object.keys(record).length>128)fail('武装記録が不正です。');for(const [id,w] of Object.entries(record)){const m=p.mounts.find(m=>m.id===id&&m.hostId===r.ids[i]);if(!m||!w||!Number.isInteger(w.stock)||!finite(w.stock,0,100000)||!['ready','safe','fault'].includes(w.status)||typeof w.result!=='string'||w.result.length>100||typeof w.target!=='string'||w.target&&!r.ids.includes(w.target)||!Array.isArray(w.cells)||w.cells.length>256||w.cells.some(c=>!['loaded','empty','reserved','fault','disabled','firing','reloading'].includes(c))||w.reserve!==undefined&&(!Number.isInteger(w.reserve)||w.reserve< -1||w.reserve>100000))fail('武装残弾・状態が不正です。');if(w.activity!==undefined&&(!['idle','firing','reloading'].includes(w.activity)||!Number.isInteger(w.busyUntil)||!finite(w.busyUntil,0,6003600)||!Number.isInteger(w.pendingAmount)||!finite(w.pendingAmount,0,100000)||!Array.isArray(w.pendingCells)||new Set(w.pendingCells).size!==w.pendingCells.length||w.pendingCells.some(i=>!Number.isInteger(i)||i<0||i>=m.cells.length)))fail('武装の作業時間記録が不正です。');}});}}
 let v=r.view;if(v){v.screen??='tactical';v.consoleRadarId??='';v.consoleFilter??='all';v.consolePage??=0;v.linkedUnit??='';v.facilityFilter??={search:'',type:'all',team:'all'};if(typeof v.facilityFilter.search!=='string'||v.facilityFilter.search.length>100||typeof v.facilityFilter.type!=='string'||v.facilityFilter.type.length>80||!['all','blue','red','neutral'].includes(v.facilityFilter.team))fail('施設フィルターが不正です。');if(!['briefing','logistics','tactical','mapedit','waveform','comms','status','cic','support','weapons','damage','aviation','facilities','settings','help'].includes(v.screen)||typeof v.consoleRadarId!=='string'||!['all','selected'].includes(v.consoleFilter)||!Number.isInteger(v.consolePage)||v.consolePage<0||v.consolePage>127||typeof v.linkedUnit!=='string')fail('画面の表示設定が不正です。');}if(v?.layers){v.layers.facilities??=true;v.layers.hp??=true;v.layers.quantity??=v.layers.hp;v.layers.echelon??=true;}if(!v||!['map','radar'].includes(v.mode)||!['wide','square'].includes(v.aspect)||!finite(v.zoom,1,4)||!v.center||!finite(v.center.x,0,1000)||!finite(v.center.y,0,625)||![0,64,128,256].includes(v.pixel)||!v.layers||['units','names','labels','terrain','grid','routes','ranges','facilities','hp','quantity','echelon'].some(k=>typeof v.layers[k]!=='boolean')||typeof v.radarHide!=='boolean'||![4,8,12].includes(v.radarTrail))fail('表示設定が不正です。');
 return r;
}
export function replayFrame(r,frame){return r.frames[frame].map((v,i)=>({id:r.ids[i],...(r.weaponFrames?{weaponStates:copy(r.weaponFrames[frame][i])}:{}),x:v[0],y:v[1],hp:v[2],maxHp:v[3],personnel:v[4],attack:v[5],status:r.strings[v[6]],reason:r.strings[v[7]],target:r.strings[v[8]],mergedInto:r.strings[v[9]],retreat:!!(v[10]&1),repair:!!(v[10]&2),spent:!!(v[10]&4),recovered:!!(v[10]&8),recoveredCount:v[11]??0,recoveredAt:v[12]??0,...(r.replayVersion===3?{fuel:v[13],ammo:v[14],food:v[15]}:{})}));}
