import {deliveryConnections} from './deliveries.mjs';
import {rasterMap} from './map-raster.mjs';
import {mapGlyph} from './cartography-icons.mjs';
import {FACILITY_TYPES,FACILITY_LINE_TYPES} from './facilities.mjs';
import {facilityState} from './facility-state.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function terrainRects(p,colors){const raster=rasterMap(p,colors);if(raster)return raster;const cols=p.terrainCols||30,rows=p.terrainRows||20,out=[];for(let y=0;y<rows;y++){let start=0;while(start<cols){const t=p.terrain[y*cols+start];let end=start+1;while(end<cols&&p.terrain[y*cols+end]===t)end++;out.push(`<rect x="${start*1000/cols}" y="${y*625/rows}" width="${(end-start)*1000/cols+.15}" height="${625/rows+.15}" fill="${colors[t].color}" opacity=".85"/>`);start=end;}}return out.join('');}
export function facilityMarkup(p,{radar=false,frame=0}={}){return deliveryConnections(p,radar)+(p.facilities||[]).map((f,index)=>{
 const state=facilityState(p,f,frame*(p.secondsPerFrame??60)),color=!state.operational?'#655f59':radar?'#639d7d':f.team==='red'?'#d4907a':f.team==='blue'?'#83b9cf':'#d6c58c',r=f.radiusKm*(p.facilityScale||1);let x=f.points[0].x,y=f.points[0].y*.625,shape;
 if(FACILITY_LINE_TYPES.includes(f.type)){
  const points=f.points.map(v=>`${v.x},${v.y*.625}`).join(' '),width=Math.max(3,r*2/p.heightKm*625);
  shape=`<polyline points="${points}" fill="none" stroke="${radar?'#0d2920':'#151c19'}" stroke-width="${width+4}"/><polyline data-line-type="${f.type}" points="${points}" fill="none" stroke="${color}" stroke-width="${f.type==='railway'?2:width}" ${f.type==='trench'?'stroke-dasharray="12 3"':''}/>`;
  if(['railway','rail_bridge'].includes(f.type))shape+=`<polyline points="${points}" fill="none" stroke="${color}" stroke-width="${width+5}" stroke-dasharray="1 7"/>`;
  if(['road','road_bridge'].includes(f.type))shape+=`<polyline points="${points}" fill="none" stroke="#d8d9bd" stroke-width="1" stroke-dasharray="8 5" opacity=".65"/>`;
  if(['road_bridge','rail_bridge','pier','seaplane_ramp'].includes(f.type)){const a=f.points[0],b=f.points.at(-1),dx=b.x-a.x,dy=(b.y-a.y)*.625,l=Math.hypot(dx,dy)||1,nx=-dy/l*(width/2+3),ny=dx/l*(width/2+3);shape+=`<path data-bridge-ends="${f.type}" d="M${a.x-nx} ${a.y*.625-ny}L${a.x+nx} ${a.y*.625+ny}M${b.x-nx} ${b.y*.625-ny}L${b.x+nx} ${b.y*.625+ny}" stroke="${color}" stroke-width="2"/>`;}
  if(f.type==='runway_strip')shape=`<polyline data-line-type="runway_strip" points="${points}" fill="none" stroke="${radar?'#224a3a':'#454e4b'}" stroke-width="${Math.max(5,width)}"/><polyline points="${points}" fill="none" stroke="${color}" stroke-width="1" stroke-dasharray="5 4"/>`;
  if(f.type==='waterway')shape=`<polyline data-line-type="waterway" points="${points}" fill="none" stroke="${radar?'#306752':'#497f90'}" stroke-width="${width}"/>`;
  x=(f.points[0].x+f.points.at(-1).x)/2;y=(f.points[0].y+f.points.at(-1).y)*.3125;
 }else if(f.footprint==='rectangle'&&f.type!=='city'){const a=f.points[0],b=f.points[1],left=Math.min(a.x,b.x),top=Math.min(a.y,b.y)*.625,w=Math.abs(a.x-b.x),h=Math.abs(a.y-b.y)*.625;x=left+w/2;y=top+h/2;shape=`<rect data-building="${f.type}" x="${left}" y="${top}" width="${w}" height="${h}" fill="${radar?'#28563e':'#617263'}" fill-opacity=".65" stroke="${color}" stroke-width="1"/><path d="M${left} ${top}L${left+w} ${top+h}M${left+w} ${top}L${left} ${top+h}" stroke="${color}" stroke-width=".4" opacity=".4"/>`;}else if(f.type==='city'){
  const a=f.points[0],b=f.points[1]||{x:a.x+r/p.widthKm*1000,y:a.y+r/p.heightKm*1000},left=f.points.length===2?Math.min(a.x,b.x):a.x-r/p.widthKm*1000,top=f.points.length===2?Math.min(a.y,b.y)*.625:(a.y-r/p.heightKm*1000)*.625,w=f.points.length===2?Math.abs(a.x-b.x):2*r/p.widthKm*1000,h=f.points.length===2?Math.abs(a.y-b.y)*.625:2*r/p.heightKm*625,stepX=Math.max(4,(f.blockKm||.2)/p.widthKm*1000),stepY=Math.max(3,(f.blockKm||.2)/p.heightKm*625),id='city-block-'+index;
  x=left+w/2;y=top+h/2;shape=`<defs><pattern id="${id}" width="${stepX}" height="${stepY}" patternUnits="userSpaceOnUse"><rect x="1" y="1" width="${stepX*.65}" height="${stepY*.65}" fill="${radar?'#416e55':'#8f9684'}" stroke="${color}" stroke-width=".5"/></pattern></defs><rect data-city-area="true" x="${left}" y="${top}" width="${w}" height="${h}" fill="url(#${id})" stroke="${color}" stroke-width="1"/>`;
 }else{
  const rx=r/p.widthKm*1000,ry=r/p.heightKm*625;shape=`<ellipse cx="${x}" cy="${y}" rx="${rx}" ry="${ry}" fill="${color}" fill-opacity="${radar?.04:.1}" stroke="${color}" stroke-dasharray="${f.type==='minefield'?'3 4':'none'}"/>`;
 }
 shape+=`<g transform="translate(${x} ${y}) scale(${p.facilityIconScale??1})"><rect x="-14" y="-14" width="28" height="28" rx="2" fill="${radar?'#0b211a':'#142824'}" opacity=".92"/>${mapGlyph(f.type,color)}<text y="25" fill="${color}" font-size="10" text-anchor="middle" stroke="#12241f" stroke-width="2" paint-order="stroke">${esc((f.name||FACILITY_TYPES[f.type])+(state.operational?'':' / 停止'))}</text></g>`;
 return `<g data-facility="${esc(f.id)}" style="cursor:pointer"><title>${esc(f.name||FACILITY_TYPES[f.type])} / ${state.hp.toFixed(0)} / ${state.status}</title>${shape}</g>`;
 }).join('');}
export function resizeTerrain(p,cols){if(p.terrainLayers?.length)throw Error('描画レイヤーがある地図の解像度は地図編集画面で変更してください。');const oldHeights=p.elevation;const oc=p.terrainCols||30,orr=p.terrainRows||20;if(![30,60,120].includes(cols))throw new Error('解像度が不正です。');const oldCols=p.terrainCols||30,oldRows=p.terrainRows||20,rows=cols*2/3,old=p.terrain;p.terrain=Array.from({length:cols*rows},(_,i)=>old[Math.min(oldRows-1,Math.floor(Math.floor(i/cols)*oldRows/rows))*oldCols+Math.min(oldCols-1,Math.floor((i%cols)*oldCols/cols))]);p.elevation=Array.from({length:cols*rows},(_,i)=>oldHeights?.[Math.min(orr-1,Math.floor(Math.floor(i/cols)*orr/rows))*oc+Math.min(oc-1,Math.floor(i%cols*oc/cols))]??0);p.terrainCols=cols;p.terrainRows=rows;}

// Cell edges are drawn once; coastlines are stronger than internal terrain edges.
export function radarTerrainBoundaries(p){const raster=rasterMap(p,{}, {radar:true});if(raster)return `<g data-radar-terrain="true" pointer-events="none">${raster}</g>`;const cols=p.terrainCols||30,rows=p.terrainRows||20,coast=[],inland=[],w=1000/cols,h=625/rows;const edge=(a,b,path)=>{if(a!==b)(a==='water'||b==='water'?coast:inland).push(path);};for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const i=y*cols+x,a=p.terrain[i];if(x+1<cols)edge(a,p.terrain[i+1],`M${(x+1)*w} ${y*h}v${h}`);if(y+1<rows)edge(a,p.terrain[i+cols],`M${x*w} ${(y+1)*h}h${w}`);}return `<g data-radar-terrain="true" fill="none" pointer-events="none"><path d="${inland.join('')}" stroke="#578369" stroke-width=".65" opacity=".28"/><path d="${coast.join('')}" stroke="#80b394" stroke-width="1" opacity=".6"/></g>`;}
