export const MOUNT_POSITIONS={bow:'艦首',stern:'艦尾',port:'左舷',starboard:'右舷',center:'中央'};
export const CELL_STATES={loaded:'装填',empty:'空',reserved:'保留',fault:'故障',disabled:'使用不能'};
export const CELL_LABELS={...CELL_STATES,firing:'使用中',reloading:'再装填中'};
export const WEAPON_KINDS={gun:'主砲',vls:'VLS',launcher:'ミサイル発射筒',torpedo:'魚雷発射管',ciws:'CIWS',laser:'レーザー'};
export const WEAPON_VARIANTS={gun_quad:['gun','四連装砲'],gun_autocannon:['gun','単装機関砲'],launcher_twin:['launcher','連装発射筒'],launcher_quad:['launcher','四連装発射筒'],torpedo_twin:['torpedo','連装魚雷発射管'],torpedo_quint:['torpedo','五連装魚雷発射管'],gun_single:['gun','単装砲'],gun_twin:['gun','連装砲'],gun_triple:['gun','三連装砲'],vls_square:['vls','角形セルVLS'],vls_module:['vls','モジュールVLS'],launcher_box:['launcher','箱形発射筒'],launcher_canister:['launcher','円筒形発射筒'],torpedo_triple:['torpedo','三連装発射管'],torpedo_quad:['torpedo','四連装発射管'],ciws_gatling:['ciws','多銃身CIWS'],ciws_cannon:['ciws','機関砲CIWS'],laser_turret:['laser','指向性ターレット']};
export const AMMO_NAMES={shell:'砲弾',missile:'ミサイル',torpedo:'魚雷',round:'機関砲弾',energy:'照射チャージ'};
export const ammoFor=kind=>({gun:'shell',vls:'missile',launcher:'missile',torpedo:'torpedo',ciws:'round',laser:'energy'})[kind];
export function weaponGlyph(kind){return `<svg viewBox="0 0 80 48" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2">${({gun:'<path d="M10 38H64L59 22H27L18 30ZM45 22L69 8M49 25L73 11"/><path d="M20 39V44H56V39"/>',vls:Array.from({length:16},(_,i)=>`<rect x="${10+i%4*15}" y="${4+Math.floor(i/4)*10}" width="12" height="7"/>`).join(''),launcher:'<path d="M10 37H65M25 36L14 18 56 4 67 22ZM22 26L63 12M35 34L26 14"/>',torpedo:'<rect x="8" y="16" width="62" height="20" rx="8"/><path d="M12 23H65M12 29H65M28 36V43H50V36"/>',ciws:'<path d="M20 40H60V24H49V8H31V24H20ZM49 28H77M49 32H77M49 36H77"/>',laser:'<path d="M18 42H61V31H18ZM28 31L20 16 41 6 53 24Z"/><path d="M51 17L75 7M54 22L78 17"/>'})[kind]}</svg>`;}
export function newMount(hostId,variant,id){const [kind,name]=WEAPON_VARIANTS[variant]||WEAPON_VARIANTS.gun_single;return{id,hostId,kind,variant,name,ammoName:AMMO_NAMES[ammoFor(kind)],status:'ready',rows:4,cols:4,stock:kind==='vls'?16:100,damage:10,range:10,cells:kind==='vls'?Array(16).fill('loaded'):[],events:[],position:'center',group:'',reserve:-1,supplyId:'',fireSeconds:0,reloadSeconds:0,cellAmmo:kind==='vls'?Array.from({length:16},()=>({name:'ミサイル',type:'missile'})):[]};}
export function resizeCells(m,rows,cols){if(!Number.isInteger(rows)||!Number.isInteger(cols)||rows<1||cols<1||rows>16||cols>16)throw Error('行・列は1〜16です。');if(m.events.length)throw Error('予約を削除してからセル構成を変更してください。');const next=Array(rows*cols).fill('empty');for(let y=0;y<Math.min(rows,m.rows);y++)for(let x=0;x<Math.min(cols,m.cols);x++)next[y*cols+x]=m.cells[y*m.cols+x];const ammo=Array.from({length:rows*cols},()=>({name:m.ammoName,type:'missile'}));for(let y=0;y<Math.min(rows,m.rows);y++)for(let x=0;x<Math.min(cols,m.cols);x++)ammo[y*cols+x]={...(m.cellAmmo?.[y*m.cols+x]||{name:m.ammoName,type:'missile'})};m.cellAmmo=ammo;m.rows=rows;m.cols=cols;m.cells=next;m.stock=next.filter(c=>c==='loaded').length;}
export function validateWeapons(p){p.weaponControlEnabled??=false;p.mounts??=[];if(typeof p.weaponControlEnabled!=='boolean'||!Array.isArray(p.mounts)||p.mounts.length>128)throw Error('武装管理設定が不正です。');const ids=new Set(),num=(x,a,b)=>typeof x==='number'&&Number.isFinite(x)&&x>=a&&x<=b;for(const m of p.mounts){if(!m)throw Error('武装が不正です。');m.position??='center';m.group??='';m.reserve??=-1;m.fireSeconds??=0;m.reloadSeconds??=0;if(![m.fireSeconds,m.reloadSeconds].every(v=>Number.isInteger(v)&&v>=0&&v<=3600))throw Error('使用・再装填時間は0〜3600秒です。');m.supplyId??='';if(typeof m.supplyId!=='string'||m.supplyId&&!p.facilities.some(f=>f.id===m.supplyId))throw Error('再装填元の施設がありません。');m.cellAmmo??=(m.cells||[]).map(()=>({name:m.ammoName,type:'missile'}));if(!Object.hasOwn(MOUNT_POSITIONS,m.position)||typeof m.group!=='string'||m.group.length>40||!Number.isInteger(m.reserve)||m.reserve< -1||m.reserve>100000||!Array.isArray(m.cellAmmo)||m.cellAmmo.length!==(m.kind==='vls'?m.cells?.length:0)||m.cellAmmo.some(a=>!a||typeof a.name!=='string'||a.name.length>60||!Object.hasOwn(AMMO_NAMES,a.type)))throw Error('武装の配置・予備弾・セル情報が不正です。');if(!m||typeof m.id!=='string'||m.id.length>40||!/^[-_a-zA-Z0-9]+$/.test(m.id)||ids.has(m.id)||!p.units.some(u=>u.id===m.hostId)||!Object.hasOwn(WEAPON_KINDS,m.kind)||WEAPON_VARIANTS[m.variant]?.[0]!==m.kind||typeof m.name!=='string'||m.name.length>60||typeof m.ammoName!=='string'||m.ammoName.length>60||!['ready','safe','fault'].includes(m.status)||!Number.isInteger(m.stock)||!num(m.stock,0,100000)||!num(m.damage,0,10000)||!num(m.range,0,1000)||!Array.isArray(m.cells)||m.cells.length>256||m.cells.some(c=>!Object.hasOwn(CELL_STATES,c))||m.kind!=='vls'&&m.cells.length!==0||!Array.isArray(m.events)||m.events.length>100)throw Error('武装の名称・母体・在庫・設定が不正です。');ids.add(m.id);if(m.kind==='vls'&&(!Number.isInteger(m.rows)||!Number.isInteger(m.cols)||!num(m.rows,1,16)||!num(m.cols,1,16)||!Array.isArray(m.cells)||m.cells.length!==m.rows*m.cols||m.cells.some(c=>!Object.hasOwn(CELL_STATES,c))))throw Error('VLSセルの構成が不正です。');const times=new Set();for(const e of m.events){e.cellIndices??=[];if(!Array.isArray(e.cellIndices)||new Set(e.cellIndices).size!==e.cellIndices.length||e.cellIndices.some(i=>!Number.isInteger(i)||i<0||i>=m.cells.length)||e.cellIndices.length&&(m.kind!=='vls'||!['fire','reload'].includes(e.action)||e.cellIndices.length!==e.count))throw Error('セル指定は重複なしで数量と一致させてください。');if(!Number.isInteger(e.at)||e.at<0||e.at>p.duration||times.has(e.at)||!['fire','reload','safe','ready','fault'].includes(e.action)||!Number.isInteger(e.count)||e.count<1||e.count>100000||typeof e.target!=='string'||e.action==='fire'&&!p.units.some(u=>u.id===e.target))throw Error('武装予約が不正です。');times.add(e.at);}}return p;}
export function initialWeaponStates(p,hostId){return Object.fromEntries((p.mounts||[]).filter(m=>m.hostId===hostId).map(m=>[m.id,{stock:m.kind==='vls'?m.cells.filter(c=>c==='loaded').length:m.stock,status:m.status,reserve:m.reserve??-1,cells:[...m.cells],result:'未実行',target:''}]));}
// Fixed-time, abstract game damage only. No real fire-control solution, interception or physical ballistics.
export function weaponStep(p,units,old,next,damage,time,canTarget,distance,emit,supply=()=>0){
 if(!p.weaponControlEnabled)return;const by=new Map(units.map((u,i)=>[u.id,i]));
 for(const m of [...p.mounts].sort((a,b)=>a.id<b.id?-1:1)){
  const i=by.get(m.hostId),u=units[i],s=old[i],n=next[i];if(!n.weaponStates)n.weaponStates=initialWeaponStates(p,u.id);const w=n.weaponStates[m.id];
  const stopped=s.hp<=0||s.spent||s.mergedInto||s.recovered||time<u.start*p.secondsPerFrame;
  if(w.activity&&w.activity!=='idle'&&(time>=w.busyUntil||stopped)){
   const reload=w.activity==='reloading';for(const k of w.pendingCells||[])w.cells[k]=reload&&!stopped?'loaded':'empty';
   if(reload&&!stopped)w.stock+=w.pendingAmount||0;
   w.activity='idle';w.busyUntil=0;w.pendingCells=[];w.pendingAmount=0;w.result=stopped?'母体停止・作業中止':reload?'再装填完了':'使用完了';
  }
  const e=m.events.find(e=>e.at*p.secondsPerFrame===time);if(!e)continue;if(stopped){w.result='母体停止・中止';continue;}
  if(['safe','ready','fault'].includes(e.action)){w.status=e.action;w.result='状態変更';continue;}
  if(w.activity&&w.activity!=='idle'){w.result='作業中・予約中止';emit(time,n,m.name+'：作業中のため予約中止','武装');continue;}
  const selected=e.cellIndices?.length?e.cellIndices:null;
  if(e.action==='reload'){
   const available=m.kind==='vls'?(selected||w.cells.map((_,i)=>i)).filter(i=>w.cells[i]==='empty'):[];
   if(w.status==='fault'||selected&&available.length!==selected.length){w.result='再装填条件不成立';continue;}
   const needed=m.kind==='vls'?Math.min(e.count,available.length):Math.min(e.count,100000-w.stock),amount=m.supplyId?supply(m,u,s,needed):w.reserve<0?needed:Math.min(needed,w.reserve);
   if(!m.supplyId&&w.reserve>=0)w.reserve-=amount;const indices=available.slice(0,amount);
   if(amount&&(m.reloadSeconds||0)>0){w.activity='reloading';w.busyUntil=time+m.reloadSeconds;w.pendingCells=indices;w.pendingAmount=amount;for(const k of indices)w.cells[k]='reloading';w.result='再装填中 '+amount;}
   else{for(const k of indices)w.cells[k]='loaded';w.stock+=amount;w.result=amount?'再装填 '+amount:'再装填できません';}
   emit(time,n,m.name+'：'+w.result,'武装');continue;
  }
  const j=by.get(e.target),target=old[j],targetUnit=units[j],available=m.kind==='vls'?(selected||w.cells.map((_,i)=>i)).filter(i=>w.cells[i]==='loaded'):[];
  if(w.status!=='ready'||e.count>w.stock||m.kind==='vls'&&available.length<e.count||!target||target.hp<=0||target.spent||target.recovered||target.mergedInto||time<targetUnit.start*p.secondsPerFrame||u.team==='neutral'||targetUnit.team==='neutral'||u.team===targetUnit.team||!canTarget(p,u,targetUnit)||distance(p,s,target)>m.range){w.result='条件不成立・中止';emit(time,n,m.name+'：予約を実行できません','武装');continue;}
  w.stock-=e.count;const indices=available.slice(0,e.count),timed=(m.fireSeconds||0)>0;for(const k of indices)w.cells[k]=timed?'firing':'empty';
  if(timed){w.activity='firing';w.busyUntil=time+m.fireSeconds;w.pendingCells=indices;w.pendingAmount=0;}
  w.target=e.target;w.result=timed?'使用中':'実行済';damage[j]+=m.damage*e.count*(p.damageScale??.05)*100/(100+(targetUnit.defense||0));emit(time,n,m.name+' / '+e.count+' 単位を実行','武装');
 }
}
export function ammoGlyph(kind){const shape=kind==='energy'?'<path d="M25 2L10 19H21L16 35 34 13H23Z"/>':kind==='torpedo'?'<path d="M7 19L14 12H39V26H14ZM14 12L8 7M14 26L8 31M32 12V26"/>':kind==='missile'?'<path d="M6 19L20 13H39V25H20ZM20 13L24 5V13M20 25L24 33V25"/>':'<path d="M16 30V13L23 3 30 13V30ZM16 24H30"/>';return `<svg viewBox="0 0 46 38" width="30" height="24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2">${shape}</svg>`;}

export function copyWeaponOrders(p,sourceId,targetIds,offset=0,move=false){
 const source=p.mounts.find(m=>m.id===sourceId);if(!source||!Number.isInteger(offset)||!targetIds.length)throw Error('コピー元・先・frame差を確認してください。');
 const ids=[...new Set(targetIds)];if(ids.includes(sourceId))throw Error('コピー元をコピー先から外してください。');
 const updates=ids.map(id=>{const target=p.mounts.find(m=>m.id===id);if(!target)throw Error('コピー先の武装がありません。');const events=source.events.map(e=>({...e,cellIndices:[...(e.cellIndices||[])],at:e.at+offset}));if(events.some(e=>e.cellIndices.length&&(target.kind!=='vls'||e.cellIndices.some(i=>i>=target.cells.length))))throw Error('コピー先のセル構成と指定セルが一致しません。');if(events.some(e=>e.at<0||e.at>p.duration||target.events.some(t=>t.at===e.at))||events.length+target.events.length>100)throw Error('予約が重複するか、frameまたは件数の上限を超えます。');return{target,events};});
 for(const {target,events} of updates)target.events.push(...events),target.events.sort((a,b)=>a.at-b.at);if(move)source.events=[];
}

export const weaponStateLabel=w=>w.status==='fault'?'故障':w.activity==='reloading'?'再装填中':w.activity==='firing'?'使用中':({ready:'準備',safe:'安全',fault:'故障'}[w.status]||'待機');
