"use strict";
document.addEventListener("DOMContentLoaded",async()=>{
 const C=MFDCOCountry,X=MFDCOCountryV11,Cloud=MFDCOCountryCloud,root=document.getElementById("market-app");
 if(!root)return;
 const [countries,prefs,u,priority]=await Promise.all([Cloud.marketSnapshots(),Cloud.getCountryPreferences(),Cloud.user(),Cloud.marketPriorityMap()]);
 const now=new Date(),initialHour=X.hourKey(now),floorHour=d=>new Date(Math.floor(d.getTime()/3600000)*3600000),contextFor=c=>{const p=priority[c.id]||{};return {loggedIn:false,isMain:!!p.isMain,isActive:!!p.isActive}},stateAt=(c,date)=>X.simulatedMarket(c,date,contextFor(c));
 const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
 function syntheticHistory(hours=168){
  const end=floorHour(now),times=[];for(let i=hours-1;i>=0;i--)times.push(new Date(end.getTime()-i*3600000));
  const running=new Map();for(const c of countries){const f=c.advanced?.finance||{},cp=new Map();for(const co of C.arr(c.companies)){const base=C.num(co.baseStockPrice,0);if(base>0)cp.set(String(co.id||co.name),base)}running.set(c.id,{stock:C.num(f.baseStockIndex,0)||10000,fx:C.num(f.baseFxPerUsd,0)||null,companyAverage:1000,companyPrices:cp})}
  let worldIndex=1000;const out=[];
  for(const at of times){const states=[];for(const c of countries){const m=stateAt(c,at);if(!m.enabled)continue;const run=running.get(c.id),companies=C.arr(c.companies),companyRows=[];run.stock*=1+m.pct/100;if(run.fx)run.fx*=1+C.num(m.fxPct,0)/100;const moves=[];for(const co of companies){const move=X.companyMove(c,co,at);moves.push(move);const key=String(co.id||co.name),base=C.num(co.baseStockPrice,0);let price=run.companyPrices.get(key);if(price==null&&base>0)price=base;if(price!=null){price*=1+move/100;run.companyPrices.set(key,price)}companyRows.push({company:co,move,price})}const compMove=moves.length?avg(moves):0;if(moves.length)run.companyAverage*=1+compMove/100;states.push({c,m:{...m,stock:run.stock,fx:run.fx,companyAverage:moves.length?run.companyAverage:null,companyAverageMove:compMove},companies:companyRows})}const worldReturn=states.length?avg(states.map(x=>x.m.pct)):0;worldIndex*=1+worldReturn/100;out.push({at,worldReturn,worldIndex,states})}
  return out;
 }
 const synthetic=syntheticHistory(168),latest=synthetic.at(-1)||{states:[],worldReturn:0,worldIndex:1000},previous=synthetic.at(-2)||latest,regime=X.marketRegime(now);
 function backfillPayload(points){const rows=[];for(const point of points){for(const x of point.states){rows.push({country_id:x.c.id,captured_hour:point.at.toISOString(),market_date:x.m.date,market_month:x.m.month,market_hour:x.m.hour,change_pct:x.m.pct,fx_value:x.m.fx,stock_value:x.m.stock,world_average_pct:point.worldReturn,themes:{version:"hourly-v17.3",regime:{id:x.m.regime?.id,eventAt:x.m.regime?.eventAt,nextEventAt:x.m.regime?.nextEventAt,strong:x.m.regime?.strong,weak:x.m.regime?.weak,resourceStrong:x.m.regime?.resourceStrong}}})}}return rows}
 let backfillNote="市場は閲覧者がいない時間も、時刻を基準に1時間単位で決定論的に進行します。";
 if(u&&Cloud.ready()){try{const maxHours=Math.min(168,Math.max(24,Math.floor(6000/Math.max(1,countries.length)))),key=`mfdco_market_backfill_v17_3_${X.hourKey(now)}`;if(localStorage.getItem("mfdco_market_backfill_v17_3")!==key){const inserted=await Cloud.backfillMarketHistory(backfillPayload(synthetic.slice(-maxHours)));localStorage.setItem("mfdco_market_backfill_v17_3",key);backfillNote=`ログインを検出し、直近${maxHours}時間の市場履歴を補完・更新しました（処理 ${inserted} 行）。`}else backfillNote="この時間の履歴補完は完了しています。"}catch(e){console.warn("MARKET BACKFILL",e);backfillNote=`履歴保存は失敗しましたが、市場表示は継続します: ${e.message||e}`}}
 const hist=await Cloud.marketHistory(null,1800);let selectedId=(prefs.activeCountryId&&countries.some(c=>c.id===prefs.activeCountryId))?prefs.activeCountryId:(latest.states[0]?.c.id||countries[0]?.id||"");
 const stateFor=(point,id)=>point.states.find(x=>x.c.id===id),pct=(a,b)=>a?((b/a)-1)*100:0,fmtTime=d=>`${String(d.getMonth()+1).padStart(2,"0")}/${String(d.getDate()).padStart(2,"0")} ${String(d.getHours()).padStart(2,"0")}:00`;
 function chartData(){const first=synthetic.find(p=>stateFor(p,selectedId)),firstState=first?stateFor(first,selectedId):null,baseStock=firstState?.m.stock||1,baseComp=firstState?.m.companyAverage||null,baseWorld=first?.worldIndex||1;return synthetic.map(point=>{const st=stateFor(point,selectedId);return {at:point.at,country:st?pct(baseStock,st.m.stock):0,companies:baseComp&&st?.m.companyAverage?pct(baseComp,st.m.companyAverage):null,world:pct(baseWorld,point.worldIndex)}})}
 function chartSvg(){const data=chartData();if(!data.length)return '<div class="empty">チャートデータがありません。</div>';const w=980,h=320,padL=58,padR=18,padT=18,padB=44,vals=data.flatMap(x=>[x.country,x.world,x.companies??0,0]),min0=Math.min(...vals),max0=Math.max(...vals),span=Math.max(.3,max0-min0),min=min0-span*.12,max=max0+span*.12,x=i=>padL+(w-padL-padR)*(i/(data.length-1||1)),y=v=>padT+(h-padT-padB)*(1-(v-min)/(max-min||1)),path=k=>data.filter(d=>d[k]!=null).map((d,i,a)=>`${i?"L":"M"}${x(data.indexOf(d)).toFixed(2)} ${y(d[k]).toFixed(2)}`).join(" ");let grid="",labels="";for(let i=0;i<5;i++){const v=max-(max-min)*i/4,yy=y(v);grid+=`<line x1="${padL}" y1="${yy}" x2="${w-padR}" y2="${yy}" class="market-chart-grid"/>`;labels+=`<text x="${padL-8}" y="${yy+4}" text-anchor="end" class="market-chart-label">${v.toFixed(2)}%</text>`}for(const i of [0,Math.floor((data.length-1)/2),data.length-1])labels+=`<text x="${x(i)}" y="${h-14}" text-anchor="middle" class="market-chart-label">${fmtTime(data[i].at)}</text>`;const selected=countries.find(c=>c.id===selectedId),avgName=selected?.advanced?.finance?.stockAverageName||"主要企業平均";return `<div class="market-chart-wrap"><svg class="market-chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="直近168時間の市場パフォーマンス"><line x1="${padL}" y1="${y(0)}" x2="${w-padR}" y2="${y(0)}" class="market-chart-zero"/>${grid}${labels}<path d="${path("world")}" class="market-chart-line world"/><path d="${path("country")}" class="market-chart-line country"/>${data.some(d=>d.companies!=null)?`<path d="${path("companies")}" class="market-chart-line companies"/>`:""}</svg><div class="market-chart-legend"><span><i class="world"></i>世界総合</span><span><i class="country"></i>${C.esc(selected?.advanced?.finance?.stockIndexName||selected?.name||"国家指数")}</span>${data.some(d=>d.companies!=null)?`<span><i class="companies"></i>${C.esc(avgName)}</span>`:""}<span class="fine">基準時=0% / 直近168時間</span></div></div>`}
 function ohlc(prevValue,currentValue,movePct){if(!prevValue||!currentValue)return null;const spread=Math.max(.0005,Math.abs(movePct)/100*.28+.0004),hi=Math.max(prevValue,currentValue)*(1+spread),lo=Math.min(prevValue,currentValue)*(1-spread);return {open:prevValue,high:hi,low:lo,close:currentValue}}
 function marketBoard(){const cur=stateFor(latest,selectedId),prev=stateFor(previous,selectedId);if(!cur)return '<div class="empty">選択国家の市場データがありません。</div>';const f=cur.c.advanced?.finance||{},stock=ohlc(prev?.m.stock,cur.m.stock,cur.m.pct),fx=ohlc(prev?.m.fx,cur.m.fx,cur.m.fxPct),avgName=f.stockAverageName||"主要企業平均";return `<div class="market-board-grid"><div class="market-board"><small>${C.esc(f.stockIndexName||"総合株価指数")}</small><strong>${C.fmtNum(cur.m.stock,{maximumFractionDigits:2})}</strong><span class="${cur.m.pct>=0?"market-up":"market-down"}">${cur.m.pct>=0?"+":""}${cur.m.pct.toFixed(3)}% / 1h</span>${stock?`<em>O ${C.fmtNum(stock.open,{maximumFractionDigits:2})} / H ${C.fmtNum(stock.high,{maximumFractionDigits:2})} / L ${C.fmtNum(stock.low,{maximumFractionDigits:2})}</em>`:""}</div><div class="market-board"><small>${C.esc(avgName)}</small><strong>${cur.m.companyAverage?C.fmtNum(cur.m.companyAverage,{maximumFractionDigits:2}):"—"}</strong><span class="${cur.m.companyAverageMove>=0?"market-up":"market-down"}">${cur.m.companyAverage!=null?(cur.m.companyAverageMove>=0?"+":"")+cur.m.companyAverageMove.toFixed(3)+"% / 1h":"企業株価未設定"}</span><em>等加重の企業株価平均指数</em></div><div class="market-board"><small>FX / 1 USD = ${C.esc(cur.c.economy?.currencyCode||"通貨")}</small><strong>${cur.m.fx?C.fmtNum(cur.m.fx,{maximumFractionDigits:6}):"—"}</strong><span class="${C.num(cur.m.fxPct)<=0?"market-up":"market-down"}">${cur.m.fx?`${cur.m.fxPct>=0?"+":""}${cur.m.fxPct.toFixed(4)}% / 1h`:"基準為替未設定"}</span>${fx?`<em>O ${C.fmtNum(fx.open,{maximumFractionDigits:6})} / H ${C.fmtNum(fx.high,{maximumFractionDigits:6})} / L ${C.fmtNum(fx.low,{maximumFractionDigits:6})}</em>`:""}</div><div class="market-board"><small>世界総合指数</small><strong>${C.fmtNum(latest.worldIndex,{maximumFractionDigits:2})}</strong><span class="${latest.worldReturn>=0?"market-up":"market-down"}">${latest.worldReturn>=0?"+":""}${latest.worldReturn.toFixed(3)}% / 1h</span><em>公開国家の等加重平均</em></div></div>`}
 function companyTable(){const cur=stateFor(latest,selectedId),prev=stateFor(previous,selectedId);if(!cur)return "";const prevMap=new Map((prev?.companies||[]).map(x=>[String(x.company.id||x.company.name),x]));const rows=cur.companies.filter(x=>x.company?.name);if(!rows.length)return '<div class="empty">主要企業が登録されていません。国家編集 → 産業・企業から企業と基準株価を追加できます。</div>';return `<div class="table-wrap"><table><thead><tr><th>銘柄</th><th>企業</th><th>株価</th><th>1時間</th><th>始値</th><th>高値</th><th>安値</th><th>時価総額</th></tr></thead><tbody>${rows.slice().sort((a,b)=>C.num(b.company.marketCap)-C.num(a.company.marketCap)).map(x=>{const key=String(x.company.id||x.company.name),pr=prevMap.get(key),ohl=ohlc(pr?.price,x.price,x.move);return `<tr><td>${C.esc(x.company.stockTicker||"—")}</td><td>${C.esc(x.company.name)}</td><td>${x.price?`$${C.fmtNum(x.price,{maximumFractionDigits:2})}`:"—"}</td><td class="${x.move>=0?"market-up":"market-down"}">${x.move>=0?"+":""}${x.move.toFixed(3)}%</td><td>${ohl?`$${C.fmtNum(ohl.open,{maximumFractionDigits:2})}`:"—"}</td><td>${ohl?`$${C.fmtNum(ohl.high,{maximumFractionDigits:2})}`:"—"}</td><td>${ohl?`$${C.fmtNum(ohl.low,{maximumFractionDigits:2})}`:"—"}</td><td>${C.num(x.company.marketCap)>0?C.fmtNum(x.company.marketCap,{notation:"compact",maximumFractionDigits:2})+" "+C.esc(x.company.financialUnit||""):"—"}</td></tr>`}).join("")}</tbody></table></div>`}
 function render(){const next=new Date(regime.nextEventAt);root.innerHTML=`<section class="card section-card"><div class="world-theme-grid"><div class="world-theme"><small>市場状態</small><strong>1時間更新</strong><span id="market-live-clock">閲覧者がいなくても時刻から再現</span></div><div class="world-theme good"><small>現在の強材料</small><strong>${C.esc(regime.strong.label)}</strong><span>資源: ${C.esc(regime.resourceStrong.label)}</span></div><div class="world-theme bad"><small>現在の弱材料</small><strong>${C.esc(regime.weak.label)}</strong><span>資源: ${C.esc(regime.resourceWeak.label)}</span></div><div class="world-theme"><small>材料更新予定</small><strong>${next.toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"})}</strong><span>3〜11時間程度の不規則間隔</span></div><div class="world-theme"><small>世界 1時間</small><strong>${latest.worldReturn>=0?"+":""}${latest.worldReturn.toFixed(3)}%</strong><span>${X.hourKey(now)}</span></div></div><p class="fine">日次・月次の変動要因は廃止しました。すべて1時間単位で計算し、通常時の値動きは小さく抑えています。${C.esc(backfillNote)}</p></section><section class="card section-card"><div class="section-head"><div><h2>マーケットボード</h2><p>指数・企業平均・為替を実市場に近い形式で表示します。</p></div><div class="field market-country-picker"><label>国家</label><select id="market-country" class="select">${countries.map(c=>`<option value="${c.id}" ${c.id===selectedId?"selected":""}>${C.esc(c.name)}</option>`).join("")}</select></div></div>${marketBoard()}</section><section class="card section-card"><div class="section-head"><div><h2>168時間パフォーマンス</h2><p>株価指数・企業平均・世界総合を同じ0%基準で比較します。</p></div></div>${chartSvg()}</section><section class="card section-card"><h2>企業株式</h2>${companyTable()}</section><section class="card section-card"><h2>保存済み履歴</h2>${hist.length?`<div class="table-wrap"><table><thead><tr><th>時刻</th><th>国家</th><th>1時間変動</th><th>世界平均</th><th>為替</th><th>株価指数</th></tr></thead><tbody>${hist.slice(0,300).map(h=>`<tr><td>${C.esc(String(h.captured_hour||"").replace("T"," ").slice(0,16))}</td><td>${C.esc(countries.find(c=>c.id===h.country_id)?.name||h.country_id)}</td><td>${C.fmtNum(h.change_pct,{maximumFractionDigits:4})}%</td><td>${h.world_average_pct==null?"—":C.fmtNum(h.world_average_pct,{maximumFractionDigits:4})+"%"}</td><td>${h.fx_value??"—"}</td><td>${h.stock_value??"—"}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">DB保存履歴はまだありません。表示用の過去値は時刻から再現されています。</div>'}</section>`;document.getElementById("market-country")?.addEventListener("change",e=>{selectedId=e.target.value;render()})}
 render();setInterval(()=>{const live=new Date(),el=document.getElementById("market-live-clock");if(el)el.textContent=`自動計算 ${live.toLocaleString("ja-JP")} / 次回は毎正時更新`;if(X.hourKey(live)!==initialHour)location.reload()},1000);
});
