"use strict";
document.addEventListener("DOMContentLoaded",async()=>{
const C=MFDCOCountry,V=MFDCOCountryV6,Cloud=MFDCOCountryCloud;let c=await V.load();let dirty=false;
const main=document.getElementById("editor-main"),nav=document.getElementById("editor-nav"),state=document.getElementById("save-state"),bottom=document.getElementById("bottom-state");
for(const id of ["preview-link","bottom-preview"])document.getElementById(id).href=`country.html?id=${encodeURIComponent(c.id)}`;document.getElementById("stats-link").href=`country-stats.html?id=${c.id}`;document.getElementById("wiki-link").href=`country-wiki.html?id=${c.id}`;
const sections=[
 ["basic","基本情報"],["media","国旗・画像・国歌"],["territory","主権・国土・EEZ"],["population","人口"],["government","政治・政府"],["administration","行政・法律"],["economy","経済・通貨"],["budget","年度予算"],["industry","産業・特産物"],["climate","気候・文化"],["companies","主要企業・政党"],["history","歴史・年表"],["military","軍事"],["posts","投稿・ニュース"],["systems","国家基盤"],["strength","国家力入力"]];
nav.innerHTML=sections.map(([id,n])=>`<a href="#sec-${id}">${n}</a>`).join("");
const card=(id,title,body,desc="")=>`<section id="sec-${id}" class="card section-card wiki-section"><div class="section-head"><div><h2>${title}</h2>${desc?`<p>${desc}</p>`:""}</div></div>${body}</section>`;
const input=(path,label,val,type="text",extra="")=>`<div class="field"><label>${label}</label><input class="input bind" data-path="${path}" type="${type}" value="${C.esc(val??"")}" ${extra}></div>`;
const ta=(path,label,val)=>`<div class="field full"><label>${label}</label><textarea class="textarea bind" data-path="${path}">${C.esc(val??"")}</textarea></div>`;
function render(){
 main.innerHTML=
 card("basic","基本情報",`<div class="form-grid">${input("name","正式国名",c.name)}${input("shortName","略称",c.shortName)}${input("englishName","英語名",c.englishName)}${input("code","国コード",c.code)}${input("capital.name","首都",c.capital.name)}${input("tags","タグ（カンマ区切り）",C.arr(c.tags).join(", "))}${ta("summary","概要",c.summary)}<div class="field"><label>公開状態</label><select class="select bind" data-path="isPublic"><option value="true" ${c.isPublic?"selected":""}>公開</option><option value="false" ${!c.isPublic?"selected":""}>非公開 / 下書き</option></select></div></div>`,`必須は国名程度です。時間をかけるほど詳細にできます。`)+
 card("media","国旗・画像・国歌",`<div class="form-grid three">${mediaField("flagKey","国旗","image/*")}${mediaField("coverKey","背景画像","image/*")}${mediaField("mapKey","地図画像","image/*")}${mediaField("capitalImageKey","首都画像","image/*")}${mediaField("anthemKey","国歌","audio/*")}</div>`)+
 card("territory","主権・国土・EEZ",`<div class="form-grid three">${input("sovereignty.status","主権状態",c.sovereignty.status)}${input("sovereignty.recognizedBy","承認状況",c.sovereignty.recognizedBy)}${input("territory.area","国土面積 km²",c.territory.area||c.area,"number")}${input("territory.landArea","陸地面積 km²",c.territory.landArea,"number")}${input("territory.waterArea","内水面積 km²",c.territory.waterArea,"number")}${input("sovereignty.territorialWatersKm","領海 幅 km",c.sovereignty.territorialWatersKm,"number")}${input("sovereignty.eezArea","EEZ km²",c.sovereignty.eezArea,"number")}${input("territory.coastlineKm","海岸線 km",c.territory.coastlineKm,"number")}</div>`)+
 card("population","人口",`<div class="form-grid three">${input("population","総人口",c.population,"number")}${input("populationYear","基準時点",c.populationYear)}${input("populationGroups.children","年少人口",c.populationGroups?.children||0,"number")}${input("populationGroups.working","生産年齢人口",c.populationGroups?.working||0,"number")}${input("populationGroups.elderly","老年人口",c.populationGroups?.elderly||0,"number")}</div>`)+
 card("government","政治・政府",`<div class="form-grid">${input("government.system","政体",c.government.system)}${input("government.headOfState","国家元首",c.government.headOfState)}${input("government.headOfGovernment","政府首班",c.government.headOfGovernment)}${input("government.legislature","立法府",c.government.legislature)}${input("government.judiciary","司法",c.government.judiciary)}${input("government.rulingParties","与党（カンマ区切り）",C.arr(c.government.rulingParties).join(", "))}</div>`)+
 card("administration","行政・法律",administrationHtml(),"大量になりやすい行政区・法律は表形式です。")+
 card("economy","経済・通貨",`<div class="form-grid three">${input("economy.gdp","名目GDP",c.economy.gdp,"number")}${input("economy.gdpYear","GDP基準年",c.economy.gdpYear)}${input("economy.gdpPerCapita","一人当たりGDP",c.economy.gdpPerCapita,"number")}${input("economy.currencyName","通貨名",c.economy.currencyName)}${input("economy.currencyCode","通貨コード",c.economy.currencyCode)}<div class="field"><label>通貨価値方式</label><select class="select bind" data-path="economy.currencyMode"><option value="USD" ${c.economy.currencyMode==="USD"?"selected":""}>米ドル基準</option><option value="JPY" ${c.economy.currencyMode==="JPY"?"selected":""}>日本円基準</option><option value="independent" ${c.economy.currencyMode==="independent"?"selected":""}>完全独立</option></select></div>${input("economy.currencyRate","1基準通貨あたり自国通貨",c.economy.currencyRate,"number","step=\"any\"")}${input("economy.growthRate","経済成長率 %",c.economy.growthRate,"number","step=\"any\"")}${input("economy.unemploymentRate","失業率 %",c.economy.unemploymentRate,"number","step=\"any\"")}${input("economy.inflationRate","物価上昇率 %",c.economy.inflationRate,"number","step=\"any\"")}${input("economy.debt","政府債務",c.economy.debt,"number")}</div><p class="help">完全独立を選ぶと現実通貨との換算を行いません。</p>`)+
 card("budget","年度予算",budgetHtml(),"歳入と歳出を分けて設定します。図表ページで自動円グラフ化できます。")+
 card("industry","産業・特産物",industryHtml())+
 card("climate","気候・文化",climateHtml())+
 card("companies","主要企業・政党",companiesHtml(),"ロゴは各項目の編集からファイル追加できます。")+
 card("history","歴史・年表",historyHtml(),"大量の出来事を想定し、プレビューは高さを抑えた表です。出来事は1件ずつ追加します。")+
 card("military","軍事",militaryHtml(),"軍種を追加し、その軍種ごとの人員・予算・指揮権を設定。部隊は表形式です。")+
 card("posts","投稿・ニュース",postsHtml(),"国家ページや全国家ニュースフィードへ掲載する時系列コンテンツです。")+
 card("systems","国家基盤",systemsHtml(),"教育・医療・税制・交通・通信・電力・金融・警察など、国家を維持する制度を追加します。")+
 card("strength","国家力の補助入力",strengthHtml(),"総合点は上限なし。100以上＝先進国、150以上＝超大国を大まかな目安として表示します。数値は世界観に応じて調整可能です。")+
 `<div style="height:60px"></div>`;
 bind();
}
function mediaField(key,label,accept){const current=c.media?.[key]||"";return `<div class="field"><label>${label}</label><input class="input media-input" data-key="${key}" type="file" accept="${accept}"><div class="fine">${current?"設定済み":"未設定"}</div><button type="button" class="btn ghost small media-clear" data-key="${key}">解除</button></div>`}
function administrationHtml(){return `<div class="toolbar"><button class="btn small" data-add="ministry">＋省庁</button><button class="btn small" data-add="law">＋法律</button><button class="btn small" data-add="region">＋行政区</button></div><h3>省庁</h3>${rowTable("ministries",c.administration.ministries,["名称","長","概要"])}<h3>法律</h3>${rowTable("laws",c.administration.laws,["法律名","制定年","状態","概要"])}<h3>行政区</h3>${rowTable("regions",c.administration.regions,["名称","庁所在地","人口","面積 km²","概要"])} `}
function budgetHtml(){return `<div class="form-grid">${input("budget.year","年度",c.budget.year)}</div><div class="split"><div><h3>歳入</h3><button class="btn small" data-add="revenue">＋歳入項目</button>${moneyRows("revenue",c.budget.revenue)}</div><div><h3>歳出</h3><button class="btn small" data-add="expenditure">＋歳出項目</button>${moneyRows("expenditure",c.budget.expenditure)}</div></div>`}
function moneyRows(k,rows){return `<div class="table-wrap"><table><thead><tr><th>項目</th><th>金額</th><th></th></tr></thead><tbody>${C.arr(rows).map((r,i)=>`<tr><td><input class="input arr-bind" data-array="budget.${k}" data-index="${i}" data-field="name" value="${C.esc(r.name)}"></td><td><input class="input arr-bind" data-array="budget.${k}" data-index="${i}" data-field="value" type="number" value="${r.value||0}"></td><td><button class="btn danger small arr-del" data-array="budget.${k}" data-index="${i}">削除</button></td></tr>`).join("")}</tbody></table></div>`}
function industryHtml(){return `<div class="form-grid"><div class="field"><label>主要産業（1行1項目・比率は任意）</label><textarea class="textarea special-lines" data-special="industries">${C.arr(c.industries).map(x=>`${x.name||x}:${x.share??""}`).join("\n")}</textarea></div><div class="field"><label>特産物・主要生産物</label><input id="product-custom" class="input" list="product-list" placeholder="候補から選択または自由入力"><datalist id="product-list">${V.PRODUCTS.map(x=>`<option value="${x}">`).join("")}</datalist><button type="button" class="btn small" data-add="product">追加</button><div class="toolbar">${C.arr(c.products).map((x,i)=>`<span class="pill">${C.esc(x)} <button class="arr-del" data-array="products" data-index="${i}" style="border:0;background:none">×</button></span>`).join("")}</div></div></div>`}
function climateHtml(){return `<div class="form-grid"><div class="field"><label>気候帯</label><select id="climate-choice" class="select"><option value="">選択</option>${V.option(V.CLIMATES)}</select><input id="climate-custom" class="input" placeholder="独自気候帯を入力"><button type="button" class="btn small" data-add="climate">追加</button><div class="toolbar">${C.arr(c.climate.zones).map((x,i)=>`<span class="pill">${C.esc(x)} <button class="climate-del" data-index="${i}" style="border:0;background:none">×</button></span>`).join("")}</div></div>${input("climate.avgTemp","平均気温・特徴",c.climate.avgTemp)}${input("climate.rainfall","降水量・降水特性",c.climate.rainfall)}${ta("climate.notes","気候・自然の説明",c.climate.notes)}${ta("culture.notes","文化概要",c.culture.notes)}</div>`}
function companiesHtml(){return `<div class="toolbar"><button class="btn small" data-add="company">＋主要企業</button><button class="btn small" data-add="party">＋政党</button></div><h3>主要企業</h3>${genericCards("companies",c.companies)}<h3>政党</h3>${genericCards("parties",c.parties)}`}
function genericCards(key,items){return C.arr(items).length?`<div class="table-wrap"><table><thead><tr><th>名称</th><th>分類</th><th>概要</th><th>ロゴ</th><th></th></tr></thead><tbody>${items.map((r,i)=>`<tr><td><input class="input arr-bind" data-array="${key}" data-index="${i}" data-field="name" value="${C.esc(r.name||"")}"></td><td><input class="input arr-bind" data-array="${key}" data-index="${i}" data-field="type" value="${C.esc(r.type||"")}"></td><td><input class="input arr-bind" data-array="${key}" data-index="${i}" data-field="summary" value="${C.esc(r.summary||"")}"></td><td><input type="file" class="row-media" data-array="${key}" data-index="${i}" data-field="logoKey" accept="image/*"></td><td><button class="btn danger small arr-del" data-array="${key}" data-index="${i}">削除</button></td></tr>`).join("")}</tbody></table></div>`:`<div class="empty">未登録</div>`}
function historyHtml(){const eras=C.arr(c.eras),events=C.arr(c.timeline).slice().sort((a,b)=>(a.year||999999)-(b.year||999999));return `<div class="form-grid"><div class="field"><label>現在の西暦（○年前計算の基準）</label><input class="input bind" data-path="chronology.currentGregorian" type="number" value="${c.chronology?.currentGregorian||new Date().getFullYear()}"></div></div><div class="toolbar"><button class="btn small" data-add="calendar">＋年号・紀年法</button><button class="btn small" data-add="era">＋時代区分</button><button class="btn small" data-add="event">＋出来事を1件追加</button></div><h3>年号・紀年法</h3>${calendarTable()}<h3>時代区分</h3>${rowTable("eras",eras,["時代名","開始年","終了年"])}<h3>現在の年表プレビュー</h3><div class="timeline-compact"><div class="table-wrap"><table class="timeline-table"><thead><tr><th>西暦</th><th>独自歴 / 年号</th><th>○年前</th><th>時代</th><th>出来事</th><th>概要</th></tr></thead><tbody>${events.map(e=>`<tr><td>${C.esc(e.date||e.year||"")}</td><td>${C.esc(calendarForYear(e.year))}</td><td>${e.year?C.esc(`${Math.max(0,Number(c.chronology?.currentGregorian||new Date().getFullYear())-Number(e.year))}年前`):""}</td><td>${C.esc(e.era||eraForYear(e.year))}</td><td><a href="country-history.html?id=${c.id}&event=${e.id}">${C.esc(e.title)}</a></td><td>${C.esc(e.summary||"")}</td></tr>`).join("")}</tbody></table></div></div><h3>出来事編集</h3>${timelineEditor()}`}
function calendarTable(){return `<div class="table-wrap"><table><thead><tr><th>名称</th><th>元年に当たる西暦</th><th>終了年（任意）</th><th>接頭辞</th><th>接尾辞</th><th></th></tr></thead><tbody>${C.arr(c.chronology?.calendars).map((x,i)=>`<tr><td><input class="input arr-bind" data-array="chronology.calendars" data-index="${i}" data-field="name" value="${C.esc(x.name||"")}"></td><td><input class="input arr-bind" data-array="chronology.calendars" data-index="${i}" data-field="startYear" type="number" value="${x.startYear??""}"></td><td><input class="input arr-bind" data-array="chronology.calendars" data-index="${i}" data-field="endYear" type="number" value="${x.endYear??""}"></td><td><input class="input arr-bind" data-array="chronology.calendars" data-index="${i}" data-field="prefix" value="${C.esc(x.prefix||x.name||"")}"></td><td><input class="input arr-bind" data-array="chronology.calendars" data-index="${i}" data-field="suffix" value="${C.esc(x.suffix||"年")}"></td><td><button class="btn danger small arr-del" data-array="chronology.calendars" data-index="${i}">削除</button></td></tr>`).join("")}</tbody></table></div>`}
function calendarForYear(y){const n=Number(y);if(!Number.isFinite(n))return "";const all=C.arr(c.chronology?.calendars).filter(x=>n>=Number(x.startYear)&&(!x.endYear||n<Number(x.endYear))).sort((a,b)=>Number(b.startYear)-Number(a.startYear));const x=all[0];if(!x)return "";const yr=n-Number(x.startYear)+1;return `${x.prefix||x.name||""}${yr===1?"元":yr}${x.suffix||"年"}`}
function timelineEditor(){return `<div class="table-wrap"><table><thead><tr><th>年/月日</th><th>西暦年</th><th>時代</th><th>出来事</th><th>概要</th><th></th></tr></thead><tbody>${C.arr(c.timeline).map((e,i)=>`<tr><td><input class="input arr-bind" data-array="timeline" data-index="${i}" data-field="date" value="${C.esc(e.date||"")}"></td><td><input class="input arr-bind" data-array="timeline" data-index="${i}" data-field="year" type="number" value="${e.year??""}"></td><td><input class="input arr-bind" data-array="timeline" data-index="${i}" data-field="era" value="${C.esc(e.era||"")}"></td><td><input class="input arr-bind" data-array="timeline" data-index="${i}" data-field="title" value="${C.esc(e.title||"")}"></td><td><input class="input arr-bind" data-array="timeline" data-index="${i}" data-field="summary" value="${C.esc(e.summary||"")}"></td><td><button class="btn danger small arr-del" data-array="timeline" data-index="${i}">削除</button></td></tr>`).join("")}</tbody></table></div>`}
function eraForYear(y){const n=Number(y);return C.arr(c.eras).find(e=>n>=Number(e.startYear??-Infinity)&&(e.endYear==null||n<=Number(e.endYear)))?.name||""}
function militaryHtml(){return `<div class="form-grid three">${input("military.personnel","現役総人員",c.military.personnel,"number")}${input("military.budget","軍事予算",c.military.budget,"number")}${input("military.budgetYear","基準年度",c.military.budgetYear)}${input("military.commanderInChief","最高指揮権",c.military.commanderInChief)}${ta("military.doctrine","国防方針・ドクトリン",c.military.doctrine)}</div><div class="toolbar"><button class="btn small" data-add="branch">＋軍種</button><a class="btn secondary small" href="country-arsenal.html?id=${c.id}">正式採用装備を管理</a></div><h3>軍種</h3>${branchesTable()}<div class="toolbar"><button class="btn small" data-add="unit">＋部隊</button></div><h3>部隊一覧</h3>${unitsTable()}`}
function branchesTable(){return `<div class="table-wrap"><table><thead><tr><th>軍種名</th><th>種類</th><th>人員</th><th>予算</th><th>司令官</th><th>指揮権</th><th></th></tr></thead><tbody>${C.arr(c.military.branches).map((b,i)=>`<tr><td><input class="input arr-bind" data-array="military.branches" data-index="${i}" data-field="name" value="${C.esc(b.name||"")}"></td><td><select class="select arr-bind" data-array="military.branches" data-index="${i}" data-field="type">${V.option(V.BRANCH_TYPES,b.type)}</select></td><td><input class="input arr-bind" data-array="military.branches" data-index="${i}" data-field="personnel" type="number" value="${b.personnel||0}"></td><td><input class="input arr-bind" data-array="military.branches" data-index="${i}" data-field="budget" type="number" value="${b.budget||0}"></td><td><input class="input arr-bind" data-array="military.branches" data-index="${i}" data-field="commander" value="${C.esc(b.commander||"")}"></td><td><input class="input arr-bind" data-array="military.branches" data-index="${i}" data-field="authority" value="${C.esc(b.authority||"")}"></td><td><button class="btn danger small arr-del" data-array="military.branches" data-index="${i}">削除</button></td></tr>`).join("")}</tbody></table></div>`}
function unitsTable(){return `<div class="table-wrap"><table><thead><tr><th>部隊名</th><th>軍種</th><th>種類</th><th>基地</th><th>人員</th><th>状態</th><th></th></tr></thead><tbody>${C.arr(c.military.units).map((u,i)=>`<tr><td><input class="input arr-bind" data-array="military.units" data-index="${i}" data-field="name" value="${C.esc(u.name||"")}"></td><td><select class="select arr-bind" data-array="military.units" data-index="${i}" data-field="branchId"><option value="">未指定</option>${C.arr(c.military.branches).map(b=>`<option value="${b.id}" ${u.branchId===b.id?"selected":""}>${C.esc(b.name)}</option>`).join("")}</select></td><td><input class="input arr-bind" data-array="military.units" data-index="${i}" data-field="type" value="${C.esc(u.type||"")}"></td><td><input class="input arr-bind" data-array="military.units" data-index="${i}" data-field="base" value="${C.esc(u.base||"")}"></td><td><input class="input arr-bind" data-array="military.units" data-index="${i}" data-field="personnel" type="number" value="${u.personnel||0}"></td><td><input class="input arr-bind" data-array="military.units" data-index="${i}" data-field="status" value="${C.esc(u.status||"現役")}"></td><td><button class="btn danger small arr-del" data-array="military.units" data-index="${i}">削除</button></td></tr>`).join("")}</tbody></table></div>`}
function postsHtml(){return `<div class="toolbar"><button class="btn small" data-add="post">＋投稿を作成</button><a class="btn ghost small" href="country-feed.html">ニュース一覧</a></div>${C.arr(c.posts).length?`<div class="table-wrap"><table><thead><tr><th>日付</th><th>分類</th><th>タイトル</th><th>公開</th><th></th></tr></thead><tbody>${c.posts.map((p,i)=>`<tr><td><input class="input arr-bind" data-array="posts" data-index="${i}" data-field="date" type="date" value="${C.esc(p.date||"")}"></td><td><select class="select arr-bind" data-array="posts" data-index="${i}" data-field="category">${V.option(V.POST_TYPES,p.category)}</select></td><td><input class="input arr-bind" data-array="posts" data-index="${i}" data-field="title" value="${C.esc(p.title||"")}"></td><td><select class="select arr-bind" data-array="posts" data-index="${i}" data-field="published"><option value="true" ${p.published!==false?"selected":""}>公開</option><option value="false" ${p.published===false?"selected":""}>下書き</option></select></td><td><a href="country-post-edit.html?id=${c.id}&post=${p.id}">編集</a> / <a href="country-post.html?id=${c.id}&post=${p.id}">表示</a> <button class="btn danger small arr-del" data-array="posts" data-index="${i}">削除</button></td></tr>`).join("")}</tbody></table></div>`:"<div class=\"empty\">投稿はありません</div>"}`}
function systemsHtml(){return `<div class="toolbar"><button class="btn small" data-add="system">＋制度</button><a class="btn secondary small" href="country-systems.html?id=${c.id}">専用ページで編集</a></div>${rowTable("systems",c.systems,["制度名","分類","概要"])} `}
function strengthHtml(){const m=c.strength.manual;return `<div class="form-grid three">${["technology:技術力","industry:産業基盤","resources:資源力","administration:行政力","diplomacy:外交力","logistics:兵站力","foodSecurity:食料安全保障","energySecurity:エネルギー安全保障"].map(x=>{const [k,l]=x.split(":");return input(`strength.manual.${k}`,`${l} (0-100)`,m[k],"number",'min="0" max="100"')}).join("")}</div><p><a href="country-strength.html?id=${c.id}">国家力の詳細分析を開く →</a></p>`}
function rowTable(key,rows,headers){let fields={ministries:["name","head","summary"],laws:["name","year","status","summary"],regions:["name","capital","population","area","summary"],eras:["name","startYear","endYear"],systems:["name","type","summary"]}[key]||headers.map((_,i)=>`f${i}`);return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join("")}<th></th></tr></thead><tbody>${C.arr(rows).map((r,i)=>`<tr>${fields.map(f=>`<td><input class="input arr-bind" data-array="${key==='ministries'||key==='laws'||key==='regions'?`administration.${key}`:key}" data-index="${i}" data-field="${f}" ${["population","area","startYear","endYear","year"].includes(f)?'type="number"':''} value="${C.esc(r[f]??"")}"></td>`).join("")}<td><button class="btn danger small arr-del" data-array="${key==='ministries'||key==='laws'||key==='regions'?`administration.${key}`:key}" data-index="${i}">削除</button></td></tr>`).join("")}</tbody></table></div>`}
function getPath(path){return path.split(".").reduce((o,k)=>o?.[k],c)}function setPath(path,value){const parts=path.split(".");let o=c;parts.slice(0,-1).forEach(k=>o=o[k]??=(/^\d+$/.test(parts[parts.indexOf(k)+1])?[]:{}));o[parts.at(-1)]=value}
function setArrayField(path,index,field,value){const a=getPath(path)||[];a[index]??={};a[index][field]=value;setPath(path,a)}
function delArray(path,index){const a=(getPath(path)||[]).slice();a.splice(index,1);setPath(path,a);dirty=true;render()}
function mark(){dirty=true;state.textContent=bottom.textContent="未保存の変更があります";state.className=bottom.className="save-state saving"}
function bind(){
 document.querySelectorAll(".bind").forEach(el=>el.addEventListener("input",()=>{let v=el.value;if(el.type==="number")v=Number(v||0);if(el.dataset.path==="isPublic")v=v==="true";if(["tags","government.rulingParties"].includes(el.dataset.path))v=v.split(",").map(x=>x.trim()).filter(Boolean);setPath(el.dataset.path,v);mark()}));
 document.querySelectorAll(".arr-bind").forEach(el=>el.addEventListener("input",()=>{let v=el.value;if(el.type==="number")v=Number(v||0);if(el.dataset.field==="published")v=v==="true";setArrayField(el.dataset.array,Number(el.dataset.index),el.dataset.field,v);mark()}));
 document.querySelectorAll(".arr-del").forEach(b=>b.addEventListener("click",e=>{e.preventDefault();delArray(b.dataset.array,Number(b.dataset.index))}));
 document.querySelectorAll(".climate-del").forEach(b=>b.addEventListener("click",()=>{c.climate.zones.splice(Number(b.dataset.index),1);mark();render()}));
 document.querySelectorAll("[data-add]").forEach(b=>b.addEventListener("click",e=>{e.preventDefault();add(b.dataset.add)}));
 document.querySelectorAll(".media-input").forEach(el=>el.addEventListener("change",async()=>{if(!el.files[0])return;try{c.media[el.dataset.key]=await Cloud.uploadMedia(c,el.files[0],el.dataset.key);mark();render()}catch(e){V.toast(e.message,"danger")}}));
 document.querySelectorAll(".media-clear").forEach(b=>b.addEventListener("click",()=>{c.media[b.dataset.key]="";mark();render()}));
 document.querySelectorAll(".row-media").forEach(el=>el.addEventListener("change",async()=>{if(!el.files[0])return;const key=await Cloud.uploadMedia(c,el.files[0],`${el.dataset.array}_${el.dataset.field}`);setArrayField(el.dataset.array,+el.dataset.index,el.dataset.field,key);mark()}));
 document.querySelectorAll(".special-lines").forEach(el=>el.addEventListener("input",()=>{if(el.dataset.special==="industries")c.industries=el.value.split("\n").filter(Boolean).map(line=>{const [name,share]=line.split(":");return{name:name.trim(),share:Number(share||0)}});mark()}));
}
function add(type){const id=C.uid();switch(type){case"ministry":c.administration.ministries.push({id,name:"新しい省庁",head:"",summary:""});break;case"law":c.administration.laws.push({id,name:"新しい法律",year:"",status:"施行中",summary:""});break;case"region":c.administration.regions.push({id,name:"新しい行政区",capital:"",population:0,area:0,summary:"",imageKey:""});break;case"revenue":c.budget.revenue.push({id,name:"新しい歳入",value:0});break;case"expenditure":c.budget.expenditure.push({id,name:"新しい歳出",value:0});break;case"product":{const e=document.getElementById("product-custom");if(e?.value.trim())c.products.push(e.value.trim());break}case"climate":{const a=document.getElementById("climate-custom")?.value.trim()||document.getElementById("climate-choice")?.value;if(a)c.climate.zones.push(a);break}case"company":c.companies.push({id,name:"新しい企業",type:"",summary:"",logoKey:""});break;case"party":c.parties.push({id,name:"新しい政党",type:"",summary:"",logoKey:""});break;case"calendar":c.chronology.calendars.push({id,name:"新しい年号",startYear:Number(c.chronology.currentGregorian)||new Date().getFullYear(),endYear:null,prefix:"",suffix:"年"});break;case"era":c.eras.push({id,name:"新しい時代",startYear:0,endYear:null});break;case"event":c.timeline.push({id,date:"",year:new Date().getFullYear(),era:"",title:"新しい出来事",summary:"",body:"",imageKey:""});break;case"branch":c.military.branches.push({id,name:"新しい軍種",type:"陸軍",personnel:0,budget:0,commander:"",authority:"",description:""});break;case"unit":c.military.units.push({id,name:"新しい部隊",branchId:"",type:"",base:"",personnel:0,status:"現役",summary:""});break;case"post":c.posts.unshift({id,title:"新しい投稿",date:new Date().toISOString().slice(0,10),category:"ニュース",body:"",imageKey:"",published:true});break;case"system":c.systems.push({id,name:"新しい制度",type:"その他",summary:"",body:""});break}mark();render()}
async function doSave(){state.textContent=bottom.textContent="保存中...";state.className=bottom.className="save-state saving";try{c.area=c.territory.area;c.capital.imageKey=c.media.capitalImageKey;c._index.strength=C.calculateStrength(c).total;c._index.completeness=C.calculateCompleteness(c);await V.save(c);dirty=false;state.textContent=bottom.textContent="保存済み";state.className=bottom.className="save-state saved";V.toast("保存しました")}catch(e){state.textContent=bottom.textContent="保存エラー";state.className=bottom.className="save-state error";V.toast(e.message||String(e),"danger")}}
document.getElementById("bottom-save").addEventListener("click",doSave);window.addEventListener("beforeunload",e=>{if(dirty){e.preventDefault();e.returnValue=""}});render();
});
