"use strict";
document.addEventListener("DOMContentLoaded",async()=>{const C0=window.MFDCOCountry,Cloud0=window.MFDCOCountryCloud;const gate0=await Cloud0.requireCountryAccess(C0.currentId(),"edit");if(!gate0.ok){const r0=document.getElementById('regions-app');if(r0)r0.innerHTML='<div class="alert warn"><strong>この国家を編集する権限がありません。</strong><br><a class="btn small" href="https://mfdco.net/join.html">MFDCOでログイン</a></div>';return;}
const C=MFDCOCountry,V=MFDCOCountryV6,Cloud=MFDCOCountryCloud,c=await V.load(),root=document.getElementById("regions-app");
let selected=C.arr(c.administration?.regions)[0]?.id||"";
function current(){return c.administration.regions.find(x=>x.id===selected)||null}
async function render(){const r=current();root.innerHTML=`<div class="wiki-builder-layout"><aside class="card wiki-page-index"><div class="toolbar"><button id="add-region" class="btn small">＋行政区</button></div>${C.arr(c.administration.regions).map(x=>`<div class="wiki-page-item ${x.id===selected?'active':''}" data-id="${x.id}"><strong>${C.esc(x.name)}</strong><div class="fine">${C.esc(x.capital||'庁所在地未設定')}</div></div>`).join('')||'<div class="empty">行政区はありません。</div>'}</aside><section id="region-detail"></section></div>`;document.querySelectorAll('.wiki-page-item').forEach(el=>el.onclick=()=>{selected=el.dataset.id;render()});document.getElementById('add-region').onclick=()=>{const x={id:C.uid(),state:'',name:'新しい行政区',capital:'',population:0,area:0,summary:'',specialties:[],culture:'',heritage:[],industries:[],climate:'',latitude:null,longitude:null,imageKey:''};c.administration.regions.push(x);selected=x.id;render()};if(r)await detail(r)}
async function detail(r){const img=await Cloud.resolveMedia(r.imageKey||'');document.getElementById('region-detail').innerHTML=`<section class="card section-card"><div class="section-head"><div><h2>${C.esc(r.name)}</h2><p>${C.esc(r.summary||'')}</p></div><button id="del-region" class="btn danger small">削除</button></div><div class="form-grid three"><div class="field"><label>州・上位区分</label><input id="rst" class="input" value="${C.esc(r.state||'')}"></div><div class="field"><label>名称</label><input id="rn" class="input" value="${C.esc(r.name)}"></div><div class="field"><label>庁所在地</label><input id="rc" class="input" value="${C.esc(r.capital||'')}"></div><div class="field"><label>人口（万人）</label><input id="rp" class="input" type="number" step="0.1" value="${C.num(r.population)/10000}"></div><div class="field"><label>面積 km²</label><input id="ra" class="input" type="number" step="any" value="${r.area||0}"></div><div class="field"><label>緯度</label><input id="rlat" class="input" type="number" step="any" value="${r.latitude??''}"></div><div class="field"><label>経度</label><input id="rlon" class="input" type="number" step="any" value="${r.longitude??''}"></div><div class="field full"><label>概要・地域特性</label><textarea id="rs" class="textarea">${C.esc(r.summary||'')}</textarea></div><div class="field"><label>特産（カンマ区切り）</label><input id="rsp" class="input" value="${C.esc(C.arr(r.specialties).join(', '))}"></div><div class="field"><label>主要産業（カンマ区切り）</label><input id="ri" class="input" value="${C.esc(C.arr(r.industries).join(', '))}"></div><div class="field"><label>遺跡・文化財（カンマ区切り）</label><input id="rh" class="input" value="${C.esc(C.arr(r.heritage).join(', '))}"></div><div class="field"><label>気候</label><input id="rcl" class="input" value="${C.esc(r.climate||'')}"></div><div class="field full"><label>文化・風習</label><textarea id="rcu" class="textarea">${C.esc(r.culture||'')}</textarea></div><div class="field"><label>代表画像</label><input id="rimg" class="input" type="file" accept="image/*">${img?`<img src="${img}" class="media-preview">`:''}</div></div><div class="toolbar"><button id="save-region" class="btn">保存</button></div></section>`;
 document.getElementById('save-region').onclick=async()=>{r.state=document.getElementById('rst').value;r.name=document.getElementById('rn').value;r.capital=document.getElementById('rc').value;r.population=Math.round(C.num(document.getElementById('rp').value)*10000);r.area=C.num(document.getElementById('ra').value);r.latitude=document.getElementById('rlat').value===''?null:C.num(document.getElementById('rlat').value);r.longitude=document.getElementById('rlon').value===''?null:C.num(document.getElementById('rlon').value);r.summary=document.getElementById('rs').value;r.specialties=document.getElementById('rsp').value.split(',').map(x=>x.trim()).filter(Boolean);r.industries=document.getElementById('ri').value.split(',').map(x=>x.trim()).filter(Boolean);r.heritage=document.getElementById('rh').value.split(',').map(x=>x.trim()).filter(Boolean);r.climate=document.getElementById('rcl').value;r.culture=document.getElementById('rcu').value;const f=document.getElementById('rimg').files[0];if(f)r.imageKey=await Cloud.uploadMedia(c,f,'region');await V.save(c);V.toast('行政区を保存しました');render()};
 document.getElementById('del-region').onclick=async()=>{if(!confirm('この行政区を削除しますか？'))return;c.administration.regions=c.administration.regions.filter(x=>x.id!==r.id);selected=c.administration.regions[0]?.id||'';await V.save(c);render()};
}
render();
});
