"use strict";
document.addEventListener("DOMContentLoaded",async()=>{
const C=MFDCOCountry,V=MFDCOCountryV6,Cloud=MFDCOCountryCloud,root=document.getElementById("feed-app");let rows=[];
if(Cloud.ready()){const {data,error}=await window.supabaseClient.rpc("mfdco_public_country_feed",{p_limit:100,p_offset:0});if(!error)rows=data||[]}
if(!rows.length){for(const c of C.load().filter(x=>x.isPublic))for(const p of C.arr(c.posts).filter(x=>x.published!==false))rows.push({record_id:p.id,country_id:c.id,country_name:c.name,country_code:c.code,post_title:p.title,post_date:p.date,category:p.category,summary:p.summary,body:p.body,details:p.details,url:p.url,image_key:p.imageKey,updated_at:c.updatedAt})}
rows.sort((a,b)=>String(b.post_date||b.updated_at).localeCompare(String(a.post_date||a.updated_at)));
const u=await Cloud.user();const mine=await Cloud.editableCountryChoices();
root.innerHTML=`<section class="card section-card"><div class="section-head"><div><h2>投稿</h2><p>国家ニュース画面から直接、新しい記事を作成できます。</p></div></div>${mine.length?`<div class="toolbar"><select id="post-country" class="select compact-select">${mine.map(c=>`<option value="${c.id}">${C.esc(c.name)}</option>`).join('')}</select><button id="new-post" class="btn">＋記事を投稿</button></div>`:`<div class="fine">投稿するには国家所有者としてログインしてください。</div>`}</section><div class="toolbar"><input id="feed-search" class="input" style="max-width:420px" placeholder="国名・記事・分類を検索"><select id="feed-category" class="select compact-select"><option value="">すべての分類</option>${V.POST_TYPES.map(x=>`<option>${x}</option>`).join("")}</select></div><div id="feed-list" class="feed-list"></div>`;
if(document.getElementById('new-post'))document.getElementById('new-post').onclick=async()=>{const id=document.getElementById('post-country').value;try{const c=await Cloud.loadCountry(id);const p={id:C.uid(),title:'新しい記事',date:new Date().toISOString().slice(0,10),category:'ニュース',summary:'',body:'',details:'',url:'',imageKey:'',published:false};c.posts.unshift(p);await V.save(c);location.href=`country-post-edit.html?id=${encodeURIComponent(c.id)}&post=${encodeURIComponent(p.id)}`}catch(e){V.toast(e.message||String(e),'danger')}};
const list=document.getElementById("feed-list");async function render(){const q=document.getElementById("feed-search").value.toLowerCase(),cat=document.getElementById("feed-category").value;const filtered=rows.filter(r=>(!q||[r.country_name,r.post_title,r.category,r.summary,r.body,r.details].join(" ").toLowerCase().includes(q))&&(!cat||r.category===cat));list.innerHTML="";for(const r of filtered){const img=await Cloud.resolveMedia(r.image_key||"");const e=document.createElement("article");e.className="feed-item";const excerpt=(r.summary||r.body||r.details||"").slice(0,220);e.innerHTML=`${img?`<img src="${img}" alt="">`:`<div class="feed-placeholder"></div>`}<div><div class="feed-meta"><span>${C.esc(r.post_date||"")}</span><span>${C.esc(r.category||"更新")}</span><span>${C.esc(r.country_name||"")}</span></div><h3><a href="country-post.html?id=${r.country_id}&post=${r.record_id}">${C.esc(r.post_title||"無題")}</a></h3><p>${C.esc(excerpt)}</p>${r.url?`<span class="fine">関連URLあり</span>`:''}<div><a href="country-post.html?id=${r.country_id}&post=${r.record_id}">記事を読む →</a> · <a href="country.html?id=${r.country_id}">${C.esc(r.country_name||"")} →</a></div></div>`;list.appendChild(e)}if(!filtered.length)list.innerHTML='<div class="empty">投稿がありません。</div>'}
document.getElementById("feed-search").addEventListener("input",render);document.getElementById("feed-category").addEventListener("change",render);render();
});
