"use strict";
document.addEventListener("DOMContentLoaded",async()=>{
const C=MFDCOCountry,V=MFDCOCountryV6,Cloud=MFDCOCountryCloud,root=document.getElementById("country-view"),c=await V.load(),id=c.id;
const st=C.calculateStrength(c),complete=C.calculateCompleteness(c);
const [flag,emblem,cover,mapImg,capitalImg]=await Promise.all([
 Cloud.resolveMedia(c.media?.flagKey||""),Cloud.resolveMedia(c.media?.emblemKey||""),Cloud.resolveMedia(c.media?.coverKey||""),Cloud.resolveMedia(c.media?.mapKey||""),Cloud.resolveMedia(c.media?.capitalImageKey||c.capital?.imageKey||"")
]);
const toc=["概要","基本情報","地理・時刻","人口・社会指標","経済・税制","食料・資源・エネルギー","政治・行政","産業・文化・気候","社会問題","歴史","軍事","外交・同盟","国家基盤","登場・二次利用","最新情報","Wiki・出典"];
const sec=(n,title,html)=>`<section id="s${n}" class="wiki-section"><h2>${title}</h2>${html}</section>`;
const kv=rows=>`<div class="table-wrap"><table><tbody>${rows.filter(x=>x[1]!==undefined&&x[1]!==null&&x[1]!=="").map(x=>`<tr><th>${C.esc(x[0])}</th><td>${x[2]?x[2]:C.esc(x[1])}</td></tr>`).join("")}</tbody></table></div>`;
const usage=c.usagePolicy||C.defaultUsagePolicy(),usageLabel={anyone:"だれでも可能",report:"要報告",application:"要申請",forbidden:"不可"};
const officialLang=C.arr(c.culture?.languages).join(" / "),officialReligion=C.arr(c.culture?.religions).join(" / ");
root.innerHTML=`<div class="hero-country" ${cover?`style="background-image:url('${cover.replace(/'/g,"%27")}')"`:""}><div class="hero-country-content">${flag?`<img class="hero-country-flag" src="${flag}" alt="${C.esc(c.nationalSymbols?.flagName||"国旗")}">`:""}<div class="eyebrow">${C.esc(c.code||"MFDCO COUNTRY")}</div><h1>${C.esc(c.name)}</h1><p>${C.esc(c.summary||"")}</p></div></div>
<div class="wiki-layout"><aside class="wiki-toc card section-card"><strong>目次</strong><div class="toc-list">${toc.map((x,i)=>`<a href="#s${i+1}">${i+1}. ${x}</a>`).join("")}</div><hr><div class="toc-list"><a href="country-strength.html?id=${id}">国家力分析</a><a href="country-stats.html?id=${id}">資料図表</a><a href="country-geography.html?id=${id}">都市・標準時</a><a href="country-regions.html?id=${id}">行政区詳細</a><a href="country-rights.html?id=${id}">利用条件</a><a href="country-wiki.html?id=${id}">Wiki</a><a href="country-map.html?id=${id}">地図データ</a><a href="country-arsenal.html?id=${id}">正式採用装備</a></div></aside><article class="wiki-content">
${sec(1,"概要",`<p>${C.esc(c.summary||"概要は未設定です。")}</p><div class="metric-grid"><div class="metric"><div class="metric-label">総人口</div><div class="metric-value population-value">${C.fmtPopulationMan(c.population)}</div></div><div class="metric"><div class="metric-label">国土面積</div><div class="metric-value">${C.fmtNum(c.territory?.area||c.area)}</div><div class="metric-sub">km²</div></div><div class="metric"><div class="metric-label">国家力</div><div class="metric-value">${st.total}</div><div class="metric-sub">${st.tier}</div></div><div class="metric"><div class="metric-label">資料完成度</div><div class="metric-value">${complete}%</div></div></div>`)}
${sec(2,"基本情報",`${emblem?`<div class="toolbar"><img src="${emblem}" alt="国章" style="width:110px;max-height:110px;object-fit:contain"></div>`:""}${kv([["正式国名",c.name],["英語名",c.englishName],["略称",c.shortName],["国コード",c.code],["国旗",c.nationalSymbols?.flagName],["国章",c.nationalSymbols?.emblemName],["国歌",c.nationalSymbols?.anthemName],["国の標語",c.nationalSymbols?.motto],["首都",c.capital?.name],["最大都市",c.identity?.largestCity],["公用語",officialLang],["公用文字",c.identity?.officialScript],["民族・住民集団",C.arr(c.culture?.ethnicGroups).join(" / ")],["国民呼称",c.identity?.demonym],["国教・主要宗教",officialReligion],["建国",c.foundation?.label],["政体",c.government?.system],["国家元首",c.government?.headOfState],["政府首班",c.government?.headOfGovernment],["通貨",`${c.economy?.currencyName||""} ${c.economy?.currencyCode||""}`],["国際電話番号",c.identity?.callingCode],["国別TLD",c.identity?.internetTld],["車両通行",c.identity?.drivingSide==="right"?"右側通行":c.identity?.drivingSide==="left"?"左側通行":c.identity?.drivingSide],["日付表記",c.identity?.dateFormat]])}`)}
${sec(3,"地理・時刻",`<div class="country-live-time"><span>現地現在時刻</span><strong id="country-live-clock">--:--:--</strong><small>${C.esc(c.timekeeping?.timezoneName||C.utcLabel(c.timekeeping?.utcOffset))}</small></div>${mapImg?`<img src="${mapImg}" class="media-preview" style="max-width:100%;max-height:480px">`:""}${capitalImg?`<img src="${capitalImg}" class="media-preview" style="max-width:100%;max-height:360px">`:""}${kv([["主権",c.sovereignty?.status],["領海",c.sovereignty?.territorialWatersKm?`${c.sovereignty.territorialWatersKm} km`:""],["EEZ",c.sovereignty?.eezArea?`${C.fmtNum(c.sovereignty.eezArea)} km²`:""],["国土面積",`${C.fmtNum(c.territory?.area||c.area)} km²`],["海岸線",c.territory?.coastlineKm?`${C.fmtNum(c.territory.coastlineKm)} km`:""],["基準都市",c.timekeeping?.referenceCity],["座標",c.timekeeping?.latitude!==null&&c.timekeeping?.longitude!==null?`${c.timekeeping.latitude}°, ${c.timekeeping.longitude}°`:"未設定"],["標準時子午線",c.timekeeping?.standardMeridian!==null?`${C.fmtNum(c.timekeeping.standardMeridian,{maximumFractionDigits:2})}°`:"未設定"],["UTC/GMT差",C.utcLabel(c.timekeeping?.utcOffset)],["標準時名称",c.timekeeping?.timezoneName]])}<h3>主要都市</h3>${simple(c.cities,"name","summary")}<p><a href="country-geography.html?id=${id}">都市・標準時の詳細 →</a></p>`)}
${sec(4,"人口・社会指標",`${kv([["総人口",C.fmtPopulationMan(c.population)],["基準時点",c.populationYear],["人口密度",c.demographics?.density?`${C.fmtNum(c.demographics.density)} 人/km²`:""],["都市人口率",c.demographics?.urbanizationPct?`${c.demographics.urbanizationPct}%`:""],["合計特殊出生率",c.demographics?.fertilityRate||""],["平均寿命（男性）",c.demographics?.lifeExpectancyMale?`${c.demographics.lifeExpectancyMale}歳`:""],["平均寿命（女性）",c.demographics?.lifeExpectancyFemale?`${c.demographics.lifeExpectancyFemale}歳`:""],["年少人口",c.populationGroups?.children?C.fmtPopulationMan(c.populationGroups.children):""],["生産年齢人口",c.populationGroups?.working?C.fmtPopulationMan(c.populationGroups.working):""],["老年人口",c.populationGroups?.elderly?C.fmtPopulationMan(c.populationGroups.elderly):""]])}<h3>社会指標</h3>${kv([["国民幸福度",c.welfare?.happinessIndex],["幸福度順位",c.welfare?.happinessRank?`${c.welfare.happinessRank}位`:""],["民主主義指数",c.welfare?.democracyIndex],["報道の自由順位",c.welfare?.pressFreedomRank?`${c.welfare.pressFreedomRank}位`:""],["汚職指数",c.welfare?.corruptionIndex],["平等指数",c.welfare?.equalityIndex],["HDI",c.welfare?.hdi]])}`)}
${sec(5,"経済・税制",`${kv([["名目GDP",C.fmtNum(c.economy?.gdp)],["基準",c.economy?.gdpYear],["一人当たりGDP",c.economy?.gdpPerCapita?C.fmtNum(c.economy.gdpPerCapita):""],["通貨",c.economy?.currencyName],["通貨価値方式",c.economy?.currencyMode],["軍事予算",C.fmtNum(c.military?.budget)]])}<h3>歳入</h3>${miniBudget(c.budget?.revenue)}<h3>歳出</h3>${miniBudget(c.budget?.expenditure)}<h3>税制</h3>${taxTable()}`)}
${sec(6,"食料・資源・エネルギー",`${kv([["食料自給率（カロリー）",c.food?.selfSufficiencyCaloriePct?`${c.food.selfSufficiencyCaloriePct}%`:""],["食料自給率（生産額）",c.food?.selfSufficiencyProductionValuePct?`${c.food.selfSufficiencyProductionValuePct}%`:""],["食料自給率（摂取熱量）",c.food?.selfSufficiencyIntakePct?`${c.food.selfSufficiencyIntakePct}%`:""],["自給率目標",c.food?.targetPct?`${c.food.targetPct}%`:""],["食料備蓄",c.food?.strategicReserveDays?`${c.food.strategicReserveDays}日`:""],["エネルギー自給率",c.energy?.selfSufficiencyPct?`${c.energy.selfSufficiencyPct}%`:""],["重要作物",C.arr(c.food?.stapleFoods).join(" / ")]])}${c.food?.notes?`<p>${C.esc(c.food.notes)}</p>`:""}<h3>資源自給率</h3>${indicatorTable("資源自給率")}<h3>エネルギー構成</h3>${energyTable()}`)}
${sec(7,"政治・行政",`${kv([["政体",c.government?.system],["立法府",c.government?.legislature],["司法",c.government?.judiciary],["与党",C.arr(c.government?.rulingParties).join(" / ")],["行政区分",c.administration?.summary]])}<h3>主要政党</h3>${simple(c.parties,"name","summary")}<h3>省庁</h3>${simple(c.administration?.ministries,"name","summary")}<h3>主要法律</h3>${simple(c.administration?.laws,"name","summary")}<h3>行政区</h3>${regionTable()}<p><a href="country-regions.html?id=${id}">行政区の詳細 →</a></p>`)}
${sec(8,"産業・文化・気候",`<h3>主要産業</h3><div class="toolbar">${C.arr(c.industries).map(x=>`<span class="pill">${C.esc(x.name||x)}${x.share?` ${x.share}%`:""}</span>`).join("")||"未設定"}</div><h3>主要企業</h3>${simple(c.companies,"name","summary")}<h3>特産物</h3><div class="toolbar">${C.arr(c.products).map(x=>`<span class="pill gray">${C.esc(x)}</span>`).join("")||"未設定"}</div><h3>気候</h3><p>${C.arr(c.climate?.zones).map(C.esc).join(" / ")}</p>${climateDiagram()}<h3>文化・宗教</h3><p>${C.esc(c.culture?.notes||"未設定")}</p>`)}
${sec(9,"社会問題",`${socialIssues()}<p><a href="country-wiki.html?id=${id}">関連Wiki記事を見る →</a></p>`)}
${sec(10,"歴史",timeline())}
${sec(11,"軍事",`${kv([["現役総人員",c.military?.personnel?C.fmtNum(c.military.personnel):"資料未記載"],["予備役",c.military?.reservePersonnel?C.fmtNum(c.military.reservePersonnel):""],["準軍事組織",c.military?.paramilitaryPersonnel?C.fmtNum(c.military.paramilitaryPersonnel):""],["軍事予算",C.fmtNum(c.military?.budget)],["徴兵制度",c.military?.conscription],["核弾頭",c.military?.nuclearWarheads?`${C.fmtNum(c.military.nuclearWarheads)}発`:""],["最高指揮権",c.military?.commanderInChief],["最高司令部",c.military?.headquarters],["国防方針",c.military?.doctrine]])}<h3>軍種</h3>${simple(c.military?.branches,"name","description")}<h3>兵役・徴兵制度</h3>${serviceTable()}<h3>部隊</h3>${simple(c.military?.units,"name","summary")}<h3>主要戦力</h3>${equipmentTable()}<p><a href="country-arsenal.html?id=${id}">正式採用装備一覧 →</a></p>`)}
${sec(12,"外交・同盟",`<div id="relation-list"><div class="fine">外交関係を読み込んでいます…</div></div><p><a href="country-exchange.html?id=${id}">外交・交流ページ →</a></p>`)}
${sec(13,"国家基盤",`${simple(c.systems,"name","summary")}<p><a href="country-systems.html?id=${id}">制度の詳細 →</a></p>`)}
${sec(14,"登場・二次利用",`<div class="usage-summary"><strong>${C.esc(usageLabel[usage.appearance]||usage.appearance||"未設定")}</strong><span>この国家を茶番・映像・小説等へ登場させる条件</span></div><p><a class="btn secondary small" href="country-rights.html?id=${id}">詳しい利用条件を見る →</a></p>`)}
${sec(15,"最新情報",posts())}
${sec(16,"Wiki・出典",`${simple(c.wikiPages,"title","summary",x=>`country-article.html?id=${id}&page=${x.id}`)}<p><a href="country-wiki.html?id=${id}">Wikiサブページ一覧 →</a></p><h3>資料出典</h3>${sourceTable()}`)}
</article><aside class="wiki-infobox card section-card">${flag?`<img src="${flag}" alt="国旗">`:""}<h3>${C.esc(c.name)}</h3>${kv([["首都",c.capital?.name],["人口",C.fmtPopulationMan(c.population)],["面積",`${C.fmtNum(c.territory?.area||c.area)} km²`],["標準時",C.utcLabel(c.timekeeping?.utcOffset)],["GDP",C.fmtNum(c.economy?.gdp)],["国家力",`${st.total} / ${st.tier}`],["完成度",`${complete}%`]])}<div class="toolbar"><a class="btn small" href="country-edit.html?id=${id}">編集</a><a class="btn ghost small" href="country-manage.html?id=${id}">管理</a></div></aside></div>`;
function miniBudget(a){const total=C.arr(a).reduce((s,x)=>s+C.num(x.value),0);return `<div class="table-wrap"><table><tbody>${C.arr(a).slice(0,16).map(x=>`<tr><td>${C.esc(x.name)}</td><td>${C.fmtNum(x.value)}</td><td>${total?Math.round(C.num(x.value)/total*1000)/10:0}%</td></tr>`).join("")}</tbody></table></div>`}
function simple(a,title,sub,linker){return C.arr(a).length?`<div class="table-wrap"><table><tbody>${C.arr(a).slice(0,80).map(x=>`<tr><td>${linker?`<a href="${linker(x)}">${C.esc(x[title]||"")}</a>`:C.esc(x[title]||"")}</td><td>${C.esc(x[sub]||"")}</td></tr>`).join("")}</tbody></table></div>`:`<div class="empty">未設定</div>`}
function regionTable(){return C.arr(c.administration?.regions).length?`<div class="table-wrap"><table><thead><tr><th>州</th><th>行政区</th><th>庁所在地</th><th>人口</th><th>特性</th></tr></thead><tbody>${c.administration.regions.slice(0,80).map(r=>`<tr><td>${C.esc(r.state||"")}</td><td>${C.esc(r.name)}</td><td>${C.esc(r.capital||"")}</td><td>${C.fmtPopulationMan(r.population)}</td><td>${C.esc(r.summary||[...C.arr(r.specialties),r.culture].filter(Boolean).join(" / ").slice(0,160))}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">未設定</div>'}
function indicatorTable(category){const rows=C.arr(c.indicators).filter(x=>x.category===category);return rows.length?`<div class="table-wrap"><table><thead><tr><th>指標</th><th>値</th><th>基準</th><th>備考</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${C.esc(x.name||"")}</td><td>${C.esc(`${x.value??""}${x.unit?` ${x.unit}`:""}`)}</td><td>${C.esc(x.year||"")}</td><td>${C.esc(x.notes||"")}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">未設定</div>'}
function timeline(){const ev=C.arr(c.timeline).slice().sort((a,b)=>C.num(a.year,999999)-C.num(b.year,999999));return ev.length?`<div class="timeline-compact"><div class="table-wrap"><table><thead><tr><th>年</th><th>時代</th><th>出来事</th></tr></thead><tbody>${ev.map(e=>`<tr><td>${C.esc(e.date||e.year)}</td><td>${C.esc(e.era||"")}</td><td><a href="country-history.html?id=${id}&event=${e.id}">${C.esc(e.title)}</a><div class="fine">${C.esc(e.summary||"")}</div></td></tr>`).join("")}</tbody></table></div></div>`:`<div class="empty">年表は未設定です。</div>`}
function posts(){return C.arr(c.posts).filter(p=>p.published!==false).slice(0,8).map(p=>`<div class="relation-line"><div class="feed-meta"><span>${C.esc(p.date||"")}</span><span>${C.esc(p.category||"")}</span></div><strong><a href="country-post.html?id=${id}&post=${p.id}">${C.esc(p.title)}</a></strong>${p.summary?`<div class="fine">${C.esc(p.summary.slice(0,160))}</div>`:""}</div>`).join("")||'<div class="empty">投稿はありません。</div>'}
function serviceTable(){return C.arr(c.military?.serviceTypes).length?`<div class="table-wrap"><table><thead><tr><th>兵役種別</th><th>詳細</th></tr></thead><tbody>${c.military.serviceTypes.map(x=>`<tr><td>${C.esc(x.name)}</td><td>${C.esc(x.details||"")}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">未設定</div>'}
function equipmentTable(){return C.arr(c.military?.equipment).length?`<div class="table-wrap"><table><thead><tr><th>装備</th><th>種別</th><th>数量</th><th>備考</th></tr></thead><tbody>${c.military.equipment.map(x=>`<tr><td>${C.esc(x.name||"")}</td><td>${C.esc(x.type||"")}</td><td>${C.esc(x.count??"")}</td><td>${C.esc(x.notes||"")}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">未設定</div>'}
function taxTable(){const a=C.arr(c.taxation?.taxes);return a.length?`<div class="table-wrap"><table><thead><tr><th>税目</th><th>分類</th><th>標準税率</th><th>課税対象</th><th>備考</th></tr></thead><tbody>${a.map(x=>`<tr><td>${C.esc(x.name||"")}</td><td>${C.esc(x.type||"")}</td><td>${x.rate!==null&&x.rate!==undefined&&x.rate!==""?C.esc(x.rate)+"%":"—"}</td><td>${C.esc(x.base||"")}</td><td>${C.esc(x.notes||"")}</td></tr>`).join("")}</tbody></table></div>${c.taxation?.summary?`<p>${C.esc(c.taxation.summary)}</p>`:""}`:'<div class="empty">税制は未設定です。</div>'}
function energyTable(){const a=C.arr(c.energy?.sources);return a.length?`<div class="table-wrap"><table><thead><tr><th>エネルギー源</th><th>構成比</th><th>自給率</th><th>備考</th></tr></thead><tbody>${a.map(x=>`<tr><td>${C.esc(x.name||"")}</td><td>${C.esc(x.sharePct??"")}${x.sharePct!==null&&x.sharePct!==undefined?"%":""}</td><td>${C.esc(x.selfSufficiencyPct??"")}${x.selfSufficiencyPct!==null&&x.selfSufficiencyPct!==undefined?"%":""}</td><td>${C.esc(x.notes||"")}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">エネルギー構成は未設定です。</div>'}
function climateDiagram(){const t=C.arr(c.climate?.monthlyTemps),r=C.arr(c.climate?.monthlyRainfall);if(!t.some(x=>x!==null&&x!=="")&&!r.some(x=>x!==null&&x!==""))return '<div class="empty">雨温図データは未設定です。</div>';const months=['1','2','3','4','5','6','7','8','9','10','11','12'],W=720,H=260,pad=38,maxR=Math.max(1,...r.map(x=>C.num(x))),vals=t.filter(x=>x!==null&&x!=="").map(Number),minT=vals.length?Math.min(...vals,0):0,maxT=vals.length?Math.max(...vals,30):30,yr=v=>H-pad-(C.num(v)/maxR)*(H-pad*2),yt=v=>H-pad-((C.num(v)-minT)/(Math.max(1,maxT-minT)))*(H-pad*2),x=i=>pad+i*((W-pad*2)/11);const bars=r.map((v,i)=>`<rect x="${x(i)-12}" y="${yr(v)}" width="24" height="${H-pad-yr(v)}" class="rain-bar"/>`).join(''),pts=t.map((v,i)=>`${x(i)},${yt(v)}`).join(' '),labs=months.map((m,i)=>`<text x="${x(i)}" y="${H-10}" text-anchor="middle">${m}</text>`).join('');return `<div class="climate-chart"><svg viewBox="0 0 ${W} ${H}" role="img" aria-label="雨温図"><line x1="${pad}" y1="${H-pad}" x2="${W-pad}" y2="${H-pad}" class="axis"/>${bars}<polyline points="${pts}" class="temp-line"/>${t.map((v,i)=>`<circle cx="${x(i)}" cy="${yt(v)}" r="3" class="temp-dot"/>`).join('')}${labs}</svg><div class="climate-legend"><span>■ 降水量</span><span>● 気温</span></div></div>`}
function socialIssues(){const own=C.arr(c.socialIssues);const wiki=C.arr(c.wikiPages).filter(x=>x.type==="社会課題").map(x=>({name:x.title,category:"Wiki",severity:"",summary:x.summary||"",pageId:x.id}));const rows=[...own,...wiki];return rows.length?`<div class="table-wrap"><table><thead><tr><th>課題</th><th>分類</th><th>深刻度</th><th>概要</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.pageId?`<a href="country-article.html?id=${id}&page=${x.pageId}">${C.esc(x.name)}</a>`:C.esc(x.name||"")}</td><td>${C.esc(x.category||"")}</td><td>${C.esc(x.severity||"")}</td><td>${C.esc(x.summary||"")}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">社会問題は未設定です。</div>'}
function sourceTable(){return C.arr(c.sources).length?`<div class="table-wrap"><table><thead><tr><th>資料</th><th>形式</th><th>頁数</th><th>備考</th></tr></thead><tbody>${c.sources.map(x=>`<tr><td>${C.esc(x.title||"")}</td><td>${C.esc(x.type||"")}</td><td>${C.esc(x.pages||"")}</td><td>${C.esc(x.notes||"")}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">出典情報は未登録です。</div>'}
function updateClock(){const el=document.getElementById("country-live-clock");if(!el)return;const off=C.num(c.timekeeping?.utcOffset,0),d=new Date(Date.now()+off*3600000),hh=String(d.getUTCHours()).padStart(2,"0"),mm=String(d.getUTCMinutes()).padStart(2,"0"),ss=String(d.getUTCSeconds()).padStart(2,"0");el.textContent=`${hh}:${mm}:${ss}`}updateClock();setInterval(updateClock,1000);
try{const rel=await Cloud.relations(id);let names={};if(Cloud.ready()&&rel.length){const ids=[...new Set(rel.flatMap(r=>[r.country_a_id,r.country_b_id]).filter(x=>x&&x!==id))];if(ids.length){const q=await window.supabaseClient.from("countries").select("id,name").in("id",ids);for(const x of q.data||[])names[x.id]=x.name}}document.getElementById("relation-list").innerHTML=rel.length?rel.map(r=>{const other=r.country_a_id===id?r.country_b_id:r.country_a_id;return `<div class="relation-line"><div><strong>${C.esc(C.relationLabel(r.relation_type))}</strong> ${names[other]?`<a href="country.html?id=${other}">${C.esc(names[other])}</a>`:C.esc(r.title||"")}</div><div class="feed-meta"><span class="pill ${r.status==='active'?'ok':'gray'}">${C.esc(r.status)}</span>${r.started_at?`<span>${C.esc(String(r.started_at).slice(0,10))}</span>`:""}</div>${r.terms?`<div class="fine">${C.esc(typeof r.terms==='string'?r.terms:JSON.stringify(r.terms))}</div>`:""}</div>`}).join(""):'<div class="empty">公開されている外交関係はありません。</div>'}catch{}
try{const u=await Cloud.user(),box=document.querySelector('.wiki-infobox .toolbar');if(u&&Cloud.ready()&&box){const q=await window.supabaseClient.from('country_follows').select('country_id').eq('country_id',c.id).eq('user_id',u.id).maybeSingle(),following=!!q.data,b=document.createElement('button');b.className='btn ghost small';b.textContent=following?'フォロー中':'国家をフォロー';b.onclick=async()=>{const r=following?await window.supabaseClient.from('country_follows').delete().eq('country_id',c.id).eq('user_id',u.id):await window.supabaseClient.from('country_follows').insert({country_id:c.id,user_id:u.id});if(r.error)V.toast(r.error.message,'danger');else location.reload()};box.appendChild(b)}}catch{}
});
